SimpleITK: itk::simple::ProcessObject Class Reference
itk::simple::ProcessObject Class Reference abstract
Base class for SimpleITK classes based on ProcessObject.
#include <sitkProcessObject.h>
Classes
struct EventCommand
Public Types
using Self = ProcessObject
Public Member Functions
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual std::string GetName () const =0
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual std::string ToString () const
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Static Public Member Functions
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions
template<class TImageType >
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType , unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType >
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T >
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Private Member Functions
unsigned long AddObserverToActiveProcessObject (EventCommand &e)
void RemoveObserverFromActiveProcessObject (EventCommand &e)
Private Attributes
itk::ProcessObject * m_ActiveProcess
std::list< EventCommand > m_Commands
bool m_Debug
unsigned int m_NumberOfThreads
unsigned int m_NumberOfWorkUnits
float m_ProgressMeasurement
Friends
class itk::simple::Command
Detailed Description
Base class for SimpleITK classes based on ProcessObject.
Examples
FilterProgressReporting/FilterProgressReporting.cxx.
Definition at line 51 of file sitkProcessObject.h.
Member Typedef Documentation
Self
using itk::simple::ProcessObject::Self = ProcessObject
Definition at line 55 of file sitkProcessObject.h.
Constructor & Destructor Documentation
ProcessObject()
itk::simple::ProcessObject::ProcessObject ()
Default Constructor that takes no arguments and initializes default parameters
~ProcessObject()
virtual itk::simple::ProcessObject::~ProcessObject () virtual
Default Destructor
Member Function Documentation
Abort()
virtual void itk::simple::ProcessObject::Abort () virtual
Sets an abort flag on the active process.
Requests the current active process to abort. Additional, progress or iteration event may occur. If aborted then, an AbortEvent should occur. The Progress should be set to 1.0 after aborting.
The expected behavior is that not exception should be throw out of this processes Execute method. Additionally, the results returned are valid but undefined content. The content may be only partially updated, uninitialized or the a of size zero.
If there is no active process the method has no effect.
AddCommand() [1/2]
virtual int itk::simple::ProcessObject::AddCommand (itk::simple::EventEnum event, const std::function< void()> & func) virtual
Directly add a callback to observe an event.
This overloaded method can take a C++ lambda function as a second argument.
AddCommand() [2/2]
virtual int itk::simple::ProcessObject::AddCommand (itk::simple::EventEnum event, itk::simple::Command & cmd) virtual
Add a Command Object to observer the event.
The Command object's Execute method will be invoked when the internal ITK Object has the event. These events only occur during this ProcessObject's Execute method when the ITK filter is running. The command occurs in the same thread as this objects Execute methods was called in.
An internal reference is made between the Command and this ProcessObject which enable automatic removal of the command when deleted. This enables both object to exist as stack based object and be automatically cleaned up.
Unless specified otherwise, it's safe to get any value during execution. "Measurements" will have valid values only after the Execute method has returned. "Active Measurements" will have valid values during events, and access the underlying ITK object.
Deleting a command this object has during a command call-back will produce undefined behavior.
For more information see the page CommandPage.
Note
The return value is reserved for latter usage.
Examples
DemonsRegistration1/DemonsRegistration1.cxx, DemonsRegistration2/DemonsRegistration2.cxx, FilterProgressReporting/FilterProgressReporting.cxx, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
AddITKObserver()
virtual unsigned long itk::simple::ProcessObject::AddITKObserver (const itk::EventObject & , itk::Command *) protected virtual
Reimplemented in itk::simple::ImageRegistrationMethod.
AddObserverToActiveProcessObject()
unsigned long itk::simple::ProcessObject::AddObserverToActiveProcessObject (EventCommand & e) private
CastImageToITK()
template<class TImageType > static TImageType::ConstPointer itk::simple::ProcessObject::CastImageToITK (const Image & img) inline static protected
Definition at line 342 of file sitkProcessObject.h.
References itk::simple::Image::GetDimension(), itk::simple::Image::GetITKBase(), itk::simple::Image::GetPixelIDTypeAsString(), itk::simple::GetPixelIDValueAsString(), and sitkExceptionMacro.
CastITKToImage() [1/3]
template<class TPixelType , unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector> static Image itk::simple::ProcessObject::CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > * img) inline static protected
Definition at line 368 of file sitkProcessObject.h.
References itk::simple::GetVectorImageFromImage().
CastITKToImage() [2/3]
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector> static Image itk::simple::ProcessObject::CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > * img) inline static protected
Definition at line 379 of file sitkProcessObject.h.
References itk::simple::GetVectorImageFromImage().
CastITKToImage() [3/3]
template<class TImageType > static Image itk::simple::ProcessObject::CastITKToImage (TImageType * img) inline static protected
Definition at line 360 of file sitkProcessObject.h.
DebugOff()
virtual void itk::simple::ProcessObject::DebugOff () virtual
Turn debugging output on/off.
Enabling debugging prints additional information to stdout about the execution of the internal filters.
DebugOn()
virtual void itk::simple::ProcessObject::DebugOn () virtual
Turn debugging output on/off.
Enabling debugging prints additional information to stdout about the execution of the internal filters.
GetActiveProcess()
virtual itk::ProcessObject* itk::simple::ProcessObject::GetActiveProcess () protected virtual
GetDebug()
virtual bool itk::simple::ProcessObject::GetDebug () const virtual
Get the value of the debug flag.
GetGlobalDefaultCoordinateTolerance()
static double itk::simple::ProcessObject::GetGlobalDefaultCoordinateTolerance () static
Access the global tolerance to determine congruent spaces.
The default tolerance is governed by the GlobalDefaultCoordinateTolerance and the GlobalDefaultDirectionTolerance properties, defaulting to 1.0e-6. The default tolerance for spatial comparison is then scaled by the voxelSpacing for coordinates (i.e. the coordinates must be the same to within one part per million). For the direction cosines the values must be within the current absolute tolerance.
GetGlobalDefaultDebug()
static bool itk::simple::ProcessObject::GetGlobalDefaultDebug () static
Get the value of the default debug flag.
GetGlobalDefaultDirectionTolerance()
static double itk::simple::ProcessObject::GetGlobalDefaultDirectionTolerance () static
Access the global tolerance to determine congruent spaces.
The default tolerance is governed by the GlobalDefaultCoordinateTolerance and the GlobalDefaultDirectionTolerance properties, defaulting to 1.0e-6. The default tolerance for spatial comparison is then scaled by the voxelSpacing for coordinates (i.e. the coordinates must be the same to within one part per million). For the direction cosines the values must be within the current absolute tolerance.
GetGlobalDefaultNumberOfThreads()
static unsigned int itk::simple::ProcessObject::GetGlobalDefaultNumberOfThreads () static
Set/Get the default threader used for process objects.
The possible available multi-threaders are:
"POOL" itk::PoolMultiThreader
"TBB" itk::TBBThreader (optional)
"PLATFORM" itk::PlatformMultiThreader
The default and the available multi-threaders are dependent upon ITK's configuration. See the ITK documentation for more details about the behavior of the multi-threaders.
The environment variable "ITK_GLOBAL_DEFAULT_THREADER" can be used to initialize this value.
The set method returns true when the threader string is valid and ITK's default is updated, otherwise false is returned. The threader argument is not case sensitive.
See also
itk::MultiThreaderBase itk::PoolMultiThreader itk::TBBThreader itk::PlatformMultiThreader
GetGlobalDefaultThreader()
static std::string itk::simple::ProcessObject::GetGlobalDefaultThreader () static
Set/Get the default threader used for process objects.
The possible available multi-threaders are:
"POOL" itk::PoolMultiThreader
"TBB" itk::TBBThreader (optional)
"PLATFORM" itk::PlatformMultiThreader
The default and the available multi-threaders are dependent upon ITK's configuration. See the ITK documentation for more details about the behavior of the multi-threaders.
The environment variable "ITK_GLOBAL_DEFAULT_THREADER" can be used to initialize this value.
The set method returns true when the threader string is valid and ITK's default is updated, otherwise false is returned. The threader argument is not case sensitive.
See also
itk::MultiThreaderBase itk::PoolMultiThreader itk::TBBThreader itk::PlatformMultiThreader
GetGlobalWarningDisplay()
static bool itk::simple::ProcessObject::GetGlobalWarningDisplay () static
Manage warnings produced by ITK.
Enabled by default, this parameter may enable printing of warnings indicating unstable state or parameters during execution. It is a global value set for all ITK filters and processes.
GetITKEventObject()
static const itk::EventObject& itk::simple::ProcessObject::GetITKEventObject (EventEnum e) static protected
GetName()
virtual std::string itk::simple::ProcessObject::GetName () const pure virtual
return user readable name for the filter
Implemented in itk::simple::LandmarkBasedTransformInitializerFilter, itk::simple::ImageRegistrationMethod, itk::simple::CenteredTransformInitializerFilter, itk::simple::ImageSeriesWriter, itk::simple::BSplineTransformInitializerFilter, itk::simple::CenteredVersorTransformInitializerFilter, itk::simple::ImageFileReader, itk::simple::ImageFileWriter, itk::simple::CastImageFilter, itk::simple::ImportImageFilter, itk::simple::ImageSeriesReader, itk::simple::HashImageFilter, itk::simple::LabelIntensityStatisticsImageFilter, itk::simple::LabelShapeStatisticsImageFilter, itk::simple::DiffeomorphicDemonsRegistrationFilter, itk::simple::FastSymmetricForcesDemonsRegistrationFilter, itk::simple::LevelSetMotionRegistrationFilter, itk::simple::CannySegmentationLevelSetImageFilter, itk::simple::DemonsRegistrationFilter, itk::simple::SymmetricForcesDemonsRegistrationFilter, itk::simple::PatchBasedDenoisingImageFilter, itk::simple::ScalarChanAndVeseDenseLevelSetImageFilter, itk::simple::N4BiasFieldCorrectionImageFilter, itk::simple::LabelOverlapMeasuresImageFilter, itk::simple::GeodesicActiveContourLevelSetImageFilter, itk::simple::LabelStatisticsImageFilter, itk::simple::ThresholdSegmentationLevelSetImageFilter, itk::simple::ShapeDetectionLevelSetImageFilter, itk::simple::LaplacianSegmentationLevelSetImageFilter, itk::simple::ResampleImageFilter, itk::simple::MultiLabelSTAPLEImageFilter, itk::simple::IsolatedConnectedImageFilter, itk::simple::FastMarchingBaseImageFilter, itk::simple::GaussianImageSource, itk::simple::DanielssonDistanceMapImageFilter, itk::simple::DiscreteGaussianDerivativeImageFilter, itk::simple::STAPLEImageFilter, itk::simple::GridImageSource, itk::simple::LabelMapContourOverlayImageFilter, itk::simple::OtsuThresholdImageFilter, itk::simple::ExtractImageFilter, itk::simple::WarpImageFilter, itk::simple::FastMarchingUpwindGradientImageFilter, itk::simple::GaborImageSource, itk::simple::AntiAliasBinaryImageFilter, itk::simple::ObjectnessMeasureImageFilter, itk::simple::RecursiveGaussianImageFilter, itk::simple::DoubleThresholdImageFilter, itk::simple::SignedDanielssonDistanceMapImageFilter, itk::simple::LandweberDeconvolutionImageFilter, itk::simple::ConfidenceConnectedImageFilter, itk::simple::VectorConfidenceConnectedImageFilter, itk::simple::HuangThresholdImageFilter, itk::simple::IntermodesThresholdImageFilter, itk::simple::IsoDataThresholdImageFilter, itk::simple::KittlerIllingworthThresholdImageFilter, itk::simple::LiThresholdImageFilter, itk::simple::MaximumEntropyThresholdImageFilter, itk::simple::MomentsThresholdImageFilter, itk::simple::OtsuMultipleThresholdsImageFilter, itk::simple::RenyiEntropyThresholdImageFilter, itk::simple::ShanbhagThresholdImageFilter, itk::simple::SLICImageFilter, itk::simple::TriangleThresholdImageFilter, itk::simple::YenThresholdImageFilter, itk::simple::CannyEdgeDetectionImageFilter, itk::simple::CollidingFrontsImageFilter, itk::simple::DisplacementFieldJacobianDeterminantFilter, itk::simple::ProjectedLandweberDeconvolutionImageFilter, itk::simple::VotingBinaryIterativeHoleFillingImageFilter, itk::simple::IsolatedWatershedImageFilter, itk::simple::LabelMapMaskImageFilter, itk::simple::RelabelComponentImageFilter, itk::simple::BinaryOpeningByReconstructionImageFilter, itk::simple::DiscreteGaussianImageFilter, itk::simple::RichardsonLucyDeconvolutionImageFilter, itk::simple::VotingBinaryImageFilter, itk::simple::BinaryDilateImageFilter, itk::simple::BinaryErodeImageFilter, itk::simple::BinaryThresholdProjectionImageFilter, itk::simple::ZeroCrossingBasedEdgeDetectionImageFilter, itk::simple::ClosingByReconstructionImageFilter, itk::simple::OpeningByReconstructionImageFilter, itk::simple::RegionalMaximaImageFilter, itk::simple::PasteImageFilter, itk::simple::FastMarchingImageFilter, itk::simple::ShotNoiseImageFilter, itk::simple::SignedMaurerDistanceMapImageFilter, itk::simple::SimpleContourExtractorImageFilter, itk::simple::TransformToDisplacementFieldFilter, itk::simple::MaskedFFTNormalizedCorrelationImageFilter, itk::simple::RegionalMinimaImageFilter, itk::simple::ScalarToRGBColormapImageFilter, itk::simple::BilateralImageFilter, itk::simple::ThresholdMaximumConnectedComponentsImageFilter, itk::simple::NeighborhoodConnectedImageFilter, itk::simple::WienerDeconvolutionImageFilter, itk::simple::BinaryMinMaxCurvatureFlowImageFilter, itk::simple::ConnectedThresholdImageFilter, itk::simple::BinaryClosingByReconstructionImageFilter, itk::simple::BinaryMorphologicalClosingImageFilter, itk::simple::InvertDisplacementFieldImageFilter, itk::simple::BinaryProjectionImageFilter, itk::simple::DICOMOrientImageFilter, itk::simple::BinaryMorphologicalOpeningImageFilter, itk::simple::StatisticsImageFilter, itk::simple::VotingBinaryHoleFillingImageFilter, itk::simple::BinaryImageToLabelMapFilter, itk::simple::TikhonovDeconvolutionImageFilter, itk::simple::CurvatureAnisotropicDiffusionImageFilter, itk::simple::InverseDeconvolutionImageFilter, itk::simple::MinMaxCurvatureFlowImageFilter, itk::simple::MorphologicalWatershedFromMarkersImageFilter, itk::simple::AdditiveGaussianNoiseImageFilter, itk::simple::BinaryMedianImageFilter, itk::simple::ConvolutionImageFilter, itk::simple::CurvatureFlowImageFilter, itk::simple::ErodeObjectMorphologyImageFilter, itk::simple::GradientAnisotropicDiffusionImageFilter, itk::simple::InverseDisplacementFieldImageFilter, itk::simple::ShiftScaleImageFilter, itk::simple::ApproximateSignedDistanceMapImageFilter, itk::simple::DerivativeImageFilter, itk::simple::UnsharpMaskImageFilter, itk::simple::ZeroFluxNeumannPadImageFilter, itk::simple::BinaryThresholdImageFilter, itk::simple::HistogramMatchingImageFilter, itk::simple::MorphologicalWatershedImageFilter, itk::simple::ExpandImageFilter, itk::simple::AdaptiveHistogramEqualizationImageFilter, itk::simple::BinaryGrindPeakImageFilter, itk::simple::IntensityWindowingImageFilter, itk::simple::MaskImageFilter, itk::simple::MaskNegatedImageFilter, itk::simple::BinaryContourImageFilter, itk::simple::BinaryReconstructionByDilationImageFilter, itk::simple::BinaryReconstructionByErosionImageFilter, itk::simple::FFTConvolutionImageFilter, itk::simple::PhysicalPointImageSource, itk::simple::ScalarImageKmeansImageFilter, itk::simple::ZeroCrossingImageFilter, itk::simple::ThresholdImageFilter, itk::simple::BlackTopHatImageFilter, itk::simple::FFTNormalizedCorrelationImageFilter, itk::simple::GrayscaleMorphologicalClosingImageFilter, itk::simple::GrayscaleMorphologicalOpeningImageFilter, itk::simple::SliceImageFilter, itk::simple::GradientImageFilter, itk::simple::LabelOverlayImageFilter, itk::simple::GradientRecursiveGaussianImageFilter, itk::simple::LabelVotingImageFilter, itk::simple::LaplacianImageFilter, itk::simple::ReconstructionByDilationImageFilter, itk::simple::ReconstructionByErosionImageFilter, itk::simple::WhiteTopHatImageFilter, itk::simple::DilateObjectMorphologyImageFilter, itk::simple::GrayscaleGeodesicDilateImageFilter, itk::simple::GrayscaleGeodesicErodeImageFilter, itk::simple::SpeckleNoiseImageFilter, itk::simple::AddImageFilter, itk::simple::ClampImageFilter, itk::simple::HMinimaImageFilter, itk::simple::SigmoidImageFilter, itk::simple::MirrorPadImageFilter, itk::simple::BinaryFillholeImageFilter, itk::simple::HConcaveImageFilter, itk::simple::HConvexImageFilter, itk::simple::LaplacianSharpeningImageFilter, itk::simple::SaltAndPepperNoiseImageFilter, itk::simple::StandardDeviationProjectionImageFilter, itk::simple::SumProjectionImageFilter, itk::simple::ConstantPadImageFilter, itk::simple::LabelContourImageFilter, itk::simple::SmoothingRecursiveGaussianImageFilter, itk::simple::ValuedRegionalMaximaImageFilter, itk::simple::EqualImageFilter, itk::simple::GrayscaleConnectedClosingImageFilter, itk::simple::GrayscaleConnectedOpeningImageFilter, itk::simple::GreaterEqualImageFilter, itk::simple::GreaterImageFilter, itk::simple::LabelMapOverlayImageFilter, itk::simple::LessEqualImageFilter, itk::simple::LessImageFilter, itk::simple::NotEqualImageFilter, itk::simple::RankImageFilter, itk::simple::BinaryNotImageFilter, itk::simple::JoinSeriesImageFilter, itk::simple::LabelToRGBImageFilter, itk::simple::MaximumProjectionImageFilter, itk::simple::MeanProjectionImageFilter, itk::simple::MedianProjectionImageFilter, itk::simple::NaryMaximumImageFilter, itk::simple::SubtractImageFilter, itk::simple::ValuedRegionalMinimaImageFilter, itk::simple::FFTPadImageFilter, itk::simple::AbsoluteValueDifferenceImageFilter, itk::simple::FlipImageFilter, itk::simple::GrayscaleGrindPeakImageFilter, itk::simple::MinimumProjectionImageFilter, itk::simple::NaryAddImageFilter, itk::simple::BinaryMagnitudeImageFilter, itk::simple::BinaryPruningImageFilter, itk::simple::ComposeImageFilter, itk::simple::GrayscaleDilateImageFilter, itk::simple::GrayscaleErodeImageFilter, itk::simple::LabelMapToBinaryImageFilter, itk::simple::MergeLabelMapFilter, itk::simple::MorphologicalGradientImageFilter, itk::simple::RescaleIntensityImageFilter, itk::simple::ConnectedComponentImageFilter, itk::simple::GrayscaleFillholeImageFilter, itk::simple::HausdorffDistanceImageFilter, itk::simple::MedianImageFilter, itk::simple::NormalizeToConstantImageFilter, itk::simple::TileImageFilter, itk::simple::VectorIndexSelectionCastImageFilter, itk::simple::BinShrinkImageFilter, itk::simple::FFTShiftImageFilter, itk::simple::GradientMagnitudeRecursiveGaussianImageFilter, itk::simple::HMaximaImageFilter, itk::simple::LaplacianRecursiveGaussianImageFilter, itk::simple::MeanImageFilter, itk::simple::MinimumMaximumImageFilter, itk::simple::PowImageFilter, itk::simple::RegionOfInterestImageFilter, itk::simple::SquaredDifferenceImageFilter, itk::simple::FastApproximateRankImageFilter, itk::simple::WrapPadImageFilter, itk::simple::CropImageFilter, itk::simple::IsoContourDistanceImageFilter, itk::simple::IterativeInverseDisplacementFieldImageFilter, itk::simple::NoiseImageFilter, itk::simple::BSplineDecompositionImageFilter, itk::simple::RealAndImaginaryToComplexImageFilter, itk::simple::StochasticFractalDimensionImageFilter, itk::simple::GradientMagnitudeImageFilter, itk::simple::NotImageFilter, itk::simple::ScalarConnectedComponentImageFilter, itk::simple::VectorConnectedComponentImageFilter, itk::simple::AcosImageFilter, itk::simple::AsinImageFilter, itk::simple::CosImageFilter, itk::simple::LabelUniqueLabelMapFilter, itk::simple::ShrinkImageFilter, itk::simple::ChangeLabelImageFilter, itk::simple::HalfHermitianToRealInverseFFTImageFilter, itk::simple::ChangeLabelLabelMapFilter, itk::simple::LabelImageToLabelMapFilter, itk::simple::PermuteAxesImageFilter, itk::simple::RelabelLabelMapFilter, itk::simple::LabelMapToRGBImageFilter, itk::simple::AtanImageFilter, itk::simple::CheckerBoardImageFilter, itk::simple::CyclicShiftImageFilter, itk::simple::InvertIntensityImageFilter, itk::simple::SimilarityIndexImageFilter, itk::simple::SobelEdgeDetectionImageFilter, itk::simple::BoxMeanImageFilter, itk::simple::BoxSigmaImageFilter, itk::simple::NormalizedCorrelationImageFilter, itk::simple::OrImageFilter, itk::simple::XorImageFilter, itk::simple::BinaryThinningImageFilter, itk::simple::BinomialBlurImageFilter, itk::simple::AndImageFilter, itk::simple::DivideFloorImageFilter, itk::simple::DivideRealImageFilter, itk::simple::ForwardFFTImageFilter, itk::simple::AggregateLabelMapFilter, itk::simple::BitwiseNotImageFilter, itk::simple::LabelMapToLabelImageFilter, itk::simple::RealToHalfHermitianForwardFFTImageFilter, itk::simple::UnaryMinusImageFilter, itk::simple::Atan2ImageFilter, itk::simple::ModulusImageFilter, itk::simple::InverseFFTImageFilter, itk::simple::NormalizeImageFilter, itk::simple::MagnitudeAndPhaseToComplexImageFilter, itk::simple::MaximumImageFilter, itk::simple::MinimumImageFilter, itk::simple::EdgePotentialImageFilter, itk::simple::VectorMagnitudeImageFilter, itk::simple::DivideImageFilter, itk::simple::MultiplyImageFilter, itk::simple::AbsImageFilter, itk::simple::BoundedReciprocalImageFilter, itk::simple::ComplexToImaginaryImageFilter, itk::simple::ComplexToModulusImageFilter, itk::simple::ComplexToPhaseImageFilter, itk::simple::ComplexToRealImageFilter, itk::simple::ExpImageFilter, itk::simple::ExpNegativeImageFilter, itk::simple::Log10ImageFilter, itk::simple::LogImageFilter, itk::simple::RoundImageFilter, itk::simple::SinImageFilter, itk::simple::SqrtImageFilter, itk::simple::SquareImageFilter, itk::simple::TanImageFilter, itk::simple::TernaryAddImageFilter, itk::simple::TernaryMagnitudeImageFilter, itk::simple::TernaryMagnitudeSquaredImageFilter, itk::simple::TobogganImageFilter, and itk::simple::TransformGeometryImageFilter.
GetNumberOfThreads()
virtual unsigned int itk::simple::ProcessObject::GetNumberOfThreads () const virtual
The number of threads used when executing a filter if the filter is multi-threaded.
With ITK version 5, this parameter now corresponds to itk::MultiThreaderBase::SetMaximumNumberOfThreads and the corresponding get method. The is clamped to be limited by the "global" maximum.
Note
The "POOL" multi-threader cannot reduce the number of threads. As the "POOL" multi-threader has a single instance of a thread pool, the number of threads will increased for subsequent processes.
GetNumberOfWorkUnits()
virtual unsigned int itk::simple::ProcessObject::GetNumberOfWorkUnits () const virtual
The work (image) is requested to be divided into this number of sub-tasks.
If zero then, the default number from the process object and the multi-threader will be used.
Note
The "PLATFORM" multi-threader set the number of threads equal to the number of work units.
GetProgress()
virtual float itk::simple::ProcessObject::GetProgress () const virtual
An Active Measurement of the progress of execution.
Get the execution progress of the current process object. The progress is a floating number in [0,1] with 0 meaning no progress and 1 meaning the filter has completed execution (or aborted).
This is an Active Measurement so it can be accessed during Events during the execution.
GlobalDefaultDebugOff()
static void itk::simple::ProcessObject::GlobalDefaultDebugOff () static
GlobalDefaultDebugOn()
static void itk::simple::ProcessObject::GlobalDefaultDebugOn () static
Turn default debugging output value on/off.
This is the initial values used for new classes and procedural methods.
GlobalWarningDisplayOff()
static void itk::simple::ProcessObject::GlobalWarningDisplayOff () static
Manage warnings produced by ITK.
Enabled by default, this parameter may enable printing of warnings indicating unstable state or parameters during execution. It is a global value set for all ITK filters and processes.
GlobalWarningDisplayOn()
static void itk::simple::ProcessObject::GlobalWarningDisplayOn () static
Manage warnings produced by ITK.
Enabled by default, this parameter may enable printing of warnings indicating unstable state or parameters during execution. It is a global value set for all ITK filters and processes.
HasCommand()
virtual bool itk::simple::ProcessObject::HasCommand (itk::simple::EventEnum event) const virtual
Query of this object has any registered commands for event.
OnActiveProcessDelete()
virtual void itk::simple::ProcessObject::OnActiveProcessDelete () protected virtual
Reimplemented in itk::simple::ImageRegistrationMethod.
onCommandDelete()
virtual void itk::simple::ProcessObject::onCommandDelete (const itk::simple::Command * cmd) protected virtual noexcept
PreUpdate()
virtual void itk::simple::ProcessObject::PreUpdate (itk::ProcessObject * p) protected virtual
Reimplemented in itk::simple::ImageRegistrationMethod.
RemoveAllCommands()
virtual void itk::simple::ProcessObject::RemoveAllCommands () virtual
Remove all registered commands.
Calling when this object is invoking anther command will produce undefined behavior.
RemoveITKObserver()
virtual void itk::simple::ProcessObject::RemoveITKObserver (EventCommand & e) protected virtual
Reimplemented in itk::simple::ImageRegistrationMethod.
RemoveObserverFromActiveProcessObject()
void itk::simple::ProcessObject::RemoveObserverFromActiveProcessObject (EventCommand & e) private
SetDebug()
virtual void itk::simple::ProcessObject::SetDebug (bool debugFlag) virtual
Get the value of the debug flag.
SetGlobalDefaultCoordinateTolerance()
static void itk::simple::ProcessObject::SetGlobalDefaultCoordinateTolerance (double) static
Access the global tolerance to determine congruent spaces.
The default tolerance is governed by the GlobalDefaultCoordinateTolerance and the GlobalDefaultDirectionTolerance properties, defaulting to 1.0e-6. The default tolerance for spatial comparison is then scaled by the voxelSpacing for coordinates (i.e. the coordinates must be the same to within one part per million). For the direction cosines the values must be within the current absolute tolerance.
SetGlobalDefaultDebug()
static void itk::simple::ProcessObject::SetGlobalDefaultDebug (bool debugFlag) static
SetGlobalDefaultDirectionTolerance()
static void itk::simple::ProcessObject::SetGlobalDefaultDirectionTolerance (double) static
Access the global tolerance to determine congruent spaces.
The default tolerance is governed by the GlobalDefaultCoordinateTolerance and the GlobalDefaultDirectionTolerance properties, defaulting to 1.0e-6. The default tolerance for spatial comparison is then scaled by the voxelSpacing for coordinates (i.e. the coordinates must be the same to within one part per million). For the direction cosines the values must be within the current absolute tolerance.
SetGlobalDefaultNumberOfThreads()
static void itk::simple::ProcessObject::SetGlobalDefaultNumberOfThreads (unsigned int n) static
Set the number of threads with which new process objects are initialized.
If the environment variable "ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS" is defined, then this value is initialized as defined in the environment. Otherwise, the value will be initialized with the number of virtual CPUs on the system.
Note
After the "POOL" multi-thread initially constructs the thread pool, this value will has no effect on the thread pool.
SetGlobalDefaultThreader()
static bool itk::simple::ProcessObject::SetGlobalDefaultThreader (const std::string & threader) static
Set/Get the default threader used for process objects.
The possible available multi-threaders are:
"POOL" itk::PoolMultiThreader
"TBB" itk::TBBThreader (optional)
"PLATFORM" itk::PlatformMultiThreader
The default and the available multi-threaders are dependent upon ITK's configuration. See the ITK documentation for more details about the behavior of the multi-threaders.
The environment variable "ITK_GLOBAL_DEFAULT_THREADER" can be used to initialize this value.
The set method returns true when the threader string is valid and ITK's default is updated, otherwise false is returned. The threader argument is not case sensitive.
See also
itk::MultiThreaderBase itk::PoolMultiThreader itk::TBBThreader itk::PlatformMultiThreader
SetGlobalWarningDisplay()
static void itk::simple::ProcessObject::SetGlobalWarningDisplay (bool flag) static
Manage warnings produced by ITK.
Enabled by default, this parameter may enable printing of warnings indicating unstable state or parameters during execution. It is a global value set for all ITK filters and processes.
SetNumberOfThreads()
virtual void itk::simple::ProcessObject::SetNumberOfThreads (unsigned int n) virtual
The number of threads used when executing a filter if the filter is multi-threaded.
With ITK version 5, this parameter now corresponds to itk::MultiThreaderBase::SetMaximumNumberOfThreads and the corresponding get method. The is clamped to be limited by the "global" maximum.
Note
The "POOL" multi-threader cannot reduce the number of threads. As the "POOL" multi-threader has a single instance of a thread pool, the number of threads will increased for subsequent processes.
SetNumberOfWorkUnits()
virtual void itk::simple::ProcessObject::SetNumberOfWorkUnits (unsigned int n) virtual
The work (image) is requested to be divided into this number of sub-tasks.
If zero then, the default number from the process object and the multi-threader will be used.
Note
The "PLATFORM" multi-threader set the number of threads equal to the number of work units.
ToString()
virtual std::string itk::simple::ProcessObject::ToString () const virtual
Reimplemented in itk::simple::LandmarkBasedTransformInitializerFilter, itk::simple::ImageRegistrationMethod, itk::simple::CenteredTransformInitializerFilter, itk::simple::BSplineTransformInitializerFilter, itk::simple::CenteredVersorTransformInitializerFilter, itk::simple::ImageFileReader, itk::simple::ImageReaderBase, itk::simple::CastImageFilter, itk::simple::ImageFileWriter, itk::simple::HashImageFilter, itk::simple::ImageSeriesWriter, itk::simple::ImportImageFilter, itk::simple::ImageSeriesReader, itk::simple::LabelIntensityStatisticsImageFilter, itk::simple::LabelShapeStatisticsImageFilter, itk::simple::DiffeomorphicDemonsRegistrationFilter, itk::simple::FastSymmetricForcesDemonsRegistrationFilter, itk::simple::LevelSetMotionRegistrationFilter, itk::simple::CannySegmentationLevelSetImageFilter, itk::simple::DemonsRegistrationFilter, itk::simple::SymmetricForcesDemonsRegistrationFilter, itk::simple::PatchBasedDenoisingImageFilter, itk::simple::ScalarChanAndVeseDenseLevelSetImageFilter, itk::simple::N4BiasFieldCorrectionImageFilter, itk::simple::LabelOverlapMeasuresImageFilter, itk::simple::GeodesicActiveContourLevelSetImageFilter, itk::simple::LabelStatisticsImageFilter, itk::simple::ThresholdSegmentationLevelSetImageFilter, itk::simple::ShapeDetectionLevelSetImageFilter, itk::simple::LaplacianSegmentationLevelSetImageFilter, itk::simple::ResampleImageFilter, itk::simple::MultiLabelSTAPLEImageFilter, itk::simple::IsolatedConnectedImageFilter, itk::simple::FastMarchingBaseImageFilter, itk::simple::GaussianImageSource, itk::simple::DanielssonDistanceMapImageFilter, itk::simple::DiscreteGaussianDerivativeImageFilter, itk::simple::STAPLEImageFilter, itk::simple::GridImageSource, itk::simple::LabelMapContourOverlayImageFilter, itk::simple::OtsuThresholdImageFilter, itk::simple::ExtractImageFilter, itk::simple::WarpImageFilter, itk::simple::FastMarchingUpwindGradientImageFilter, itk::simple::GaborImageSource, itk::simple::AntiAliasBinaryImageFilter, itk::simple::ObjectnessMeasureImageFilter, itk::simple::RecursiveGaussianImageFilter, itk::simple::DoubleThresholdImageFilter, itk::simple::SignedDanielssonDistanceMapImageFilter, itk::simple::LandweberDeconvolutionImageFilter, itk::simple::ConfidenceConnectedImageFilter, itk::simple::VectorConfidenceConnectedImageFilter, itk::simple::HuangThresholdImageFilter, itk::simple::IntermodesThresholdImageFilter, itk::simple::IsoDataThresholdImageFilter, itk::simple::KittlerIllingworthThresholdImageFilter, itk::simple::LiThresholdImageFilter, itk::simple::MaximumEntropyThresholdImageFilter, itk::simple::MomentsThresholdImageFilter, itk::simple::OtsuMultipleThresholdsImageFilter, itk::simple::RenyiEntropyThresholdImageFilter, itk::simple::ShanbhagThresholdImageFilter, itk::simple::SLICImageFilter, itk::simple::TriangleThresholdImageFilter, itk::simple::YenThresholdImageFilter, itk::simple::CannyEdgeDetectionImageFilter, itk::simple::CollidingFrontsImageFilter, itk::simple::DisplacementFieldJacobianDeterminantFilter, itk::simple::ProjectedLandweberDeconvolutionImageFilter, itk::simple::VotingBinaryIterativeHoleFillingImageFilter, itk::simple::IsolatedWatershedImageFilter, itk::simple::LabelMapMaskImageFilter, itk::simple::RelabelComponentImageFilter, itk::simple::BinaryOpeningByReconstructionImageFilter, itk::simple::DiscreteGaussianImageFilter, itk::simple::RichardsonLucyDeconvolutionImageFilter, itk::simple::VotingBinaryImageFilter, itk::simple::BinaryDilateImageFilter, itk::simple::BinaryErodeImageFilter, itk::simple::BinaryThresholdProjectionImageFilter, itk::simple::ZeroCrossingBasedEdgeDetectionImageFilter, itk::simple::ClosingByReconstructionImageFilter, itk::simple::OpeningByReconstructionImageFilter, itk::simple::RegionalMaximaImageFilter, itk::simple::PasteImageFilter, itk::simple::FastMarchingImageFilter, itk::simple::ShotNoiseImageFilter, itk::simple::SignedMaurerDistanceMapImageFilter, itk::simple::SimpleContourExtractorImageFilter, itk::simple::TransformToDisplacementFieldFilter, itk::simple::MaskedFFTNormalizedCorrelationImageFilter, itk::simple::RegionalMinimaImageFilter, itk::simple::ScalarToRGBColormapImageFilter, itk::simple::BilateralImageFilter, itk::simple::ThresholdMaximumConnectedComponentsImageFilter, itk::simple::NeighborhoodConnectedImageFilter, itk::simple::WienerDeconvolutionImageFilter, itk::simple::BinaryMinMaxCurvatureFlowImageFilter, itk::simple::ConnectedThresholdImageFilter, itk::simple::BinaryClosingByReconstructionImageFilter, itk::simple::BinaryMorphologicalClosingImageFilter, itk::simple::InvertDisplacementFieldImageFilter, itk::simple::BinaryProjectionImageFilter, itk::simple::DICOMOrientImageFilter, itk::simple::BinaryMorphologicalOpeningImageFilter, itk::simple::StatisticsImageFilter, itk::simple::VotingBinaryHoleFillingImageFilter, itk::simple::BinaryImageToLabelMapFilter, itk::simple::TikhonovDeconvolutionImageFilter, itk::simple::CurvatureAnisotropicDiffusionImageFilter, itk::simple::InverseDeconvolutionImageFilter, itk::simple::MinMaxCurvatureFlowImageFilter, itk::simple::MorphologicalWatershedFromMarkersImageFilter, itk::simple::AdditiveGaussianNoiseImageFilter, itk::simple::BinaryMedianImageFilter, itk::simple::ConvolutionImageFilter, itk::simple::CurvatureFlowImageFilter, itk::simple::ErodeObjectMorphologyImageFilter, itk::simple::GradientAnisotropicDiffusionImageFilter, itk::simple::InverseDisplacementFieldImageFilter, itk::simple::ShiftScaleImageFilter, itk::simple::ApproximateSignedDistanceMapImageFilter, itk::simple::DerivativeImageFilter, itk::simple::UnsharpMaskImageFilter, itk::simple::ZeroFluxNeumannPadImageFilter, itk::simple::BinaryThresholdImageFilter, itk::simple::HistogramMatchingImageFilter, itk::simple::MorphologicalWatershedImageFilter, itk::simple::ExpandImageFilter, itk::simple::AdaptiveHistogramEqualizationImageFilter, itk::simple::BinaryGrindPeakImageFilter, itk::simple::IntensityWindowingImageFilter, itk::simple::MaskImageFilter, itk::simple::MaskNegatedImageFilter, itk::simple::BinaryContourImageFilter, itk::simple::BinaryReconstructionByDilationImageFilter, itk::simple::BinaryReconstructionByErosionImageFilter, itk::simple::FFTConvolutionImageFilter, itk::simple::PhysicalPointImageSource, itk::simple::ScalarImageKmeansImageFilter, itk::simple::ZeroCrossingImageFilter, itk::simple::ThresholdImageFilter, itk::simple::BlackTopHatImageFilter, itk::simple::FFTNormalizedCorrelationImageFilter, itk::simple::GrayscaleMorphologicalClosingImageFilter, itk::simple::GrayscaleMorphologicalOpeningImageFilter, itk::simple::SliceImageFilter, itk::simple::GradientImageFilter, itk::simple::LabelOverlayImageFilter, itk::simple::GradientRecursiveGaussianImageFilter, itk::simple::LabelVotingImageFilter, itk::simple::LaplacianImageFilter, itk::simple::ReconstructionByDilationImageFilter, itk::simple::ReconstructionByErosionImageFilter, itk::simple::WhiteTopHatImageFilter, itk::simple::DilateObjectMorphologyImageFilter, itk::simple::GrayscaleGeodesicDilateImageFilter, itk::simple::GrayscaleGeodesicErodeImageFilter, itk::simple::SpeckleNoiseImageFilter, itk::simple::AddImageFilter, itk::simple::ClampImageFilter, itk::simple::HMinimaImageFilter, itk::simple::SigmoidImageFilter, itk::simple::MirrorPadImageFilter, itk::simple::BinaryFillholeImageFilter, itk::simple::HConcaveImageFilter, itk::simple::HConvexImageFilter, itk::simple::LaplacianSharpeningImageFilter, itk::simple::SaltAndPepperNoiseImageFilter, itk::simple::StandardDeviationProjectionImageFilter, itk::simple::SumProjectionImageFilter, itk::simple::ConstantPadImageFilter, itk::simple::LabelContourImageFilter, itk::simple::SmoothingRecursiveGaussianImageFilter, itk::simple::ValuedRegionalMaximaImageFilter, itk::simple::EqualImageFilter, itk::simple::GrayscaleConnectedClosingImageFilter, itk::simple::GrayscaleConnectedOpeningImageFilter, itk::simple::GreaterEqualImageFilter, itk::simple::GreaterImageFilter, itk::simple::LabelMapOverlayImageFilter, itk::simple::LessEqualImageFilter, itk::simple::LessImageFilter, itk::simple::NotEqualImageFilter, itk::simple::RankImageFilter, itk::simple::BinaryNotImageFilter, itk::simple::JoinSeriesImageFilter, itk::simple::LabelToRGBImageFilter, itk::simple::MaximumProjectionImageFilter, itk::simple::MeanProjectionImageFilter, itk::simple::MedianProjectionImageFilter, itk::simple::NaryMaximumImageFilter, itk::simple::SubtractImageFilter, itk::simple::ValuedRegionalMinimaImageFilter, itk::simple::FFTPadImageFilter, itk::simple::AbsoluteValueDifferenceImageFilter, itk::simple::FlipImageFilter, itk::simple::GrayscaleGrindPeakImageFilter, itk::simple::MinimumProjectionImageFilter, itk::simple::NaryAddImageFilter, itk::simple::BinaryMagnitudeImageFilter, itk::simple::BinaryPruningImageFilter, itk::simple::ComposeImageFilter, itk::simple::GrayscaleDilateImageFilter, itk::simple::GrayscaleErodeImageFilter, itk::simple::LabelMapToBinaryImageFilter, itk::simple::MergeLabelMapFilter, itk::simple::MorphologicalGradientImageFilter, itk::simple::RescaleIntensityImageFilter, itk::simple::ConnectedComponentImageFilter, itk::simple::GrayscaleFillholeImageFilter, itk::simple::HausdorffDistanceImageFilter, itk::simple::MedianImageFilter, itk::simple::NormalizeToConstantImageFilter, itk::simple::TileImageFilter, itk::simple::VectorIndexSelectionCastImageFilter, itk::simple::BinShrinkImageFilter, itk::simple::FFTShiftImageFilter, itk::simple::GradientMagnitudeRecursiveGaussianImageFilter, itk::simple::HMaximaImageFilter, itk::simple::LaplacianRecursiveGaussianImageFilter, itk::simple::MeanImageFilter, itk::simple::MinimumMaximumImageFilter, itk::simple::PowImageFilter, itk::simple::RegionOfInterestImageFilter, itk::simple::SquaredDifferenceImageFilter, itk::simple::FastApproximateRankImageFilter, itk::simple::WrapPadImageFilter, itk::simple::CropImageFilter, itk::simple::IsoContourDistanceImageFilter, itk::simple::IterativeInverseDisplacementFieldImageFilter, itk::simple::NoiseImageFilter, itk::simple::BSplineDecompositionImageFilter, itk::simple::RealAndImaginaryToComplexImageFilter, itk::simple::StochasticFractalDimensionImageFilter, itk::simple::GradientMagnitudeImageFilter, itk::simple::NotImageFilter, itk::simple::ScalarConnectedComponentImageFilter, itk::simple::VectorConnectedComponentImageFilter, itk::simple::AcosImageFilter, itk::simple::AsinImageFilter, itk::simple::CosImageFilter, itk::simple::LabelUniqueLabelMapFilter, itk::simple::ShrinkImageFilter, itk::simple::ChangeLabelImageFilter, itk::simple::HalfHermitianToRealInverseFFTImageFilter, itk::simple::ChangeLabelLabelMapFilter, itk::simple::LabelImageToLabelMapFilter, itk::simple::PermuteAxesImageFilter, itk::simple::RelabelLabelMapFilter, itk::simple::LabelMapToRGBImageFilter, itk::simple::AtanImageFilter, itk::simple::CheckerBoardImageFilter, itk::simple::CyclicShiftImageFilter, itk::simple::InvertIntensityImageFilter, itk::simple::SimilarityIndexImageFilter, itk::simple::SobelEdgeDetectionImageFilter, itk::simple::BoxMeanImageFilter, itk::simple::BoxSigmaImageFilter, itk::simple::NormalizedCorrelationImageFilter, itk::simple::OrImageFilter, itk::simple::XorImageFilter, itk::simple::BinaryThinningImageFilter, itk::simple::BinomialBlurImageFilter, itk::simple::AndImageFilter, itk::simple::DivideFloorImageFilter, itk::simple::DivideRealImageFilter, itk::simple::ForwardFFTImageFilter, itk::simple::AggregateLabelMapFilter, itk::simple::BitwiseNotImageFilter, itk::simple::LabelMapToLabelImageFilter, itk::simple::RealToHalfHermitianForwardFFTImageFilter, itk::simple::UnaryMinusImageFilter, itk::simple::Atan2ImageFilter, itk::simple::ModulusImageFilter, itk::simple::InverseFFTImageFilter, itk::simple::NormalizeImageFilter, itk::simple::MagnitudeAndPhaseToComplexImageFilter, itk::simple::MaximumImageFilter, itk::simple::MinimumImageFilter, itk::simple::EdgePotentialImageFilter, itk::simple::VectorMagnitudeImageFilter, itk::simple::DivideImageFilter, itk::simple::MultiplyImageFilter, itk::simple::AbsImageFilter, itk::simple::BoundedReciprocalImageFilter, itk::simple::ComplexToImaginaryImageFilter, itk::simple::ComplexToModulusImageFilter, itk::simple::ComplexToPhaseImageFilter, itk::simple::ComplexToRealImageFilter, itk::simple::ExpImageFilter, itk::simple::ExpNegativeImageFilter, itk::simple::Log10ImageFilter, itk::simple::LogImageFilter, itk::simple::RoundImageFilter, itk::simple::SinImageFilter, itk::simple::SqrtImageFilter, itk::simple::SquareImageFilter, itk::simple::TanImageFilter, itk::simple::TernaryAddImageFilter, itk::simple::TernaryMagnitudeImageFilter, itk::simple::TernaryMagnitudeSquaredImageFilter, itk::simple::TobogganImageFilter, and itk::simple::TransformGeometryImageFilter.
ToStringHelper() [1/4]
static std::ostream& itk::simple::ProcessObject::ToStringHelper (std::ostream & os, const char & v) static protected
Output operator to os with conversion to a printable type.
That is char types are presumed to be numbers, and converted to int.
ToStringHelper() [2/4]
static std::ostream& itk::simple::ProcessObject::ToStringHelper (std::ostream & os, const signed char & v) static protected
Output operator to os with conversion to a printable type.
That is char types are presumed to be numbers, and converted to int.
ToStringHelper() [3/4]
template<typename T > static std::ostream& itk::simple::ProcessObject::ToStringHelper (std::ostream & os, const T & v) inline static protected
Output operator to os with conversion to a printable type.
That is char types are presumed to be numbers, and converted to int.
Definition at line 398 of file sitkProcessObject.h.
ToStringHelper() [4/4]
static std::ostream& itk::simple::ProcessObject::ToStringHelper (std::ostream & os, const unsigned char & v) static protected
Output operator to os with conversion to a printable type.
That is char types are presumed to be numbers, and converted to int.
Friends And Related Function Documentation
itk::simple::Command
friend class itk::simple::Command friend
Definition at line 334 of file sitkProcessObject.h.
Member Data Documentation
m_ActiveProcess
itk::ProcessObject* itk::simple::ProcessObject::m_ActiveProcess private
Definition at line 429 of file sitkProcessObject.h.
m_Commands
std::list<EventCommand> itk::simple::ProcessObject::m_Commands private
Definition at line 427 of file sitkProcessObject.h.
m_Debug
bool itk::simple::ProcessObject::m_Debug private
Definition at line 422 of file sitkProcessObject.h.
m_NumberOfThreads
unsigned int itk::simple::ProcessObject::m_NumberOfThreads private
Definition at line 424 of file sitkProcessObject.h.
m_NumberOfWorkUnits
unsigned int itk::simple::ProcessObject::m_NumberOfWorkUnits private
Definition at line 425 of file sitkProcessObject.h.
m_ProgressMeasurement
float itk::simple::ProcessObject::m_ProgressMeasurement private
Definition at line 432 of file sitkProcessObject.h.
The documentation for this class was generated from the following file:
sitkProcessObject.h