SimpleITK: itk::simple Namespace Reference
itk::simple Namespace Reference
Namespaces
namespace detail
namespace ioutils
Classes
class AbsImageFilter
Computes the absolute value of each pixel.
class AbsoluteValueDifferenceImageFilter
Implements pixel-wise the computation of absolute value difference.
class AcosImageFilter
Computes the inverse cosine of each pixel.
class AdaptiveHistogramEqualizationImageFilter
Power Law Adaptive Histogram Equalization.
class AddImageFilter
Pixel-wise addition of two images.
class AdditiveGaussianNoiseImageFilter
Alter an image with additive Gaussian white noise.
class AffineTransform
An affine transformation about a fixed center with translation for a 2D or 3D coordinate.
class AggregateLabelMapFilter
Collapses all labels into the first label.
class AndImageFilter
Implements the AND bitwise operator pixel-wise between two images.
class AntiAliasBinaryImageFilter
A method for estimation of a surface from a binary volume.
class ApproximateSignedDistanceMapImageFilter
Create a map of the approximate signed distance from the boundaries of a binary image.
class AsinImageFilter
Computes the sine of each pixel.
class Atan2ImageFilter
Computes two argument inverse tangent.
class AtanImageFilter
Computes the one-argument inverse tangent of each pixel.
struct BasicPixelID
class BilateralImageFilter
Blurs an image while preserving edges.
class BinaryClosingByReconstructionImageFilter
binary closing by reconstruction of an image.
class BinaryContourImageFilter
Labels the pixels on the border of the objects in a binary image.
class BinaryDilateImageFilter
Fast binary dilation of a single intensity value in the image.
class BinaryErodeImageFilter
Fast binary erosion of a single intensity value in the image.
class BinaryFillholeImageFilter
Remove holes not connected to the boundary of the image.
class BinaryGrindPeakImageFilter
Remove the objects not connected to the boundary of the image.
class BinaryImageToLabelMapFilter
Label the connected components in a binary image and produce a collection of label objects.
class BinaryMagnitudeImageFilter
Computes the square root of the sum of squares of corresponding input pixels.
class BinaryMedianImageFilter
Applies a version of the median filter optimized for binary images.
class BinaryMinMaxCurvatureFlowImageFilter
Denoise a binary image using min/max curvature flow.
class BinaryMorphologicalClosingImageFilter
binary morphological closing of an image.
class BinaryMorphologicalOpeningImageFilter
binary morphological opening of an image.
class BinaryNotImageFilter
Implements the BinaryNot logical operator pixel-wise between two images.
class BinaryOpeningByReconstructionImageFilter
binary morphological closing of an image.
class BinaryProjectionImageFilter
Binary projection.
class BinaryPruningImageFilter
This filter removes "spurs" of less than a certain length in the input image.
class BinaryReconstructionByDilationImageFilter
binary reconstruction by dilation of an image
class BinaryReconstructionByErosionImageFilter
binary reconstruction by erosion of an image
class BinaryThinningImageFilter
This filter computes one-pixel-wide edges of the input image.
class BinaryThresholdImageFilter
Binarize an input image by thresholding.
class BinaryThresholdProjectionImageFilter
BinaryThreshold projection.
class BinomialBlurImageFilter
Performs a separable blur on each dimension of an image.
class BinShrinkImageFilter
Reduce the size of an image by an integer factor in each dimension while performing averaging of an input neighborhood.
class BitwiseNotImageFilter
Implements pixel-wise generic operation on one image.
class BlackTopHatImageFilter
Black top hat extracts local minima that are smaller than the structuring element.
class BoundedReciprocalImageFilter
Computes 1/(1+x) for each pixel in the image.
class BoxMeanImageFilter
Implements a fast rectangular mean filter using the accumulator approach.
class BoxSigmaImageFilter
Implements a fast rectangular sigma filter using the accumulator approach.
class BSplineDecompositionImageFilter
Calculates the B-Spline coefficients of an image. Spline order may be from 0 to 5.
class BSplineTransform
A deformable transform over a bounded spatial domain using a BSpline representation for a 2D or 3D coordinate space.
class BSplineTransformInitializerFilter
BSplineTransformInitializerFilter is a helper class intended to initialize the control point grid such that it has a physically consistent definition. It sets the transform domain origin, physical dimensions and direction from information obtained from the image. It also sets the mesh size if asked to do so by calling SetTransformDomainMeshSize()before calling InitializeTransform().
class CannyEdgeDetectionImageFilter
This filter is an implementation of a Canny edge detector for scalar-valued images.
class CannySegmentationLevelSetImageFilter
Segments structures in images based on image features derived from pseudo-canny-edges.
class CastImageFilter
A hybrid cast image filter to convert images to other types of images.
class CenteredTransformInitializerFilter
CenteredTransformInitializerFilter is a helper class intended to initialize the center of rotation and the translation of Transforms having the center of rotation among their parameters.
class CenteredVersorTransformInitializerFilter
CenteredVersorTransformInitializerFilter is a helper class intended to initialize the center of rotation, versor, and translation of the VersorRigid3DTransform.
class ChangeLabelImageFilter
Change Sets of Labels.
class ChangeLabelLabelMapFilter
Replace the label Ids of selected LabelObjects with new label Ids.
class CheckerBoardImageFilter
Combines two images in a checkerboard pattern.
class ClampImageFilter
Casts input pixels to output pixel type and clamps the output pixel values to a specified range.
class ClosingByReconstructionImageFilter
Closing by reconstruction of an image.
class CollidingFrontsImageFilter
Selects a region of space where two independent fronts run towards each other.
class Command
An implementation of the Command design pattern for callback.
class ComplexToImaginaryImageFilter
Computes pixel-wise the imaginary part of a complex image.
class ComplexToModulusImageFilter
Computes pixel-wise the Modulus of a complex image.
class ComplexToPhaseImageFilter
Computes pixel-wise the modulus of a complex image.
class ComplexToRealImageFilter
Computes pixel-wise the real(x) part of a complex image.
class ComposeImageFilter
ComposeImageFilter combine several scalar images into a multicomponent image.
class ComposeScaleSkewVersor3DTransform
This transform applies a versor rotation and translation & scale/skew to the space.
class CompositeTransform
This class contains a stack of transforms and concatenates them by composition.
struct ConditionalValue
class ConfidenceConnectedImageFilter
Segment pixels with similar statistics using connectivity.
class ConnectedComponentImageFilter
Label the objects in a binary image.
class ConnectedThresholdImageFilter
Label pixels that are connected to a seed and lie within a range of values.
class ConstantPadImageFilter
Increase the image size by padding with a constant value.
class ConvolutionImageFilter
Convolve a given image with an arbitrary image kernel.
class CosImageFilter
Computes the cosine of each pixel.
class CropImageFilter
Decrease the image size by cropping the image by an itk::Size at both the upper and lower bounds of the largest possible region.
class CurvatureAnisotropicDiffusionImageFilter
class CurvatureFlowImageFilter
Denoise an image using curvature driven flow.
class CyclicShiftImageFilter
Perform a cyclic spatial shift of image intensities on the image grid.
class DanielssonDistanceMapImageFilter
This filter computes the distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
class DemonsRegistrationFilter
Deformably register two images using the demons algorithm.
class DerivativeImageFilter
Computes the directional derivative of an image. The directional derivative at each pixel location is computed by convolution with a derivative operator of user-specified order.
class DICOMOrientImageFilter
Permute axes and flip images as needed to obtain an approximation to the desired orientation.
class DiffeomorphicDemonsRegistrationFilter
Deformably register two images using a diffeomorphic demons algorithm.
class DilateObjectMorphologyImageFilter
dilation of an object in an image
class DiscreteGaussianDerivativeImageFilter
Calculates image derivatives using discrete derivative gaussian kernels. This filter calculates Gaussian derivative by separable convolution of an image and a discrete Gaussian derivative operator (kernel).
class DiscreteGaussianImageFilter
Blurs an image by separable convolution with discrete gaussian kernels. This filter performs Gaussian blurring by separable convolution of an image and a discrete Gaussian operator (kernel).
class DisplacementFieldJacobianDeterminantFilter
Computes a scalar image from a vector image (e.g., deformation field) input, where each output scalar at each pixel is the Jacobian determinant of the vector field at that location. This calculation is correct in the case where the vector image is a "displacement" from the current location. The computation for the jacobian determinant is: det[ dT/dx ] = det[ I + du/dx ].
class DisplacementFieldTransform
A dense deformable transform over a bounded spatial domain for 2D or 3D coordinates space.
class DivideFloorImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class DivideImageFilter
Pixel-wise division of two images.
class DivideRealImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class DoubleThresholdImageFilter
Binarize an input image using double thresholding.
class EdgePotentialImageFilter
Computes the edge potential of an image from the image gradient.
class EqualImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class ErodeObjectMorphologyImageFilter
Erosion of an object in an image.
class Euler2DTransform
A rigid 2D transform with rotation in radians around a fixed center with translation.
class Euler3DTransform
A rigid 3D transform with rotation in radians around a fixed center with translation.
class ExpandImageFilter
Expand the size of an image by an integer factor in each dimension.
class ExpImageFilter
Computes the exponential function of each pixel.
class ExpNegativeImageFilter
Computes the function exp(-K.x) for each input pixel.
class ExtractImageFilter
Decrease the image size by cropping the image to the selected region bounds.
class FastApproximateRankImageFilter
A separable rank filter.
class FastMarchingBaseImageFilter
Apply the Fast Marching method to solve an Eikonal equation on an image.
class FastMarchingImageFilter
Solve an Eikonal equation using Fast Marching.
class FastMarchingUpwindGradientImageFilter
Generates the upwind gradient field of fast marching arrival times.
class FastSymmetricForcesDemonsRegistrationFilter
Deformably register two images using a symmetric forces demons algorithm.
class FFTConvolutionImageFilter
Convolve a given image with an arbitrary image kernel using multiplication in the Fourier domain.
class FFTNormalizedCorrelationImageFilter
Calculate normalized cross correlation using FFTs.
class FFTPadImageFilter
Pad an image to make it suitable for an FFT transformation.
class FFTShiftImageFilter
Shift the zero-frequency components of a Fourier transform to the center of the image.
class FlipImageFilter
Flips an image across user specified axes.
class ForwardFFTImageFilter
Base class for forward Fast Fourier Transform .
class FunctionCommand
A Command class which allows setting an external function, or member function.
class GaborImageSource
Generate an n-dimensional image of a Gabor filter.
class GaussianImageSource
Generate an n-dimensional image of a Gaussian.
class GenericException
The base SimpleITK exception class.
class GeodesicActiveContourLevelSetImageFilter
Segments structures in images based on a user supplied edge potential map.
class GradientAnisotropicDiffusionImageFilter
class GradientImageFilter
Computes the gradient of an image using directional derivatives.
class GradientMagnitudeImageFilter
Computes the gradient magnitude of an image region at each pixel.
class GradientMagnitudeRecursiveGaussianImageFilter
Computes the Magnitude of the Gradient of an image by convolution with the first derivative of a Gaussian.
class GradientRecursiveGaussianImageFilter
Computes the gradient of an image by convolution with the first derivative of a Gaussian.
class GrayscaleConnectedClosingImageFilter
Enhance pixels associated with a dark object (identified by a seed pixel) where the dark object is surrounded by a brighter object.
class GrayscaleConnectedOpeningImageFilter
Enhance pixels associated with a bright object (identified by a seed pixel) where the bright object is surrounded by a darker object.
class GrayscaleDilateImageFilter
Grayscale dilation of an image.
class GrayscaleErodeImageFilter
Grayscale erosion of an image.
class GrayscaleFillholeImageFilter
Remove local minima not connected to the boundary of the image.
class GrayscaleGeodesicDilateImageFilter
geodesic gray scale dilation of an image
class GrayscaleGeodesicErodeImageFilter
geodesic gray scale erosion of an image
class GrayscaleGrindPeakImageFilter
Remove local maxima not connected to the boundary of the image.
class GrayscaleMorphologicalClosingImageFilter
gray scale dilation of an image
class GrayscaleMorphologicalOpeningImageFilter
gray scale dilation of an image
class GreaterEqualImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class GreaterImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class GridImageSource
Generate an n-dimensional image of a grid.
class HalfHermitianToRealInverseFFTImageFilter
Base class for specialized complex-to-real inverse Fast Fourier Transform .
class HashImageFilter
Compute the sha1 or md5 hash of an image.
class HausdorffDistanceImageFilter
Computes the Hausdorff distance between the set of non-zero pixels of two images.
class HConcaveImageFilter
Identify local minima whose depth below the baseline is greater than h.
class HConvexImageFilter
Identify local maxima whose height above the baseline is greater than h.
class HistogramMatchingImageFilter
Normalize the grayscale values for a source image by matching the shape of the source image histogram to a reference histogram.
class HMaximaImageFilter
Suppress local maxima whose height above the baseline is less than h.
class HMinimaImageFilter
Suppress local minima whose depth below the baseline is less than h.
class HuangThresholdImageFilter
Threshold an image using the Huang Threshold.
class Image
The Image class for SimpleITK.
class ImageFileReader
Read an image file and return a SimpleITK Image.
class ImageFileWriter
Write out a SimpleITK image to the specified file location.
class ImageFilter
The base interface for SimpleITK filters that take one input image.
class ImageReaderBase
An abstract base class for image readers.
class ImageRegistrationMethod
An interface method to the modular ITKv4 registration framework.
class ImageSeriesReader
Read series of image files into a SimpleITK image.
class ImageSeriesWriter
Writer series of image from a SimpleITK image.
struct ImageTypeToPixelID
struct ImageTypeToPixelID< itk::Image< TPixelType, VImageDimension > >
struct ImageTypeToPixelID< itk::LabelMap< itk::LabelObject< TLabelType, VImageDimension > > >
struct ImageTypeToPixelID< itk::VectorImage< TPixelType, VImageDimension > >
struct ImageTypeToPixelIDValue
struct ImageTypeToPixelIDValue< itk::ImageBase< VImageDimension > >
class ImageViewer
Display an image in an external viewer (Fiji by default)
class ImportImageFilter
Compose a 2D or 3D image and return a smart pointer to a SimpleITK image.
class IntensityWindowingImageFilter
Applies a linear transformation to the intensity levels of the input Image that are inside a user-defined interval. Values below this interval are mapped to a constant. Values over the interval are mapped to another constant.
class IntermodesThresholdImageFilter
Threshold an image using the Intermodes Threshold.
class InverseDeconvolutionImageFilter
The direct linear inverse deconvolution filter.
class InverseDisplacementFieldImageFilter
Computes the inverse of a displacement field.
class InverseFFTImageFilter
Base class for inverse Fast Fourier Transform .
class InvertDisplacementFieldImageFilter
Iteratively estimate the inverse field of a displacement field.
class InvertIntensityImageFilter
Invert the intensity of an image.
struct IsBasic
struct IsBasic< BasicPixelID< TPixelType > >
struct IsBasic< itk::Image< TPixelType, VImageDimension > >
struct IsInstantiated
struct IsInstantiated< itk::Image< TPixelType, VImageDimension >, 0 >
struct IsInstantiated< itk::LabelMap< itk::LabelObject< TLabelType, VImageDimension > >, 0 >
struct IsInstantiated< itk::VectorImage< TPixelType, VImageDimension >, 0 >
struct IsLabel
struct IsLabel< itk::LabelMap< itk::LabelObject< TLabelType, VImageDimension > > >
struct IsLabel< LabelPixelID< TPixelType > >
class IsoContourDistanceImageFilter
Compute an approximate distance from an interpolated isocontour to the close grid points.
class IsoDataThresholdImageFilter
Threshold an image using the IsoData Threshold.
class IsolatedConnectedImageFilter
Label pixels that are connected to one set of seeds but not another.
class IsolatedWatershedImageFilter
Isolate watershed basins using two seeds.
struct IsVector
struct IsVector< itk::VectorImage< TPixelType, VImageDimension > >
struct IsVector< VectorPixelID< TPixelType > >
class IterativeInverseDisplacementFieldImageFilter
Computes the inverse of a displacement field.
class JoinSeriesImageFilter
Join N-D images into an (N+1)-D image.
class KittlerIllingworthThresholdImageFilter
Threshold an image using the KittlerIllingworth Threshold.
class LabelContourImageFilter
Labels the pixels on the border of the objects in a labeled image.
class LabelImageToLabelMapFilter
convert a labeled image to a label collection image
class LabelIntensityStatisticsImageFilter
a convenient class to convert a label image to a label map and valuate the statistics attributes at once
class LabelMapContourOverlayImageFilter
Apply a colormap to the contours (outlines) of each object in a label map and superimpose it on top of the feature image.
class LabelMapMaskImageFilter
Mask and image with a LabelMap .
class LabelMapOverlayImageFilter
Apply a colormap to a label map and superimpose it on an image.
class LabelMapToBinaryImageFilter
Convert a LabelMap to a binary image.
class LabelMapToLabelImageFilter
Converts a LabelMap to a labeled image.
class LabelMapToRGBImageFilter
Convert a LabelMap to a colored image.
class LabelOverlapMeasuresImageFilter
Computes overlap measures between the set same set of labels of pixels of two images. Background is assumed to be 0.
class LabelOverlayImageFilter
Apply a colormap to a label image and put it on top of the input image.
struct LabelPixelID
class LabelShapeStatisticsImageFilter
Converts a label image to a label map and valuates the shape attributes.
class LabelStatisticsImageFilter
Given an intensity image and a label map, compute min, max, variance and mean of the pixels associated with each label or segment.
class LabelToRGBImageFilter
Apply a colormap to a label image.
class LabelUniqueLabelMapFilter
Make sure that the objects are not overlapping.
class LabelVotingImageFilter
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
class LandmarkBasedTransformInitializerFilter
class LandweberDeconvolutionImageFilter
Deconvolve an image using the Landweber deconvolution algorithm.
class LaplacianImageFilter
class LaplacianRecursiveGaussianImageFilter
Computes the Laplacian of Gaussian (LoG) of an image.
class LaplacianSegmentationLevelSetImageFilter
Segments structures in images based on a second derivative image features.
class LaplacianSharpeningImageFilter
This filter sharpens an image using a Laplacian. LaplacianSharpening highlights regions of rapid intensity change and therefore highlights or enhances the edges. The result is an image that appears more in focus.
class LessEqualImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class LessImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class LevelSetMotionRegistrationFilter
Deformably register two images using level set motion.
class LiThresholdImageFilter
Threshold an image using the Li Threshold.
class Log10ImageFilter
Computes the log10 of each pixel.
class LoggerBase
A base class to handle SimpleITK and ITK messages and logging.
class LogImageFilter
Computes the log() of each pixel.
class MagnitudeAndPhaseToComplexImageFilter
Implements pixel-wise conversion of magnitude and phase data into complex voxels.
class MaskedFFTNormalizedCorrelationImageFilter
Calculate masked normalized cross correlation using FFTs.
class MaskImageFilter
Mask an image with a mask.
class MaskNegatedImageFilter
Mask an image with the negation (or logical compliment) of a mask.
class MaximumEntropyThresholdImageFilter
Threshold an image using the MaximumEntropy Threshold.
class MaximumImageFilter
Implements a pixel-wise operator Max(a,b) between two images.
class MaximumProjectionImageFilter
Maximum projection.
class MeanImageFilter
Applies an averaging filter to an image.
class MeanProjectionImageFilter
Mean projection.
class MedianImageFilter
Applies a median filter to an image.
class MedianProjectionImageFilter
Median projection.
class MergeLabelMapFilter
Merges several Label Maps.
class MinimumImageFilter
Implements a pixel-wise operator Min(a,b) between two images.
class MinimumMaximumImageFilter
Computes the minimum and the maximum intensity values of an image.
class MinimumProjectionImageFilter
Minimum projection.
class MinMaxCurvatureFlowImageFilter
Denoise an image using min/max curvature flow.
class MirrorPadImageFilter
Increase the image size by padding with replicants of the input image value.
class ModulusImageFilter
Computes the modulus (x % dividend) pixel-wise.
class MomentsThresholdImageFilter
Threshold an image using the Moments Threshold.
class MorphologicalGradientImageFilter
gray scale dilation of an image
class MorphologicalWatershedFromMarkersImageFilter
Morphological watershed transform from markers.
class MorphologicalWatershedImageFilter
Watershed segmentation implementation with morphological operators.
class MultiLabelSTAPLEImageFilter
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
class MultiplyImageFilter
Pixel-wise multiplication of two images.
class N4BiasFieldCorrectionImageFilter
Implementation of the N4 bias field correction algorithm.
class NaryAddImageFilter
Pixel-wise addition of N images.
class NaryMaximumImageFilter
Computes the pixel-wise maximum of several images.
class NeighborhoodConnectedImageFilter
Label pixels that are connected to a seed and lie within a neighborhood.
class NoiseImageFilter
Calculate the local noise in an image.
class NonCopyable
An inheritable class to disable copying of a class.
class NormalizedCorrelationImageFilter
Computes the normalized correlation of an image and a template.
class NormalizeImageFilter
Normalize an image by setting its mean to zero and variance to one.
class NormalizeToConstantImageFilter
Scales image pixel intensities to make the sum of all pixels equal a user-defined constant.
class NotEqualImageFilter
Implements pixel-wise generic operation of two images, or of an image and a constant.
class NotImageFilter
Implements the NOT logical operator pixel-wise on an image.
class ObjectnessMeasureImageFilter
Enhance M-dimensional objects in N-dimensional images.
class ObjectOwnedBase
An abstract base class to connect this object with the lifetime of another.
class OpeningByReconstructionImageFilter
Opening by reconstruction of an image.
class OrImageFilter
Implements the OR bitwise operator pixel-wise between two images.
class OtsuMultipleThresholdsImageFilter
Threshold an image using multiple Otsu Thresholds.
class OtsuThresholdImageFilter
Threshold an image using the Otsu Threshold.
class PasteImageFilter
Paste an image (or a constant value) into another image.
class PatchBasedDenoisingImageFilter
Derived class implementing a specific patch-based denoising algorithm, as detailed below.
class PermuteAxesImageFilter
Permutes the image axes according to a user specified order.
class PhysicalPointImageSource
Generate an image of the physical locations of each pixel.
class PimpleImageBase
Private implementation idiom image base class.
struct PixelIDToImageType
struct PixelIDToImageType< BasicPixelID< TPixelType >, VImageDimension >
struct PixelIDToImageType< LabelPixelID< TLabelType >, VImageDimension >
struct PixelIDToImageType< VectorPixelID< TVectorPixelType >, VImageDimension >
struct PixelIDToPixelIDValue
class PowImageFilter
Computes the powers of 2 images.
class ProcessObject
Base class for SimpleITK classes based on ProcessObject.
class ProjectedLandweberDeconvolutionImageFilter
Deconvolve an image using the projected Landweber deconvolution algorithm.
class RankImageFilter
Rank filter of a greyscale image.
class RealAndImaginaryToComplexImageFilter
ComposeImageFilter combine several scalar images into a multicomponent image.
class RealToHalfHermitianForwardFFTImageFilter
Base class for specialized real-to-complex forward Fast Fourier Transform .
class ReconstructionByDilationImageFilter
grayscale reconstruction by dilation of an image
class ReconstructionByErosionImageFilter
grayscale reconstruction by erosion of an image
class RecursiveGaussianImageFilter
Base class for computing IIR convolution with an approximation of a Gaussian kernel.
class RegionalMaximaImageFilter
Produce a binary image where foreground is the regional maxima of the input image.
class RegionalMinimaImageFilter
Produce a binary image where foreground is the regional minima of the input image.
class RegionOfInterestImageFilter
Extract a region of interest from the input image.
class RelabelComponentImageFilter
Relabel the components in an image such that consecutive labels are used.
class RelabelLabelMapFilter
This filter relabels the LabelObjects; the new labels are arranged consecutively with consideration for the background value.
class RenyiEntropyThresholdImageFilter
Threshold an image using the RenyiEntropy Threshold.
class ResampleImageFilter
Resample an image via a coordinate transform.
class RescaleIntensityImageFilter
Applies a linear transformation to the intensity levels of the input Image .
class RichardsonLucyDeconvolutionImageFilter
Deconvolve an image using the Richardson-Lucy deconvolution algorithm.
class RoundImageFilter
Rounds the value of each pixel.
class SaltAndPepperNoiseImageFilter
Alter an image with fixed value impulse noise, often called salt and pepper noise.
class ScalarChanAndVeseDenseLevelSetImageFilter
Dense implementation of the Chan and Vese multiphase level set image filter.
class ScalarConnectedComponentImageFilter
A connected components filter that labels the objects in an arbitrary image. Two pixels are similar if they are within threshold of each other. Uses ConnectedComponentFunctorImageFilter .
class ScalarImageKmeansImageFilter
Classifies the intensity values of a scalar image using the K-Means algorithm.
class ScalarToRGBColormapImageFilter
Implements pixel-wise intensity->rgb mapping operation on one image.
class ScaleSkewVersor3DTransform
A over parameterized 3D Affine transform composed of the addition of a versor rotation matrix, a scale matrix and a skew matrix around a fixed center with translation.
class ScaleTransform
A 2D or 3D anisotropic scale of coordinate space around a fixed center.
class ScaleVersor3DTransform
A parameterized 3D transform composed of the addition of a versor rotation matrix and a scale matrix around a fixed center with translation.
struct scope_exit
class ShanbhagThresholdImageFilter
Threshold an image using the Shanbhag Threshold.
class ShapeDetectionLevelSetImageFilter
Segments structures in images based on a user supplied edge potential map.
class ShiftScaleImageFilter
Shift and scale the pixels in an image.
class ShotNoiseImageFilter
Alter an image with shot noise.
class ShrinkImageFilter
Reduce the size of an image by an integer factor in each dimension.
class SigmoidImageFilter
Computes the sigmoid function pixel-wise.
class SignedDanielssonDistanceMapImageFilter
class SignedMaurerDistanceMapImageFilter
This filter calculates the Euclidean distance transform of a binary image in linear time for arbitrary dimensions.
class Similarity2DTransform
A similarity 2D transform with rotation in radians and isotropic scaling around a fixed center with translation.
class Similarity3DTransform
A similarity 3D transform with rotation as a versor, and isotropic scaling around a fixed center with translation.
class SimilarityIndexImageFilter
Measures the similarity between the set of non-zero pixels of two images.
class SimpleContourExtractorImageFilter
Computes an image of contours which will be the contour of the first image.
class SinImageFilter
Computes the sine of each pixel.
class SITK_FINAL
class SliceImageFilter
Slices an image based on a starting index and a stopping index, and a step size.
class SLICImageFilter
Simple Linear Iterative Clustering (SLIC) super-pixel segmentation.
class SmoothingRecursiveGaussianImageFilter
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
class SobelEdgeDetectionImageFilter
A 2D or 3D edge detection using the Sobel operator.
class SpeckleNoiseImageFilter
Alter an image with speckle (multiplicative) noise.
class SqrtImageFilter
Computes the square root of each pixel.
class SquaredDifferenceImageFilter
Implements pixel-wise the computation of squared difference.
class SquareImageFilter
Computes the square of the intensity values pixel-wise.
class StandardDeviationProjectionImageFilter
Mean projection.
class STAPLEImageFilter
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
class StatisticsImageFilter
Compute min, max, variance and mean of an Image .
class StochasticFractalDimensionImageFilter
This filter computes the stochastic fractal dimension of the input image.
class SubtractImageFilter
Pixel-wise subtraction of two images.
class SumProjectionImageFilter
Sum projection.
class SymmetricForcesDemonsRegistrationFilter
Deformably register two images using the demons algorithm.
class TanImageFilter
Computes the tangent of each input pixel.
class TernaryAddImageFilter
Pixel-wise addition of three images.
class TernaryMagnitudeImageFilter
Compute the pixel-wise magnitude of three images.
class TernaryMagnitudeSquaredImageFilter
Compute the pixel-wise squared magnitude of three images.
class ThresholdImageFilter
Set image values to a user-specified value if they are below, above, or between simple threshold values.
class ThresholdMaximumConnectedComponentsImageFilter
Finds the threshold value of an image based on maximizing the number of objects in the image that are larger than a given minimal size.
class ThresholdSegmentationLevelSetImageFilter
Segments structures in images based on intensity values.
class TikhonovDeconvolutionImageFilter
An inverse deconvolution filter regularized in the Tikhonov sense.
class TileImageFilter
Tile multiple input images into a single output image.
class TobogganImageFilter
toboggan image segmentation The Toboggan segmentation takes a gradient magnitude image as input and produces an (over-)segmentation of the image based on connecting each pixel to a local minimum of gradient. It is roughly equivalent to a watershed segmentation of the lowest level.
class Transform
A simplified wrapper around a variety of ITK transforms.
class TransformGeometryImageFilter
class TransformToDisplacementFieldFilter
Generate a displacement field from a coordinate transform.
class TranslationTransform
Translation of a 2D or 3D coordinate space.
class TriangleThresholdImageFilter
Threshold an image using the Triangle Threshold.
class UnaryMinusImageFilter
Implements pixel-wise generic operation on one image.
class UnsharpMaskImageFilter
Edge enhancement filter.
class ValuedRegionalMaximaImageFilter
Transforms the image so that any pixel that is not a regional maxima is set to the minimum value for the pixel type. Pixels that are regional maxima retain their value.
class ValuedRegionalMinimaImageFilter
Transforms the image so that any pixel that is not a regional minima is set to the maximum value for the pixel type. Pixels that are regional minima retain their value.
class VectorConfidenceConnectedImageFilter
Segment pixels with similar statistics using connectivity.
class VectorConnectedComponentImageFilter
A connected components filter that labels the objects in a vector image. Two vectors are pointing similar directions if one minus their dot product is less than a threshold. Vectors that are 180 degrees out of phase are similar. Assumes that vectors are normalized.
class VectorIndexSelectionCastImageFilter
Extracts the selected index of the vector that is the input pixel type.
class VectorMagnitudeImageFilter
Take an image of vectors as input and produce an image with the magnitude of those vectors.
struct VectorPixelID
class Version
Version info for SimpleITK.
class VersorRigid3DTransform
A rotation as a versor around a fixed center with translation of a 3D coordinate space.
class VersorTransform
A 3D rotation transform with rotation as a versor around a fixed center.
class VotingBinaryHoleFillingImageFilter
Fills in holes and cavities by applying a voting operation on each pixel.
class VotingBinaryImageFilter
Applies a voting operation in a neighborhood of each pixel.
class VotingBinaryIterativeHoleFillingImageFilter
Fills in holes and cavities by iteratively applying a voting operation.
class WarpImageFilter
Warps an image using an input displacement field.
class WhiteTopHatImageFilter
White top hat extracts local maxima that are larger than the structuring element.
class WienerDeconvolutionImageFilter
The Wiener deconvolution image filter is designed to restore an image convolved with a blurring kernel while keeping noise enhancement to a minimum.
class WrapPadImageFilter
Increase the image size by padding with replicants of the input image value.
class XorImageFilter
Computes the XOR bitwise operator pixel-wise between two images.
class YenThresholdImageFilter
Threshold an image using the Yen Threshold.
class ZeroCrossingBasedEdgeDetectionImageFilter
This filter implements a zero-crossing based edge detecor.
class ZeroCrossingImageFilter
This filter finds the closest pixel to the zero-crossings (sign changes) in a signed itk::Image .
class ZeroFluxNeumannPadImageFilter
Increase the image size by padding according to the zero-flux Neumann boundary condition.
Typedefs
typedef typelist::Append< typelist::Append< BasicPixelIDTypeList, ComplexPixelIDTypeList >::Type, typelist::Append< VectorPixelIDTypeList, LabelPixelIDTypeList >::Type >::Type AllPixelIDTypeList
typedef typelist::MakeTypeList< BasicPixelID< int8_t >, BasicPixelID< uint8_t >, BasicPixelID< int16_t >, BasicPixelID< uint16_t >, BasicPixelID< int32_t >, BasicPixelID< uint32_t >, BasicPixelID< float >, BasicPixelID< double > >::Type BasicPixelIDTypeList
typedef typelist::MakeTypeList< BasicPixelID< std::complex< float > >, BasicPixelID< std::complex< double > > >::Type ComplexPixelIDTypeList
using FalseType = std::false_type
using InstantiatedPixelIDTypeList = AllPixelIDTypeList
using IntegerLabelPixelIDTypeList = UnsignedIntegerPixelIDTypeList
typedef typelist::MakeTypeList< BasicPixelID< int8_t >, BasicPixelID< uint8_t >, BasicPixelID< int16_t >, BasicPixelID< uint16_t >, BasicPixelID< int32_t >, BasicPixelID< uint32_t > >::Type IntegerPixelIDTypeList
typedef typelist::MakeTypeList< LabelPixelID< uint8_t >, LabelPixelID< uint16_t >, LabelPixelID< uint32_t > >::Type LabelPixelIDTypeList
using MaskedPixelIDTypeList = typelist::MakeTypeList< BasicPixelID< uint8_t > >::Type
typedef typelist::Append< typelist::Append< BasicPixelIDTypeList, ComplexPixelIDTypeList >::Type, VectorPixelIDTypeList >::Type NonLabelPixelIDTypeList
using PixelIDValueType = int
typedef typelist::MakeTypeList< BasicPixelID< float >, BasicPixelID< double > >::Type RealPixelIDTypeList
typedef typelist::MakeTypeList< VectorPixelID< float >, VectorPixelID< double > >::Type RealVectorPixelIDTypeList
using ScalarPixelIDTypeList = BasicPixelIDTypeList
typedef typelist::MakeTypeList< BasicPixelID< int8_t >, BasicPixelID< int16_t >, BasicPixelID< int32_t >, BasicPixelID< float >, BasicPixelID< double > >::Type SignedPixelIDTypeList
typedef typelist::MakeTypeList< VectorPixelID< int8_t >, VectorPixelID< int16_t >, VectorPixelID< int32_t >, VectorPixelID< float >, VectorPixelID< double > >::Type SignedVectorPixelIDTypeList
using TrueType = std::true_type
typedef typelist::MakeTypeList< BasicPixelID< uint8_t >, BasicPixelID< uint16_t >, BasicPixelID< uint32_t > >::Type UnsignedIntegerPixelIDTypeList
typedef typelist::MakeTypeList< VectorPixelID< int8_t >, VectorPixelID< uint8_t >, VectorPixelID< int16_t >, VectorPixelID< uint16_t >, VectorPixelID< int32_t >, VectorPixelID< uint32_t >, VectorPixelID< float >, VectorPixelID< double > >::Type VectorPixelIDTypeList
Enumerations
enum EventEnum {
sitkAnyEvent = 0 ,
sitkAbortEvent = 1 ,
sitkDeleteEvent = 2 ,
sitkEndEvent = 3 ,
sitkIterationEvent = 4 ,
sitkProgressEvent = 5 ,
sitkStartEvent = 6 ,
sitkMultiResolutionIterationEvent = 9 ,
sitkUserEvent = 7
}
Events which can be observed from ProcessObject.
enum InterpolatorEnum {
sitkNearestNeighbor = 1 ,
sitkLinear = 2 ,
sitkBSpline1 = 21 ,
sitkBSpline2 = 22 ,
sitkBSpline = 23 ,
sitkBSpline3 = 23 ,
sitkBSpline4 = 24 ,
sitkBSpline5 = 25 ,
sitkGaussian = 4 ,
sitkLabelGaussian = 5 ,
sitkHammingWindowedSinc = 6 ,
sitkCosineWindowedSinc = 7 ,
sitkWelchWindowedSinc = 8 ,
sitkLanczosWindowedSinc = 9 ,
sitkBlackmanWindowedSinc = 10 ,
sitkBSplineResampler = 11 ,
sitkBSplineResamplerOrder3 = 11 ,
sitkBSplineResamplerOrder1 = 12 ,
sitkBSplineResamplerOrder2 = 13 ,
sitkBSplineResamplerOrder4 = 14 ,
sitkBSplineResamplerOrder5 = 15
}
enum KernelEnum {
sitkAnnulus ,
sitkBall ,
sitkBox ,
sitkCross ,
sitkPolygon3 ,
sitkPolygon4 ,
sitkPolygon5 ,
sitkPolygon6 ,
sitkPolygon7 ,
sitkPolygon8 ,
sitkPolygon9
}
enum PixelIDValueEnum {
sitkUnknown = -1 ,
sitkUInt8 = PixelIDToPixelIDValue< BasicPixelID<uint8_t> >::Result ,
sitkInt8 = PixelIDToPixelIDValue< BasicPixelID<int8_t> >::Result ,
sitkUInt16 = PixelIDToPixelIDValue< BasicPixelID<uint16_t> >::Result ,
sitkInt16 = PixelIDToPixelIDValue< BasicPixelID<int16_t> >::Result ,
sitkUInt32 = PixelIDToPixelIDValue< BasicPixelID<uint32_t> >::Result ,
sitkInt32 = PixelIDToPixelIDValue< BasicPixelID<int32_t> >::Result ,
sitkUInt64 = PixelIDToPixelIDValue< BasicPixelID<uint64_t> >::Result ,
sitkInt64 = PixelIDToPixelIDValue< BasicPixelID<int64_t> >::Result ,
sitkFloat32 = PixelIDToPixelIDValue< BasicPixelID<float> >::Result ,
sitkFloat64 = PixelIDToPixelIDValue< BasicPixelID<double> >::Result ,
sitkComplexFloat32 = PixelIDToPixelIDValue< BasicPixelID<std::complex<float> > >::Result ,
sitkComplexFloat64 = PixelIDToPixelIDValue< BasicPixelID<std::complex<double> > >::Result ,
sitkVectorUInt8 = PixelIDToPixelIDValue< VectorPixelID<uint8_t> >::Result ,
sitkVectorInt8 = PixelIDToPixelIDValue< VectorPixelID<int8_t> >::Result ,
sitkVectorUInt16 = PixelIDToPixelIDValue< VectorPixelID<uint16_t> >::Result ,
sitkVectorInt16 = PixelIDToPixelIDValue< VectorPixelID<int16_t> >::Result ,
sitkVectorUInt32 = PixelIDToPixelIDValue< VectorPixelID<uint32_t> >::Result ,
sitkVectorInt32 = PixelIDToPixelIDValue< VectorPixelID<int32_t> >::Result ,
sitkVectorUInt64 = PixelIDToPixelIDValue< VectorPixelID<uint64_t> >::Result ,
sitkVectorInt64 = PixelIDToPixelIDValue< VectorPixelID<int64_t> >::Result ,
sitkVectorFloat32 = PixelIDToPixelIDValue< VectorPixelID<float> >::Result ,
sitkVectorFloat64 = PixelIDToPixelIDValue< VectorPixelID<double> >::Result ,
sitkLabelUInt8 = PixelIDToPixelIDValue< LabelPixelID<uint8_t> >::Result ,
sitkLabelUInt16 = PixelIDToPixelIDValue< LabelPixelID<uint16_t> >::Result ,
sitkLabelUInt32 = PixelIDToPixelIDValue< LabelPixelID<uint32_t> >::Result ,
sitkLabelUInt64 = PixelIDToPixelIDValue< LabelPixelID<uint64_t> >::Result
}
Enumerated values of pixelIDs.
enum SeedEnum { sitkWallClock = 0 }
enum TransformEnum {
sitkUnknownTransform = -1 ,
sitkIdentity ,
sitkTranslation ,
sitkScale ,
sitkScaleLogarithmic ,
sitkEuler ,
sitkSimilarity ,
sitkQuaternionRigid ,
sitkVersor ,
sitkVersorRigid ,
sitkScaleSkewVersor ,
sitkComposeScaleSkewVersor ,
sitkScaleVersor ,
sitkAffine ,
sitkComposite ,
sitkDisplacementField ,
sitkBSplineTransform
}
Functions
Image AbsoluteValueDifference (const Image &image1, double constant)
Image AbsoluteValueDifference (double constant, const Image &image2)
Image AbsoluteValueDifference (Image &&image1, double constant)
Image Add (const Image &image1, double constant)
Image Add (double constant, const Image &image2)
Image Add (Image &&image1, double constant)
Image And (const Image &image1, int constant)
Image And (Image &&image1, int constant)
Image And (int constant, const Image &image2)
Image Atan2 (const Image &image1, double constant)
Image Atan2 (double constant, const Image &image2)
Image Atan2 (Image &&image1, double constant)
BSplineTransform BSplineTransformInitializer (const Image &image1, const std::vector< uint32_t > &transformDomainMeshSize=std::vector< uint32_t >(3, 1u), unsigned int order=3u)
BSplineTransformInitializerFilter is a helper class intended to initialize the control point grid such that it has a physically consistent definition. It sets the transform domain origin, physical dimensions and direction from information obtained from the image. It also sets the mesh size if asked to do so by calling SetTransformDomainMeshSize()before calling InitializeTransform().
Image Cast (const Image &image, PixelIDValueEnum pixelID)
Transform CenteredTransformInitializer (const Image &fixedImage, const Image &movingImage, const Transform &transform, CenteredTransformInitializerFilter::OperationModeType operationMode=itk::simple::CenteredTransformInitializerFilter::MOMENTS)
CenteredTransformInitializer is a helper class intended to initialize the center of rotation and the translation of Transforms having the center of rotation among their parameters.
Transform CenteredVersorTransformInitializer (const Image &fixedImage, const Image &movingImage, const Transform &transform, bool computeRotation=false)
CenteredVersorTransformInitializer is a helper class intended to initialize the center of rotation, versor, and translation of the VersorRigid3DTransform.
template<unsigned int VImageDimension>
itk::FlatStructuringElement< VImageDimension > CreateKernel (KernelEnum kernelType, const std::vector< uint32_t > &size)
Image DiscreteGaussian (const Image &image1, double variance, unsigned int maximumKernelWidth=32u, double maximumError=0.01, bool useImageSpacing=true)
Blurs an image by separable convolution with discrete gaussian kernels. This filter performs Gaussian blurring by separable convolution of an image and a discrete Gaussian operator (kernel).
Image Divide (const Image &image1, double constant)
Image Divide (double constant, const Image &image2)
Image Divide (Image &&image1, double constant)
Image DivideFloor (const Image &image1, double constant)
Image DivideFloor (double constant, const Image &image2)
Image DivideFloor (Image &&image1, double constant)
Image DivideReal (const Image &image1, double constant)
Image DivideReal (double constant, const Image &image2)
Image DivideReal (Image &&image1, double constant)
Image Equal (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Equal (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Equal (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image GaborSource (PixelIDValueEnum outputPixelType=itk::simple::sitkFloat32, std::vector< unsigned int > size=std::vector< unsigned int >(3, 64), std::vector< double > sigma=std::vector< double >(3, 16.0), std::vector< double > mean=std::vector< double >(3, 32.0), double frequency=0.4, std::vector< double > origin=std::vector< double >(3, 0.0), std::vector< double > spacing=std::vector< double >(3, 1.0), std::vector< double > direction=std::vector< double >())
Generate an n-dimensional image of a Gabor filter.
Image GaussianSource (PixelIDValueEnum outputPixelType=itk::simple::sitkFloat32, std::vector< unsigned int > size=std::vector< unsigned int >(3, 64), std::vector< double > sigma=std::vector< double >(3, 16.0), std::vector< double > mean=std::vector< double >(3, 32.0), double scale=255, std::vector< double > origin=std::vector< double >(3, 0.0), std::vector< double > spacing=std::vector< double >(3, 1.0), std::vector< double > direction=std::vector< double >(), bool normalized=false)
Generate an n-dimensional image of a Gaussian.
template<typename TPixelType , unsigned int ImageDimension>
SITKCommon_HIDDEN itk::Image< itk::Vector< TPixelType, ImageDimension >, ImageDimension >::Pointer GetImageFromVectorImage (itk::VectorImage< TPixelType, ImageDimension > *img, bool transferOwnership=false)
A utility method to help convert between itk image types efficiently.
const std::string SITKCommon_EXPORT GetPixelIDValueAsString (PixelIDValueEnum type)
const std::string SITKCommon_EXPORT GetPixelIDValueAsString (PixelIDValueType type)
PixelIDValueType SITKCommon_EXPORT GetPixelIDValueFromString (const std::string &enumString)
Function mapping enumeration names in std::string to values.
template<class TPixelType , unsigned int NImageDimension, unsigned int NLength>
SITKCommon_HIDDEN itk::VectorImage< TPixelType, NImageDimension >::Pointer GetVectorImageFromImage (itk::Image< itk::CovariantVector< TPixelType, NLength >, NImageDimension > *img, bool transferOwnership=false)
template<unsigned int NImageDimension, unsigned int NLength>
SITKCommon_HIDDEN itk::VectorImage< typenamestd::conditional< sizeof(typenameitk::Offset< NLength >::OffsetValueType)==sizeof(int64_t), int64_t, FalseType >::type, NImageDimension >::Pointer GetVectorImageFromImage (itk::Image< itk::Offset< NLength >, NImageDimension > *img, bool transferOwnership=false)
template<class TPixelType , unsigned int NImageDimension, unsigned int NLength>
SITKCommon_HIDDEN itk::VectorImage< TPixelType, NImageDimension >::Pointer GetVectorImageFromImage (itk::Image< itk::Vector< TPixelType, NLength >, NImageDimension > *img, bool transferOwnership=false)
Image Greater (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Greater (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Greater (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image GreaterEqual (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image GreaterEqual (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image GreaterEqual (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image GridSource (PixelIDValueEnum outputPixelType=itk::simple::sitkFloat32, std::vector< unsigned int > size=std::vector< unsigned int >(3, 64), std::vector< double > sigma=std::vector< double >(3, 0.5), std::vector< double > gridSpacing=std::vector< double >(3, 4.0), std::vector< double > gridOffset=std::vector< double >(3, 0.0), double scale=255.0, std::vector< double > origin=std::vector< double >(3, 0.0), std::vector< double > spacing=std::vector< double >(3, 1.0), std::vector< double > direction=std::vector< double >())
Generate an n-dimensional image of a grid.
std::string Hash (const Image &image, HashImageFilter::HashFunction function=HashImageFilter::SHA1)
Image SITKIO_EXPORT ImportAsDouble (double *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsFloat (float *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsInt16 (int16_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsInt32 (int32_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsInt64 (int64_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsInt8 (int8_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsUInt16 (uint16_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsUInt32 (uint32_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsUInt64 (uint64_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Image SITKIO_EXPORT ImportAsUInt8 (uint8_t *buffer, const std::vector< unsigned int > &size, const std::vector< double > &spacing=std::vector< double >(3, 1.0), const std::vector< double > &origin=std::vector< double >(3, 0.0), const std::vector< double > &direction=std::vector< double >(), unsigned int numberOfComponents=1)
Transform LandmarkBasedTransformInitializer (const Transform &transform, const std::vector< double > &fixedLandmarks=std::vector< double >(), const std::vector< double > &movingLandmarks=std::vector< double >(), const std::vector< double > &landmarkWeight=std::vector< double >(), const Image &referenceImage=Image(), unsigned int numberOfControlPoints=4u)
itk::simple::LandmarkBasedTransformInitializerFilter Procedural Interface
Image Less (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Less (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image Less (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image LessEqual (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image LessEqual (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image LessEqual (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image MagnitudeAndPhaseToComplex (const Image &image1, double constant)
Image MagnitudeAndPhaseToComplex (double constant, const Image &image2)
Image MagnitudeAndPhaseToComplex (Image &&image1, double constant)
template<typename F >
scope_exit< F > make_scope_exit (F &&f) noexcept
Image Maximum (const Image &image1, double constant)
Image Maximum (double constant, const Image &image2)
Image Maximum (Image &&image1, double constant)
Image Minimum (const Image &image1, double constant)
Image Minimum (double constant, const Image &image2)
Image Minimum (Image &&image1, double constant)
Image Modulus (const Image &image1, uint32_t constant)
Image Modulus (Image &&image1, uint32_t constant)
Image Modulus (uint32_t constant, const Image &image2)
Image Multiply (const Image &image1, double constant)
Image Multiply (double constant, const Image &image2)
Image Multiply (Image &&image1, double constant)
Image NotEqual (const Image &image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image NotEqual (double constant, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Image NotEqual (Image &&image1, double constant, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
SITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const EventEnum k)
SITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const InterpolatorEnum i)
SITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const KernelEnum k)
SITKCommon_EXPORT std::ostream & operator<< (std::ostream &os, const PixelIDValueEnum id)
template<typename T >
SITKCommon_HIDDEN std::ostream & operator<< (std::ostream &os, const std::vector< T > &v)
Output the element of an std::vector to the output stream.
Image Or (const Image &image1, int constant)
Image Or (Image &&image1, int constant)
Image Or (int constant, const Image &image2)
Image PatchBasedDenoising (const Image &image1, double kernelBandwidthSigma=400.0, uint32_t patchRadius=4u, uint32_t numberOfIterations=1u, uint32_t numberOfSamplePatches=200u, double sampleVariance=400.0)
Image PatchBasedDenoising (const Image &image1, itk::simple::PatchBasedDenoisingImageFilter::NoiseModelType noiseModel, double kernelBandwidthSigma=400.0, uint32_t patchRadius=4u, uint32_t numberOfIterations=1u, uint32_t numberOfSamplePatches=200u, double sampleVariance=400.0, double noiseSigma=0.0, double noiseModelFidelityWeight=0.0)
itk::simple::PatchBasedDenoisingImageFilter Procedural Interface
Image PhysicalPointSource (PixelIDValueEnum outputPixelType=itk::simple::sitkVectorFloat32, std::vector< unsigned int > size=std::vector< unsigned int >(3, 64), std::vector< double > origin=std::vector< double >(3, 0.0), std::vector< double > spacing=std::vector< double >(3, 1.0), std::vector< double > direction=std::vector< double >())
Generate an image of the physical locations of each pixel.
Image Pow (const Image &image1, double constant)
Image Pow (double constant, const Image &image2)
Image Pow (Image &&image1, double constant)
SITKIO_EXPORT Image ReadImage (const std::string &filename, PixelIDValueEnum outputPixelType=sitkUnknown, const std::string &imageIO="")
ReadImage is a procedural interface to the ImageFileReader class which is convenient for most image reading tasks.
SITKIO_EXPORT Image ReadImage (const std::vector< std::string > &fileNames, PixelIDValueEnum outputPixelType=sitkUnknown, const std::string &imageIO="")
ReadImage is a procedural interface to the ImageSeriesReader class which is convenient for most image reading tasks.
SITKCommon_EXPORT Transform ReadTransform (const std::string &filename)
void SITKIO_EXPORT Show (const Image &image, const std::string &title="", const bool debugOn=ProcessObject::GetGlobalDefaultDebug())
template<typename TDirectionType >
std::vector< double > SITKCommon_HIDDEN sitkITKDirectionToSTL (const TDirectionType &d)
template<unsigned int VImageDimension>
std::vector< unsigned int > SITKCommon_HIDDEN sitkITKImageRegionToSTL (const ImageRegion< VImageDimension > &in)
Convert an ITK ImageRegion to and std::vector with the first part being the start index followed by the size.
template<typename TType , typename TITKVector >
std::vector< TType > SITKCommon_HIDDEN sitkITKVectorToSTL (const std::vector< TITKVector > &in)
template<typename TType , typename TITKVector >
std::vector< TType > SITKCommon_HIDDEN sitkITKVectorToSTL (const TITKVector &in)
Convert an ITK fixed width vector to a std::vector.
template<typename TType , typename T >
std::vector< TType > SITKCommon_HIDDEN sitkITKVersorToSTL (const itk::Versor< T > &in)
template<typename TDirectionType >
TDirectionType SITKCommon_HIDDEN sitkSTLToITKDirection (const std::vector< double > &direction)
template<typename TITKVector , typename TType >
TITKVector SITKCommon_HIDDEN sitkSTLVectorToITK (const std::vector< TType > &in)
Copy the elements of an std::vector into an ITK fixed width vector.
template<typename TITKPointVector , typename TType >
TITKPointVector SITKCommon_HIDDEN sitkSTLVectorToITKPointVector (const std::vector< TType > &in)
template<typename T , typename TType >
itk::Versor< T > SITKCommon_HIDDEN sitkSTLVectorToITKVersor (const std::vector< TType > &in)
template<typename TType , typename TVectorOfITKVector >
std::vector< TType > SITKCommon_HIDDEN sitkVectorOfITKVectorToSTL (const TVectorOfITKVector &in)
Convert an ITK style array of ITK fixed width vector to std::vector.
Image SmoothingRecursiveGaussian (const Image &image1, double sigma, bool normalizeAcrossScale=false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
Image SquaredDifference (const Image &image1, double constant)
Image SquaredDifference (double constant, const Image &image2)
Image SquaredDifference (Image &&image1, double constant)
Image Subtract (const Image &image1, double constant)
Image Subtract (double constant, const Image &image2)
Image Subtract (Image &&image1, double constant)
Image TransformToDisplacementField (const Transform &transform, PixelIDValueEnum outputPixelType=itk::simple::sitkVectorFloat64, std::vector< unsigned int > size=std::vector< unsigned int >(3, 64), std::vector< double > outputOrigin=std::vector< double >(3, 0.0), std::vector< double > outputSpacing=std::vector< double >(3, 1.0), std::vector< double > outputDirection=std::vector< double >())
Generate a displacement field from a coordinate transform.
template<typename T >
void SITKCommon_HIDDEN Unused (const T &)
A function which does nothing.
SITKIO_EXPORT void WriteImage (const Image &image, const std::string &fileName, bool useCompression=false, int compressionLevel=-1)
WriteImage is a procedural interface to the ImageFileWriter. class which is convenient for many image writing tasks.
SITKIO_EXPORT void WriteImage (const Image &image, const std::vector< std::string > &fileNames, bool useCompression=false, int compressionLevel=-1)
WriteImage is a procedural interface to the ImageSeriesWriter. class which is convenient for many image writing tasks.
SITKCommon_EXPORT void WriteTransform (const Transform &transform, const std::string &filename)
Image Xor (const Image &image1, int constant)
Image Xor (Image &&image1, int constant)
Image Xor (int constant, const Image &image2)
Image Abs (Image &&image1)
Computes the absolute value of each pixel.
Image Abs (const Image &image1)
Computes the absolute value of each pixel.
Image AbsoluteValueDifference (Image &&image1, const Image &image2)
Implements pixel-wise the computation of absolute value difference.
Image AbsoluteValueDifference (const Image &image1, const Image &image2)
Implements pixel-wise the computation of absolute value difference.
Image Acos (Image &&image1)
Computes the inverse cosine of each pixel.
Image Acos (const Image &image1)
Computes the inverse cosine of each pixel.
Image AdaptiveHistogramEqualization (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 5), float alpha=0.3f, float beta=0.3f)
Power Law Adaptive Histogram Equalization.
Image Add (Image &&image1, const Image &image2)
Pixel-wise addition of two images.
Image Add (const Image &image1, const Image &image2)
Pixel-wise addition of two images.
Image AdditiveGaussianNoise (Image &&image1, double standardDeviation=1.0, double mean=0.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with additive Gaussian white noise.
Image AdditiveGaussianNoise (const Image &image1, double standardDeviation=1.0, double mean=0.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with additive Gaussian white noise.
Image AggregateLabelMap (Image &&image1)
Collapses all labels into the first label.
Image AggregateLabelMap (const Image &image1)
Collapses all labels into the first label.
Image And (Image &&image1, const Image &image2)
Implements the AND bitwise operator pixel-wise between two images.
Image And (const Image &image1, const Image &image2)
Implements the AND bitwise operator pixel-wise between two images.
Image AntiAliasBinary (Image &&image1, double maximumRMSError=0.07, uint32_t numberOfIterations=1000u)
A method for estimation of a surface from a binary volume.
Image AntiAliasBinary (const Image &image1, double maximumRMSError=0.07, uint32_t numberOfIterations=1000u)
A method for estimation of a surface from a binary volume.
Image ApproximateSignedDistanceMap (const Image &image1, double insideValue=1u, double outsideValue=0u)
Create a map of the approximate signed distance from the boundaries of a binary image.
Image Asin (Image &&image1)
Computes the sine of each pixel.
Image Asin (const Image &image1)
Computes the sine of each pixel.
Image Atan2 (Image &&image1, const Image &image2)
Computes two argument inverse tangent.
Image Atan2 (const Image &image1, const Image &image2)
Computes two argument inverse tangent.
Image Atan (Image &&image1)
Computes the one-argument inverse tangent of each pixel.
Image Atan (const Image &image1)
Computes the one-argument inverse tangent of each pixel.
Image Bilateral (const Image &image1, double domainSigma=4.0, double rangeSigma=50.0, unsigned int numberOfRangeGaussianSamples=100u)
Blurs an image while preserving edges.
Image BinaryClosingByReconstruction (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double foregroundValue=1.0, bool fullyConnected=false)
binary closing by reconstruction of an image.
Image BinaryContour (Image &&image1, bool fullyConnected=false, double backgroundValue=0.0, double foregroundValue=1.0)
Labels the pixels on the border of the objects in a binary image.
Image BinaryContour (const Image &image1, bool fullyConnected=false, double backgroundValue=0.0, double foregroundValue=1.0)
Labels the pixels on the border of the objects in a binary image.
Image BinaryDilate (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double backgroundValue=0.0, double foregroundValue=1.0, bool boundaryToForeground=false)
Fast binary dilation of a single intensity value in the image.
Image BinaryErode (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double backgroundValue=0.0, double foregroundValue=1.0, bool boundaryToForeground=true)
Fast binary erosion of a single intensity value in the image.
Image BinaryFillhole (const Image &image1, bool fullyConnected=false, double foregroundValue=1.0)
Remove holes not connected to the boundary of the image.
Image BinaryGrindPeak (const Image &image1, bool fullyConnected=false, double foregroundValue=1.0, double backgroundValue=0)
Remove the objects not connected to the boundary of the image.
Image BinaryImageToLabelMap (const Image &image1, bool fullyConnected=false, double inputForegroundValue=1.0, double outputBackgroundValue=0.0)
Label the connected components in a binary image and produce a collection of label objects.
Image BinaryMagnitude (Image &&image1, const Image &image2)
Computes the square root of the sum of squares of corresponding input pixels.
Image BinaryMagnitude (const Image &image1, const Image &image2)
Computes the square root of the sum of squares of corresponding input pixels.
Image BinaryMedian (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), double foregroundValue=1.0, double backgroundValue=0.0)
Applies a version of the median filter optimized for binary images.
Image BinaryMinMaxCurvatureFlow (Image &&image1, double timeStep=0.05, uint32_t numberOfIterations=5u, int stencilRadius=2, double threshold=0.0)
Denoise a binary image using min/max curvature flow.
Image BinaryMinMaxCurvatureFlow (const Image &image1, double timeStep=0.05, uint32_t numberOfIterations=5u, int stencilRadius=2, double threshold=0.0)
Denoise a binary image using min/max curvature flow.
Image BinaryMorphologicalClosing (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double foregroundValue=1.0, bool safeBorder=true)
binary morphological closing of an image.
Image BinaryMorphologicalOpening (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double backgroundValue=0.0, double foregroundValue=1.0)
binary morphological opening of an image.
Image BinaryNot (Image &&image1, double foregroundValue=1.0, double backgroundValue=0.0)
Implements the BinaryNot logical operator pixel-wise between two images.
Image BinaryNot (const Image &image1, double foregroundValue=1.0, double backgroundValue=0.0)
Implements the BinaryNot logical operator pixel-wise between two images.
Image BinaryOpeningByReconstruction (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double foregroundValue=1.0, double backgroundValue=0.0, bool fullyConnected=false)
binary morphological closing of an image.
Image BinaryProjection (const Image &image1, unsigned int projectionDimension=0u, double foregroundValue=1.0, double backgroundValue=0.0)
Binary projection.
Image BinaryPruning (const Image &image1, uint32_t iteration=3u)
This filter removes "spurs" of less than a certain length in the input image.
Image BinaryReconstructionByDilation (const Image &markerImage, const Image &maskImage, double backgroundValue=0.0, double foregroundValue=1.0, bool fullyConnected=false)
binary reconstruction by dilation of an image
Image BinaryReconstructionByErosion (const Image &markerImage, const Image &maskImage, double backgroundValue=0.0, double foregroundValue=1.0, bool fullyConnected=false)
binary reconstruction by erosion of an image
Image BinaryThinning (const Image &image1)
This filter computes one-pixel-wide edges of the input image.
Image BinaryThreshold (Image &&image1, double lowerThreshold=0.0, double upperThreshold=255.0, uint8_t insideValue=1u, uint8_t outsideValue=0u)
Binarize an input image by thresholding.
Image BinaryThreshold (const Image &image1, double lowerThreshold=0.0, double upperThreshold=255.0, uint8_t insideValue=1u, uint8_t outsideValue=0u)
Binarize an input image by thresholding.
Image BinaryThresholdProjection (const Image &image1, unsigned int projectionDimension=0u, double thresholdValue=0.0, uint8_t foregroundValue=1u, uint8_t backgroundValue=0u)
BinaryThreshold projection.
Image BinomialBlur (const Image &image1, unsigned int repetitions=1u)
Performs a separable blur on each dimension of an image.
Image BinShrink (const Image &image1, std::vector< unsigned int > shrinkFactors=std::vector< unsigned int >(3, 1))
Reduce the size of an image by an integer factor in each dimension while performing averaging of an input neighborhood.
Image BitwiseNot (Image &&image1)
Implements pixel-wise generic operation on one image.
Image BitwiseNot (const Image &image1)
Implements pixel-wise generic operation on one image.
Image BlackTopHat (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool safeBorder=true)
Black top hat extracts local minima that are smaller than the structuring element.
Image BoundedReciprocal (Image &&image1)
Computes 1/(1+x) for each pixel in the image.
Image BoundedReciprocal (const Image &image1)
Computes 1/(1+x) for each pixel in the image.
Image BoxMean (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Implements a fast rectangular mean filter using the accumulator approach.
Image BoxSigma (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Implements a fast rectangular sigma filter using the accumulator approach.
Image BSplineDecomposition (const Image &image1, uint32_t splineOrder=3u)
Calculates the B-Spline coefficients of an image. Spline order may be from 0 to 5.
Image CannyEdgeDetection (const Image &image1, double lowerThreshold=0.0, double upperThreshold=0.0, std::vector< double > variance=std::vector< double >(3, 0.0), std::vector< double > maximumError=std::vector< double >(3, 0.01))
This filter is an implementation of a Canny edge detector for scalar-valued images.
Image CannySegmentationLevelSet (Image &&initialImage, const Image &featureImage, double threshold=0.0, double variance=0.0, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, double advectionScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false, double isoSurfaceValue=0.0)
Segments structures in images based on image features derived from pseudo-canny-edges.
Image CannySegmentationLevelSet (const Image &initialImage, const Image &featureImage, double threshold=0.0, double variance=0.0, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, double advectionScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false, double isoSurfaceValue=0.0)
Segments structures in images based on image features derived from pseudo-canny-edges.
Image ChangeLabel (Image &&image1, std::map< double, double > changeMap=std::map< double, double >())
Change Sets of Labels.
Image ChangeLabel (const Image &image1, std::map< double, double > changeMap=std::map< double, double >())
Change Sets of Labels.
Image ChangeLabelLabelMap (Image &&image1, std::map< double, double > changeMap=std::map< double, double >())
Replace the label Ids of selected LabelObjects with new label Ids.
Image ChangeLabelLabelMap (const Image &image1, std::map< double, double > changeMap=std::map< double, double >())
Replace the label Ids of selected LabelObjects with new label Ids.
Image CheckerBoard (const Image &image1, const Image &image2, std::vector< uint32_t > checkerPattern=std::vector< uint32_t >(3, 4))
Combines two images in a checkerboard pattern.
Image Clamp (Image &&image1, PixelIDValueEnum outputPixelType=itk::simple::sitkUnknown, double lowerBound=-std::numeric_limits< double >::max(), double upperBound=std::numeric_limits< double >::max())
Casts input pixels to output pixel type and clamps the output pixel values to a specified range.
Image Clamp (const Image &image1, PixelIDValueEnum outputPixelType=itk::simple::sitkUnknown, double lowerBound=-std::numeric_limits< double >::max(), double upperBound=std::numeric_limits< double >::max())
Casts input pixels to output pixel type and clamps the output pixel values to a specified range.
Image ClosingByReconstruction (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool fullyConnected=false, bool preserveIntensities=false)
Closing by reconstruction of an image.
Image CollidingFronts (const Image &image1, std::vector< std::vector< unsigned int > > seedPoints1=std::vector< std::vector< unsigned int > >(), std::vector< std::vector< unsigned int > > seedPoints2=std::vector< std::vector< unsigned int > >(), bool applyConnectivity=true, double negativeEpsilon=-1e-6, bool stopOnTargets=false)
Selects a region of space where two independent fronts run towards each other.
Image ComplexToImaginary (Image &&image1)
Computes pixel-wise the imaginary part of a complex image.
Image ComplexToImaginary (const Image &image1)
Computes pixel-wise the imaginary part of a complex image.
Image ComplexToModulus (Image &&image1)
Computes pixel-wise the Modulus of a complex image.
Image ComplexToModulus (const Image &image1)
Computes pixel-wise the Modulus of a complex image.
Image ComplexToPhase (Image &&image1)
Computes pixel-wise the modulus of a complex image.
Image ComplexToPhase (const Image &image1)
Computes pixel-wise the modulus of a complex image.
Image ComplexToReal (Image &&image1)
Computes pixel-wise the real(x) part of a complex image.
Image ComplexToReal (const Image &image1)
Computes pixel-wise the real(x) part of a complex image.
Image Compose (const std::vector< Image > &images)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image Compose (const Image &image1)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image Compose (const Image &image1, const Image &image2)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image Compose (const Image &image1, const Image &image2, const Image &image3)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image Compose (const Image &image1, const Image &image2, const Image &image3, const Image &image4)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image Compose (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image ConfidenceConnected (const Image &image1, std::vector< std::vector< unsigned int > > seedList=std::vector< std::vector< unsigned int > >(), unsigned int numberOfIterations=4u, double multiplier=4.5, unsigned int initialNeighborhoodRadius=1u, uint8_t replaceValue=1u)
Segment pixels with similar statistics using connectivity.
Image ConnectedComponent (const Image &image, const Image &maskImage, bool fullyConnected=false)
Label the objects in a binary image.
Image ConnectedComponent (const Image &image, bool fullyConnected=false)
Label the objects in a binary image.
Image ConnectedThreshold (const Image &image1, std::vector< std::vector< unsigned int > > seedList=std::vector< std::vector< unsigned int > >(), double lower=0, double upper=1, uint8_t replaceValue=1u, ConnectedThresholdImageFilter::ConnectivityType connectivity=itk::simple::ConnectedThresholdImageFilter::FaceConnectivity)
Label pixels that are connected to a seed and lie within a range of values.
Image ConstantPad (const Image &image1, std::vector< unsigned int > padLowerBound=std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound=std::vector< unsigned int >(3, 0), double constant=0.0)
Increase the image size by padding with a constant value.
Image Convolution (const Image &image, const Image &kernelImage, bool normalize=false, ConvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::ConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, ConvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::ConvolutionImageFilter::SAME)
Convolve a given image with an arbitrary image kernel.
Image Cos (Image &&image1)
Computes the cosine of each pixel.
Image Cos (const Image &image1)
Computes the cosine of each pixel.
Image Crop (Image &&image1, std::vector< unsigned int > lowerBoundaryCropSize=std::vector< unsigned int >(3, 0), std::vector< unsigned int > upperBoundaryCropSize=std::vector< unsigned int >(3, 0))
Decrease the image size by cropping the image by an itk::Size at both the upper and lower bounds of the largest possible region.
Image Crop (const Image &image1, std::vector< unsigned int > lowerBoundaryCropSize=std::vector< unsigned int >(3, 0), std::vector< unsigned int > upperBoundaryCropSize=std::vector< unsigned int >(3, 0))
Decrease the image size by cropping the image by an itk::Size at both the upper and lower bounds of the largest possible region.
Image CurvatureAnisotropicDiffusion (Image &&image1, double timeStep=0.0625, double conductanceParameter=3.0, unsigned int conductanceScalingUpdateInterval=1u, uint32_t numberOfIterations=5u)
itk::simple::CurvatureAnisotropicDiffusionImageFilter Procedural Interface
Image CurvatureAnisotropicDiffusion (const Image &image1, double timeStep=0.0625, double conductanceParameter=3.0, unsigned int conductanceScalingUpdateInterval=1u, uint32_t numberOfIterations=5u)
itk::simple::CurvatureAnisotropicDiffusionImageFilter Procedural Interface
Image CurvatureFlow (Image &&image1, double timeStep=0.05, uint32_t numberOfIterations=5u)
Denoise an image using curvature driven flow.
Image CurvatureFlow (const Image &image1, double timeStep=0.05, uint32_t numberOfIterations=5u)
Denoise an image using curvature driven flow.
Image CyclicShift (const Image &image1, std::vector< int > shift=std::vector< int >(3, 0))
Perform a cyclic spatial shift of image intensities on the image grid.
Image DanielssonDistanceMap (const Image &image1, bool inputIsBinary=false, bool squaredDistance=false, bool useImageSpacing=false)
This filter computes the distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
Image Derivative (const Image &image1, unsigned int direction=0u, unsigned int order=1u, bool useImageSpacing=true)
Computes the directional derivative of an image. The directional derivative at each pixel location is computed by convolution with a derivative operator of user-specified order.
Image DICOMOrient (const Image &image1, std::string desiredCoordinateOrientation=std::string("LPS"))
Permute axes and flip images as needed to obtain an approximation to the desired orientation.
Image DilateObjectMorphology (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double objectValue=1)
dilation of an object in an image
Image DiscreteGaussianDerivative (const Image &image1, std::vector< double > variance=std::vector< double >(3, 0.0), std::vector< unsigned int > order=std::vector< unsigned int >(3, 1), unsigned int maximumKernelWidth=32u, double maximumError=0.01, bool useImageSpacing=true, bool normalizeAcrossScale=false)
Calculates image derivatives using discrete derivative gaussian kernels. This filter calculates Gaussian derivative by separable convolution of an image and a discrete Gaussian derivative operator (kernel).
Image DiscreteGaussian (const Image &image1, std::vector< double > variance=std::vector< double >(3, 1.0), unsigned int maximumKernelWidth=32u, std::vector< double > maximumError=std::vector< double >(3, 0.01), bool useImageSpacing=true)
Blurs an image by separable convolution with discrete gaussian kernels. This filter performs Gaussian blurring by separable convolution of an image and a discrete Gaussian operator (kernel).
Image DisplacementFieldJacobianDeterminant (const Image &image1, bool useImageSpacing=true, std::vector< double > derivativeWeights=std::vector< double >())
Computes a scalar image from a vector image (e.g., deformation field) input, where each output scalar at each pixel is the Jacobian determinant of the vector field at that location. This calculation is correct in the case where the vector image is a "displacement" from the current location. The computation for the jacobian determinant is: det[ dT/dx ] = det[ I + du/dx ].
Image DivideFloor (Image &&image1, const Image &image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image DivideFloor (const Image &image1, const Image &image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Divide (Image &&image1, const Image &image2)
Pixel-wise division of two images.
Image Divide (const Image &image1, const Image &image2)
Pixel-wise division of two images.
Image DivideReal (Image &&image1, const Image &image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image DivideReal (const Image &image1, const Image &image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image DoubleThreshold (const Image &image1, double threshold1=0.0, double threshold2=1.0, double threshold3=254.0, double threshold4=255.0, uint8_t insideValue=1u, uint8_t outsideValue=0u, bool fullyConnected=false)
Binarize an input image using double thresholding.
Image EdgePotential (Image &&image1)
Computes the edge potential of an image from the image gradient.
Image EdgePotential (const Image &image1)
Computes the edge potential of an image from the image gradient.
Image Equal (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Equal (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image ErodeObjectMorphology (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, double objectValue=1, double backgroundValue=0)
Erosion of an object in an image.
Image Expand (const Image &image1, std::vector< unsigned int > expandFactors=std::vector< unsigned int >(3, 1), InterpolatorEnum interpolator=itk::simple::sitkLinear)
Expand the size of an image by an integer factor in each dimension.
Image Exp (Image &&image1)
Computes the exponential function of each pixel.
Image Exp (const Image &image1)
Computes the exponential function of each pixel.
Image ExpNegative (Image &&image1)
Computes the function exp(-K.x) for each input pixel.
Image ExpNegative (const Image &image1)
Computes the function exp(-K.x) for each input pixel.
Image FastApproximateRank (const Image &image1, double rank=0.5, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
A separable rank filter.
Image FastMarchingBase (const Image &image1, std::vector< std::vector< unsigned int > > trialPoints=std::vector< std::vector< unsigned int > >(), double normalizationFactor=1.0, double stoppingValue=std::numeric_limits< float >::max()/2.0, FastMarchingBaseImageFilter::TopologyCheckType topologyCheck=itk::simple::FastMarchingBaseImageFilter::Nothing)
Apply the Fast Marching method to solve an Eikonal equation on an image.
Image FastMarching (const Image &image1, std::vector< std::vector< unsigned int > > trialPoints=std::vector< std::vector< unsigned int > >(), double normalizationFactor=1.0, double stoppingValue=std::numeric_limits< double >::max()/2.0)
Solve an Eikonal equation using Fast Marching.
Image FastMarchingUpwindGradient (const Image &image1, std::vector< std::vector< unsigned int > > trialPoints=std::vector< std::vector< unsigned int > >(), unsigned int numberOfTargets=0u, std::vector< std::vector< unsigned int > > targetPoints=std::vector< std::vector< unsigned int > >(), double targetOffset=1.0, double normalizationFactor=1.0)
Generates the upwind gradient field of fast marching arrival times.
Image FFTConvolution (const Image &image, const Image &kernelImage, bool normalize=false, FFTConvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::FFTConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, FFTConvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::FFTConvolutionImageFilter::SAME)
Convolve a given image with an arbitrary image kernel using multiplication in the Fourier domain.
Image FFTNormalizedCorrelation (const Image &image1, const Image &image2, uint64_t requiredNumberOfOverlappingPixels=0u)
Calculate normalized cross correlation using FFTs.
Image FFTPad (const Image &image1, FFTPadImageFilter::BoundaryConditionType boundaryCondition=itk::simple::FFTPadImageFilter::ZERO_FLUX_NEUMANN_PAD, int sizeGreatestPrimeFactor=5)
Pad an image to make it suitable for an FFT transformation.
Image FFTShift (const Image &image1, bool inverse=false)
Shift the zero-frequency components of a Fourier transform to the center of the image.
Image Flip (const Image &image1, std::vector< bool > flipAxes=std::vector< bool >(3, false), bool flipAboutOrigin=false)
Flips an image across user specified axes.
Image ForwardFFT (const Image &image1)
Base class for forward Fast Fourier Transform .
Image GeodesicActiveContourLevelSet (Image &&initialImage, const Image &featureImage, double maximumRMSError=0.01, double propagationScaling=1.0, double curvatureScaling=1.0, double advectionScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a user supplied edge potential map.
Image GeodesicActiveContourLevelSet (const Image &initialImage, const Image &featureImage, double maximumRMSError=0.01, double propagationScaling=1.0, double curvatureScaling=1.0, double advectionScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a user supplied edge potential map.
Image GradientAnisotropicDiffusion (Image &&image1, double timeStep=0.125, double conductanceParameter=3, unsigned int conductanceScalingUpdateInterval=1u, uint32_t numberOfIterations=5u)
itk::simple::GradientAnisotropicDiffusionImageFilter Procedural Interface
Image GradientAnisotropicDiffusion (const Image &image1, double timeStep=0.125, double conductanceParameter=3, unsigned int conductanceScalingUpdateInterval=1u, uint32_t numberOfIterations=5u)
itk::simple::GradientAnisotropicDiffusionImageFilter Procedural Interface
Image Gradient (const Image &image1, bool useImageSpacing=true, bool useImageDirection=false)
Computes the gradient of an image using directional derivatives.
Image GradientMagnitude (const Image &image1, bool useImageSpacing=true)
Computes the gradient magnitude of an image region at each pixel.
Image GradientMagnitudeRecursiveGaussian (Image &&image1, double sigma=1.0, bool normalizeAcrossScale=false)
Computes the Magnitude of the Gradient of an image by convolution with the first derivative of a Gaussian.
Image GradientMagnitudeRecursiveGaussian (const Image &image1, double sigma=1.0, bool normalizeAcrossScale=false)
Computes the Magnitude of the Gradient of an image by convolution with the first derivative of a Gaussian.
Image GradientRecursiveGaussian (const Image &image1, double sigma=1.0, bool normalizeAcrossScale=false, bool useImageDirection=false)
Computes the gradient of an image by convolution with the first derivative of a Gaussian.
Image GrayscaleConnectedClosing (const Image &image1, std::vector< uint32_t > seed=std::vector< uint32_t >(3, 0), bool fullyConnected=false)
Enhance pixels associated with a dark object (identified by a seed pixel) where the dark object is surrounded by a brighter object.
Image GrayscaleConnectedOpening (const Image &image1, std::vector< unsigned int > seed=std::vector< unsigned int >(3, 0), bool fullyConnected=false)
Enhance pixels associated with a bright object (identified by a seed pixel) where the bright object is surrounded by a darker object.
Image GrayscaleDilate (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall)
Grayscale dilation of an image.
Image GrayscaleErode (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall)
Grayscale erosion of an image.
Image GrayscaleFillhole (const Image &image1, bool fullyConnected=false)
Remove local minima not connected to the boundary of the image.
Image GrayscaleGeodesicDilate (const Image &image1, const Image &image2, bool runOneIteration=false, bool fullyConnected=false)
geodesic gray scale dilation of an image
Image GrayscaleGeodesicErode (const Image &image1, const Image &image2, bool runOneIteration=false, bool fullyConnected=false)
geodesic gray scale erosion of an image
Image GrayscaleGrindPeak (const Image &image1, bool fullyConnected=false)
Remove local maxima not connected to the boundary of the image.
Image GrayscaleMorphologicalClosing (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool safeBorder=true)
gray scale dilation of an image
Image GrayscaleMorphologicalOpening (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool safeBorder=true)
gray scale dilation of an image
Image GreaterEqual (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image GreaterEqual (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Greater (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Greater (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image HalfHermitianToRealInverseFFT (const Image &image1, bool actualXDimensionIsOdd=false)
Base class for specialized complex-to-real inverse Fast Fourier Transform .
Image HConcave (const Image &image1, double height=2.0, bool fullyConnected=false)
Identify local minima whose depth below the baseline is greater than h.
Image HConvex (const Image &image1, double height=2.0, bool fullyConnected=false)
Identify local maxima whose height above the baseline is greater than h.
Image HistogramMatching (const Image &image, const Image &referenceImage, uint32_t numberOfHistogramLevels=256u, uint32_t numberOfMatchPoints=1u, bool thresholdAtMeanIntensity=true)
Normalize the grayscale values for a source image by matching the shape of the source image histogram to a reference histogram.
Image HMaxima (const Image &image1, double height=2.0)
Suppress local maxima whose height above the baseline is less than h.
Image HMinima (const Image &image1, double height=2.0, bool fullyConnected=false)
Suppress local minima whose depth below the baseline is less than h.
Image HuangThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=128u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Huang Threshold.
Image HuangThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=128u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Huang Threshold.
Image IntensityWindowing (Image &&image1, double windowMinimum=0.0, double windowMaximum=255.0, double outputMinimum=0.0, double outputMaximum=255.0)
Applies a linear transformation to the intensity levels of the input Image that are inside a user-defined interval. Values below this interval are mapped to a constant. Values over the interval are mapped to another constant.
Image IntensityWindowing (const Image &image1, double windowMinimum=0.0, double windowMaximum=255.0, double outputMinimum=0.0, double outputMaximum=255.0)
Applies a linear transformation to the intensity levels of the input Image that are inside a user-defined interval. Values below this interval are mapped to a constant. Values over the interval are mapped to another constant.
Image IntermodesThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Intermodes Threshold.
Image IntermodesThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Intermodes Threshold.
Image InverseDeconvolution (const Image &image1, const Image &image2, double kernelZeroMagnitudeThreshold=1.0e-4, bool normalize=false, InverseDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::InverseDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, InverseDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::InverseDeconvolutionImageFilter::SAME)
The direct linear inverse deconvolution filter.
Image InverseDisplacementField (const Image &image1, std::vector< uint32_t > size=std::vector< uint32_t >(3, 0), std::vector< double > outputOrigin=std::vector< double >(3, 0.0), std::vector< double > outputSpacing=std::vector< double >(3, 1.0), unsigned int subsamplingFactor=16u)
Computes the inverse of a displacement field.
Image InverseFFT (const Image &image1)
Base class for inverse Fast Fourier Transform .
Image InvertDisplacementField (const Image &image1, uint32_t maximumNumberOfIterations=10u, double maxErrorToleranceThreshold=0.1, double meanErrorToleranceThreshold=0.001, bool enforceBoundaryCondition=true)
Iteratively estimate the inverse field of a displacement field.
Image InvertIntensity (Image &&image1, double maximum=255)
Invert the intensity of an image.
Image InvertIntensity (const Image &image1, double maximum=255)
Invert the intensity of an image.
Image IsoContourDistance (const Image &image1, double levelSetValue=0.0, double farValue=10)
Compute an approximate distance from an interpolated isocontour to the close grid points.
Image IsoDataThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the IsoData Threshold.
Image IsoDataThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the IsoData Threshold.
Image IsolatedConnected (const Image &image1, std::vector< unsigned int > seed1=std::vector< unsigned int >(3, 0), std::vector< unsigned int > seed2=std::vector< unsigned int >(3, 0), double lower=0, double upper=1, uint8_t replaceValue=1u, double isolatedValueTolerance=1.0, bool findUpperThreshold=true)
Label pixels that are connected to one set of seeds but not another.
Image IsolatedWatershed (const Image &image1, std::vector< uint32_t > seed1=std::vector< uint32_t >(3, 0), std::vector< uint32_t > seed2=std::vector< uint32_t >(3, 0), double threshold=0.0, double upperValueLimit=1.0, double isolatedValueTolerance=0.001, uint8_t replaceValue1=1u, uint8_t replaceValue2=2u)
Isolate watershed basins using two seeds.
Image IterativeInverseDisplacementField (const Image &image1, uint32_t numberOfIterations=5u, double stopValue=0.0)
Computes the inverse of a displacement field.
Image JoinSeries (const std::vector< Image > &images, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image JoinSeries (const Image &image1, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image JoinSeries (const Image &image1, const Image &image2, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image JoinSeries (const Image &image1, const Image &image2, const Image &image3, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image JoinSeries (const Image &image1, const Image &image2, const Image &image3, const Image &image4, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image JoinSeries (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, double origin=0.0, double spacing=1.0)
Join N-D images into an (N+1)-D image.
Image KittlerIllingworthThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the KittlerIllingworth Threshold.
Image KittlerIllingworthThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the KittlerIllingworth Threshold.
Image LabelContour (Image &&image1, bool fullyConnected=false, double backgroundValue=0)
Labels the pixels on the border of the objects in a labeled image.
Image LabelContour (const Image &image1, bool fullyConnected=false, double backgroundValue=0)
Labels the pixels on the border of the objects in a labeled image.
Image LabelImageToLabelMap (const Image &image1, double backgroundValue=0)
convert a labeled image to a label collection image
Image LabelMapContourOverlay (const Image &labelMapImage, const Image &featureImage, double opacity=0.5, std::vector< unsigned int > dilationRadius=std::vector< unsigned int >(3, 1), std::vector< unsigned int > contourThickness=std::vector< unsigned int >(3, 1), unsigned int sliceDimension=0u, LabelMapContourOverlayImageFilter::ContourTypeType contourType=itk::simple::LabelMapContourOverlayImageFilter::CONTOUR, LabelMapContourOverlayImageFilter::PriorityType priority=itk::simple::LabelMapContourOverlayImageFilter::HIGH_LABEL_ON_TOP, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Apply a colormap to the contours (outlines) of each object in a label map and superimpose it on top of the feature image.
Image LabelMapMask (const Image &labelMapImage, const Image &featureImage, uint64_t label=1u, double backgroundValue=0, bool negated=false, bool crop=false, std::vector< unsigned int > cropBorder=std::vector< unsigned int >(3, 0))
Mask and image with a LabelMap .
Image LabelMapOverlay (const Image &labelMapImage, const Image &featureImage, double opacity=0.5, std::vector< unsigned char > colormap=std::vector< unsigned char >())
Apply a colormap to a label map and superimpose it on an image.
Image LabelMapToBinary (const Image &image1, double backgroundValue=0, double foregroundValue=1.0)
Convert a LabelMap to a binary image.
Image LabelMapToLabel (const Image &image1)
Converts a LabelMap to a labeled image.
Image LabelMapToRGB (const Image &image1, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Convert a LabelMap to a colored image.
Image LabelOverlay (Image &&image, const Image &labelImage, double opacity=0.5, double backgroundValue=0.0, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Apply a colormap to a label image and put it on top of the input image.
Image LabelOverlay (const Image &image, const Image &labelImage, double opacity=0.5, double backgroundValue=0.0, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Apply a colormap to a label image and put it on top of the input image.
Image LabelToRGB (Image &&image1, double backgroundValue=0.0, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Apply a colormap to a label image.
Image LabelToRGB (const Image &image1, double backgroundValue=0.0, std::vector< uint8_t > colormap=std::vector< uint8_t >())
Apply a colormap to a label image.
Image LabelUniqueLabelMap (Image &&image1, bool reverseOrdering=false)
Make sure that the objects are not overlapping.
Image LabelUniqueLabelMap (const Image &image1, bool reverseOrdering=false)
Make sure that the objects are not overlapping.
Image LabelVoting (const std::vector< Image > &images, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LabelVoting (const Image &image1, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LabelVoting (const Image &image1, const Image &image2, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LabelVoting (const Image &image1, const Image &image2, const Image &image3, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LabelVoting (const Image &image1, const Image &image2, const Image &image3, const Image &image4, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LabelVoting (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image LandweberDeconvolution (const Image &image1, const Image &image2, double alpha=0.1, int numberOfIterations=1, bool normalize=false, LandweberDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::LandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, LandweberDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::LandweberDeconvolutionImageFilter::SAME)
Deconvolve an image using the Landweber deconvolution algorithm.
Image Laplacian (const Image &image1, bool useImageSpacing=true)
itk::simple::LaplacianImageFilter Procedural Interface
Image LaplacianRecursiveGaussian (const Image &image1, double sigma=1.0, bool normalizeAcrossScale=false)
Computes the Laplacian of Gaussian (LoG) of an image.
Image LaplacianSegmentationLevelSet (Image &&initialImage, const Image &featureImage, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a second derivative image features.
Image LaplacianSegmentationLevelSet (const Image &initialImage, const Image &featureImage, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a second derivative image features.
Image LaplacianSharpening (const Image &image1, bool useImageSpacing=true)
This filter sharpens an image using a Laplacian. LaplacianSharpening highlights regions of rapid intensity change and therefore highlights or enhances the edges. The result is an image that appears more in focus.
Image LessEqual (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image LessEqual (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Less (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Less (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image LiThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Li Threshold.
Image LiThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Li Threshold.
Image Log10 (Image &&image1)
Computes the log10 of each pixel.
Image Log10 (const Image &image1)
Computes the log10 of each pixel.
Image Log (Image &&image1)
Computes the log() of each pixel.
Image Log (const Image &image1)
Computes the log() of each pixel.
Image MagnitudeAndPhaseToComplex (Image &&image1, const Image &image2)
Implements pixel-wise conversion of magnitude and phase data into complex voxels.
Image MagnitudeAndPhaseToComplex (const Image &image1, const Image &image2)
Implements pixel-wise conversion of magnitude and phase data into complex voxels.
Image MaskedFFTNormalizedCorrelation (const Image &fixedImage, const Image &movingImage, const Image &fixedImageMask, const Image &movingImageMask, uint64_t requiredNumberOfOverlappingPixels=0u, float requiredFractionOfOverlappingPixels=0.0)
Calculate masked normalized cross correlation using FFTs.
Image Mask (Image &&image, const Image &maskImage, double outsideValue=0, double maskingValue=0)
Mask an image with a mask.
Image Mask (const Image &image, const Image &maskImage, double outsideValue=0, double maskingValue=0)
Mask an image with a mask.
Image MaskNegated (Image &&image, const Image &maskImage, double outsideValue=0, double maskingValue=0)
Mask an image with the negation (or logical compliment) of a mask.
Image MaskNegated (const Image &image, const Image &maskImage, double outsideValue=0, double maskingValue=0)
Mask an image with the negation (or logical compliment) of a mask.
Image MaximumEntropyThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the MaximumEntropy Threshold.
Image MaximumEntropyThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the MaximumEntropy Threshold.
Image Maximum (Image &&image1, const Image &image2)
Implements a pixel-wise operator Max(a,b) between two images.
Image Maximum (const Image &image1, const Image &image2)
Implements a pixel-wise operator Max(a,b) between two images.
Image MaximumProjection (const Image &image1, unsigned int projectionDimension=0u)
Maximum projection.
Image Mean (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Applies an averaging filter to an image.
Image MeanProjection (const Image &image1, unsigned int projectionDimension=0u)
Mean projection.
Image Median (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Applies a median filter to an image.
Image MedianProjection (const Image &image1, unsigned int projectionDimension=0u)
Median projection.
Image MergeLabelMap (const std::vector< Image > &images, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image MergeLabelMap (const Image &image1, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image MergeLabelMap (const Image &image1, const Image &image2, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image MergeLabelMap (const Image &image1, const Image &image2, const Image &image3, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image MergeLabelMap (const Image &image1, const Image &image2, const Image &image3, const Image &image4, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image MergeLabelMap (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, MergeLabelMapFilter::MethodType method=itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
Image Minimum (Image &&image1, const Image &image2)
Implements a pixel-wise operator Min(a,b) between two images.
Image Minimum (const Image &image1, const Image &image2)
Implements a pixel-wise operator Min(a,b) between two images.
Image MinimumProjection (const Image &image1, unsigned int projectionDimension=0u)
Minimum projection.
Image MinMaxCurvatureFlow (Image &&image1, double timeStep=0.05, uint32_t numberOfIterations=5u, int stencilRadius=2)
Denoise an image using min/max curvature flow.
Image MinMaxCurvatureFlow (const Image &image1, double timeStep=0.05, uint32_t numberOfIterations=5u, int stencilRadius=2)
Denoise an image using min/max curvature flow.
Image MirrorPad (const Image &image1, std::vector< unsigned int > padLowerBound=std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound=std::vector< unsigned int >(3, 0), double decayBase=1.0)
Increase the image size by padding with replicants of the input image value.
Image Modulus (Image &&image1, const Image &image2)
Computes the modulus (x % dividend) pixel-wise.
Image Modulus (const Image &image1, const Image &image2)
Computes the modulus (x % dividend) pixel-wise.
Image MomentsThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Moments Threshold.
Image MomentsThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Moments Threshold.
Image MorphologicalGradient (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall)
gray scale dilation of an image
Image MorphologicalWatershedFromMarkers (const Image &image, const Image &markerImage, bool markWatershedLine=true, bool fullyConnected=false)
Morphological watershed transform from markers.
Image MorphologicalWatershed (const Image &image1, double level=0.0, bool markWatershedLine=true, bool fullyConnected=false)
Watershed segmentation implementation with morphological operators.
Image MultiLabelSTAPLE (const std::vector< Image > &images, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image MultiLabelSTAPLE (const Image &image1, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image MultiLabelSTAPLE (const Image &image1, const Image &image2, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image MultiLabelSTAPLE (const Image &image1, const Image &image2, const Image &image3, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image MultiLabelSTAPLE (const Image &image1, const Image &image2, const Image &image3, const Image &image4, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image MultiLabelSTAPLE (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, uint64_t labelForUndecidedPixels=std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold=1e-5f, unsigned int maximumNumberOfIterations=std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities=std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
Image Multiply (Image &&image1, const Image &image2)
Pixel-wise multiplication of two images.
Image Multiply (const Image &image1, const Image &image2)
Pixel-wise multiplication of two images.
Image N4BiasFieldCorrection (const Image &image, const Image &maskImage, double convergenceThreshold=0.001, std::vector< uint32_t > maximumNumberOfIterations=std::vector< uint32_t >(4, 50), double biasFieldFullWidthAtHalfMaximum=0.15, double wienerFilterNoise=0.01, uint32_t numberOfHistogramBins=200u, std::vector< uint32_t > numberOfControlPoints=std::vector< uint32_t >(3, 4), uint32_t splineOrder=3u, bool useMaskLabel=true, uint8_t maskLabel=1)
Implementation of the N4 bias field correction algorithm.
Image N4BiasFieldCorrection (const Image &image, double convergenceThreshold=0.001, std::vector< uint32_t > maximumNumberOfIterations=std::vector< uint32_t >(4, 50), double biasFieldFullWidthAtHalfMaximum=0.15, double wienerFilterNoise=0.01, uint32_t numberOfHistogramBins=200u, std::vector< uint32_t > numberOfControlPoints=std::vector< uint32_t >(3, 4), uint32_t splineOrder=3u, bool useMaskLabel=true, uint8_t maskLabel=1)
Implementation of the N4 bias field correction algorithm.
Image NaryAdd (const std::vector< Image > &images)
Pixel-wise addition of N images.
Image NaryAdd (const Image &image1)
Pixel-wise addition of N images.
Image NaryAdd (const Image &image1, const Image &image2)
Pixel-wise addition of N images.
Image NaryAdd (const Image &image1, const Image &image2, const Image &image3)
Pixel-wise addition of N images.
Image NaryAdd (const Image &image1, const Image &image2, const Image &image3, const Image &image4)
Pixel-wise addition of N images.
Image NaryAdd (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5)
Pixel-wise addition of N images.
Image NaryMaximum (const std::vector< Image > &images)
Computes the pixel-wise maximum of several images.
Image NaryMaximum (const Image &image1)
Computes the pixel-wise maximum of several images.
Image NaryMaximum (const Image &image1, const Image &image2)
Computes the pixel-wise maximum of several images.
Image NaryMaximum (const Image &image1, const Image &image2, const Image &image3)
Computes the pixel-wise maximum of several images.
Image NaryMaximum (const Image &image1, const Image &image2, const Image &image3, const Image &image4)
Computes the pixel-wise maximum of several images.
Image NaryMaximum (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5)
Computes the pixel-wise maximum of several images.
Image NeighborhoodConnected (const Image &image1, std::vector< std::vector< unsigned int > > seedList=std::vector< std::vector< unsigned int > >(), double lower=0, double upper=1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), double replaceValue=1)
Label pixels that are connected to a seed and lie within a neighborhood.
Image Noise (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Calculate the local noise in an image.
Image NormalizedCorrelation (const Image &image, const Image &maskImage, const Image &templateImage)
Computes the normalized correlation of an image and a template.
Image Normalize (const Image &image1)
Normalize an image by setting its mean to zero and variance to one.
Image NormalizeToConstant (const Image &image1, double constant=1.0)
Scales image pixel intensities to make the sum of all pixels equal a user-defined constant.
Image NotEqual (Image &&image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image NotEqual (const Image &image1, const Image &image2, uint8_t backgroundValue=0u, uint8_t foregroundValue=1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
Image Not (Image &&image1)
Implements the NOT logical operator pixel-wise on an image.
Image Not (const Image &image1)
Implements the NOT logical operator pixel-wise on an image.
Image ObjectnessMeasure (const Image &image1, double alpha=0.5, double beta=0.5, double gamma=5.0, bool scaleObjectnessMeasure=true, unsigned int objectDimension=1u, bool brightObject=true)
Enhance M-dimensional objects in N-dimensional images.
Image OpeningByReconstruction (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool fullyConnected=false, bool preserveIntensities=false)
Opening by reconstruction of an image.
Image Or (Image &&image1, const Image &image2)
Implements the OR bitwise operator pixel-wise between two images.
Image Or (const Image &image1, const Image &image2)
Implements the OR bitwise operator pixel-wise between two images.
Image OtsuMultipleThresholds (const Image &image1, uint8_t numberOfThresholds=1u, uint8_t labelOffset=0u, uint32_t numberOfHistogramBins=128u, bool valleyEmphasis=false, bool returnBinMidpoint=false)
Threshold an image using multiple Otsu Thresholds.
Image OtsuThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=128u, bool maskOutput=true, uint8_t maskValue=255u, bool returnBinMidpoint=false)
Threshold an image using the Otsu Threshold.
Image OtsuThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=128u, bool maskOutput=true, uint8_t maskValue=255u, bool returnBinMidpoint=false)
Threshold an image using the Otsu Threshold.
Image PermuteAxes (const Image &image1, std::vector< unsigned int > order=std::vector< unsigned int >(itk::simple::PermuteAxesImageFilter::DefaultOrder))
Permutes the image axes according to a user specified order.
Image Pow (Image &&image1, const Image &image2)
Computes the powers of 2 images.
Image Pow (const Image &image1, const Image &image2)
Computes the powers of 2 images.
Image ProjectedLandweberDeconvolution (const Image &image1, const Image &image2, double alpha=0.1, int numberOfIterations=1, bool normalize=false, ProjectedLandweberDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::ProjectedLandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, ProjectedLandweberDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::ProjectedLandweberDeconvolutionImageFilter::SAME)
Deconvolve an image using the projected Landweber deconvolution algorithm.
Image Rank (const Image &image1, double rank=0.5, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1))
Rank filter of a greyscale image.
Image RealAndImaginaryToComplex (const Image &image1, const Image &image2)
ComposeImageFilter combine several scalar images into a multicomponent image.
Image RealToHalfHermitianForwardFFT (const Image &image1)
Base class for specialized real-to-complex forward Fast Fourier Transform .
Image ReconstructionByDilation (const Image &markerImage, const Image &maskImage, bool fullyConnected=false, bool useInternalCopy=true)
grayscale reconstruction by dilation of an image
Image ReconstructionByErosion (const Image &markerImage, const Image &maskImage, bool fullyConnected=false, bool useInternalCopy=true)
grayscale reconstruction by erosion of an image
Image RecursiveGaussian (Image &&image1, double sigma=1.0, bool normalizeAcrossScale=false, RecursiveGaussianImageFilter::OrderType order=itk::simple::RecursiveGaussianImageFilter::ZeroOrder, unsigned int direction=0u)
Base class for computing IIR convolution with an approximation of a Gaussian kernel.
Image RecursiveGaussian (const Image &image1, double sigma=1.0, bool normalizeAcrossScale=false, RecursiveGaussianImageFilter::OrderType order=itk::simple::RecursiveGaussianImageFilter::ZeroOrder, unsigned int direction=0u)
Base class for computing IIR convolution with an approximation of a Gaussian kernel.
Image RegionalMaxima (const Image &image1, double backgroundValue=0.0, double foregroundValue=1.0, bool fullyConnected=false, bool flatIsMaxima=true)
Produce a binary image where foreground is the regional maxima of the input image.
Image RegionalMinima (const Image &image1, double backgroundValue=0.0, double foregroundValue=1.0, bool fullyConnected=false, bool flatIsMinima=true)
Produce a binary image where foreground is the regional minima of the input image.
Image RegionOfInterest (const Image &image1, std::vector< unsigned int > size=std::vector< unsigned int >(3, 1), std::vector< int > index=std::vector< int >(3, 0))
Extract a region of interest from the input image.
Image RelabelComponent (Image &&image1, uint64_t minimumObjectSize=0u, bool sortByObjectSize=true)
Relabel the components in an image such that consecutive labels are used.
Image RelabelComponent (const Image &image1, uint64_t minimumObjectSize=0u, bool sortByObjectSize=true)
Relabel the components in an image such that consecutive labels are used.
Image RelabelLabelMap (Image &&image1, bool reverseOrdering=true)
This filter relabels the LabelObjects; the new labels are arranged consecutively with consideration for the background value.
Image RelabelLabelMap (const Image &image1, bool reverseOrdering=true)
This filter relabels the LabelObjects; the new labels are arranged consecutively with consideration for the background value.
Image RenyiEntropyThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the RenyiEntropy Threshold.
Image RenyiEntropyThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the RenyiEntropy Threshold.
Image RescaleIntensity (Image &&image1, double outputMinimum=0, double outputMaximum=255)
Applies a linear transformation to the intensity levels of the input Image .
Image RescaleIntensity (const Image &image1, double outputMinimum=0, double outputMaximum=255)
Applies a linear transformation to the intensity levels of the input Image .
Image RichardsonLucyDeconvolution (const Image &image1, const Image &image2, int numberOfIterations=1, bool normalize=false, RichardsonLucyDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::RichardsonLucyDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, RichardsonLucyDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::RichardsonLucyDeconvolutionImageFilter::SAME)
Deconvolve an image using the Richardson-Lucy deconvolution algorithm.
Image Round (Image &&image1)
Rounds the value of each pixel.
Image Round (const Image &image1)
Rounds the value of each pixel.
Image SaltAndPepperNoise (Image &&image1, double probability=0.01, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with fixed value impulse noise, often called salt and pepper noise.
Image SaltAndPepperNoise (const Image &image1, double probability=0.01, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with fixed value impulse noise, often called salt and pepper noise.
Image ScalarChanAndVeseDenseLevelSet (const Image &initialImage, const Image &featureImage, double maximumRMSError=0.02, uint32_t numberOfIterations=1000u, double lambda1=1.0, double lambda2=1.0, double epsilon=1.0, double curvatureWeight=1.0, double areaWeight=0.0, double reinitializationSmoothingWeight=0.0, double volume=0.0, double volumeMatchingWeight=0.0, ScalarChanAndVeseDenseLevelSetImageFilter::HeavisideStepFunctionType heavisideStepFunction=itk::simple::ScalarChanAndVeseDenseLevelSetImageFilter::AtanRegularizedHeaviside, bool useImageSpacing=true)
Dense implementation of the Chan and Vese multiphase level set image filter.
Image ScalarConnectedComponent (const Image &image, const Image &maskImage, double distanceThreshold=0.0, bool fullyConnected=false)
A connected components filter that labels the objects in an arbitrary image. Two pixels are similar if they are within threshold of each other. Uses ConnectedComponentFunctorImageFilter .
Image ScalarConnectedComponent (const Image &image, double distanceThreshold=0.0, bool fullyConnected=false)
A connected components filter that labels the objects in an arbitrary image. Two pixels are similar if they are within threshold of each other. Uses ConnectedComponentFunctorImageFilter .
Image ScalarImageKmeans (const Image &image1, std::vector< double > classWithInitialMean=std::vector< double >(), bool useNonContiguousLabels=false)
Classifies the intensity values of a scalar image using the K-Means algorithm.
Image ScalarToRGBColormap (const Image &image1, ScalarToRGBColormapImageFilter::ColormapType colormap=itk::simple::ScalarToRGBColormapImageFilter::Grey, bool useInputImageExtremaForScaling=true)
Implements pixel-wise intensity->rgb mapping operation on one image.
Image ShanbhagThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Shanbhag Threshold.
Image ShanbhagThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Shanbhag Threshold.
Image ShapeDetectionLevelSet (Image &&initialImage, const Image &featureImage, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a user supplied edge potential map.
Image ShapeDetectionLevelSet (const Image &initialImage, const Image &featureImage, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on a user supplied edge potential map.
Image ShiftScale (const Image &image1, double shift=0, double scale=1.0, PixelIDValueEnum outputPixelType=itk::simple::sitkUnknown)
Shift and scale the pixels in an image.
Image ShotNoise (Image &&image1, double scale=1.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with shot noise.
Image ShotNoise (const Image &image1, double scale=1.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with shot noise.
Image Shrink (const Image &image1, std::vector< unsigned int > shrinkFactors=std::vector< unsigned int >(3, 1))
Reduce the size of an image by an integer factor in each dimension.
Image Sigmoid (Image &&image1, double alpha=1, double beta=0, double outputMaximum=255, double outputMinimum=0)
Computes the sigmoid function pixel-wise.
Image Sigmoid (const Image &image1, double alpha=1, double beta=0, double outputMaximum=255, double outputMinimum=0)
Computes the sigmoid function pixel-wise.
Image SignedDanielssonDistanceMap (const Image &image1, bool insideIsPositive=false, bool squaredDistance=false, bool useImageSpacing=false)
itk::simple::SignedDanielssonDistanceMapImageFilter Procedural Interface
Image SignedMaurerDistanceMap (const Image &image1, bool insideIsPositive=false, bool squaredDistance=true, bool useImageSpacing=false, double backgroundValue=0.0)
This filter calculates the Euclidean distance transform of a binary image in linear time for arbitrary dimensions.
Image SimpleContourExtractor (const Image &image1, double inputForegroundValue=1.0, double inputBackgroundValue=0.0, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), double outputForegroundValue=1.0, double outputBackgroundValue=0.0)
Computes an image of contours which will be the contour of the first image.
Image Sin (Image &&image1)
Computes the sine of each pixel.
Image Sin (const Image &image1)
Computes the sine of each pixel.
Image Slice (const Image &image1, std::vector< int32_t > start=std::vector< int32_t >(3, 0), std::vector< int32_t > stop=std::vector< int32_t >(3, std::numeric_limits< int32_t >::max()), std::vector< int > step=std::vector< int >(3, 1))
Slices an image based on a starting index and a stopping index, and a step size.
Image SLIC (const Image &image1, std::vector< unsigned int > superGridSize=std::vector< unsigned int >(3, 50), double spatialProximityWeight=10.0, uint32_t maximumNumberOfIterations=5u, bool enforceConnectivity=true, bool initializationPerturbation=true)
Simple Linear Iterative Clustering (SLIC) super-pixel segmentation.
Image SmoothingRecursiveGaussian (Image &&image1, std::vector< double > sigma=std::vector< double >(3, 1.0), bool normalizeAcrossScale=false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
Image SmoothingRecursiveGaussian (const Image &image1, std::vector< double > sigma=std::vector< double >(3, 1.0), bool normalizeAcrossScale=false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
Image SobelEdgeDetection (const Image &image1)
A 2D or 3D edge detection using the Sobel operator.
Image SpeckleNoise (Image &&image1, double standardDeviation=1.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with speckle (multiplicative) noise.
Image SpeckleNoise (const Image &image1, double standardDeviation=1.0, uint32_t seed=(uint32_t) itk::simple::sitkWallClock)
Alter an image with speckle (multiplicative) noise.
Image Sqrt (Image &&image1)
Computes the square root of each pixel.
Image Sqrt (const Image &image1)
Computes the square root of each pixel.
Image SquaredDifference (Image &&image1, const Image &image2)
Implements pixel-wise the computation of squared difference.
Image SquaredDifference (const Image &image1, const Image &image2)
Implements pixel-wise the computation of squared difference.
Image Square (Image &&image1)
Computes the square of the intensity values pixel-wise.
Image Square (const Image &image1)
Computes the square of the intensity values pixel-wise.
Image StandardDeviationProjection (const Image &image1, unsigned int projectionDimension=0u)
Mean projection.
Image STAPLE (const std::vector< Image > &images, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image STAPLE (const Image &image1, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image STAPLE (const Image &image1, const Image &image2, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image STAPLE (const Image &image1, const Image &image2, const Image &image3, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image STAPLE (const Image &image1, const Image &image2, const Image &image3, const Image &image4, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image STAPLE (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, double confidenceWeight=1.0, double foregroundValue=1.0, unsigned int maximumIterations=std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
Image StochasticFractalDimension (const Image &image, const Image &maskImage, std::vector< unsigned int > neighborhoodRadius=std::vector< unsigned int >(3, 2u))
This filter computes the stochastic fractal dimension of the input image.
Image StochasticFractalDimension (const Image &image, std::vector< unsigned int > neighborhoodRadius=std::vector< unsigned int >(3, 2u))
This filter computes the stochastic fractal dimension of the input image.
Image Subtract (Image &&image1, const Image &image2)
Pixel-wise subtraction of two images.
Image Subtract (const Image &image1, const Image &image2)
Pixel-wise subtraction of two images.
Image SumProjection (const Image &image1, unsigned int projectionDimension=0u)
Sum projection.
Image Tan (Image &&image1)
Computes the tangent of each input pixel.
Image Tan (const Image &image1)
Computes the tangent of each input pixel.
Image TernaryAdd (Image &&image1, const Image &image2, const Image &image3)
Pixel-wise addition of three images.
Image TernaryAdd (const Image &image1, const Image &image2, const Image &image3)
Pixel-wise addition of three images.
Image TernaryMagnitude (Image &&image1, const Image &image2, const Image &image3)
Compute the pixel-wise magnitude of three images.
Image TernaryMagnitude (const Image &image1, const Image &image2, const Image &image3)
Compute the pixel-wise magnitude of three images.
Image TernaryMagnitudeSquared (Image &&image1, const Image &image2, const Image &image3)
Compute the pixel-wise squared magnitude of three images.
Image TernaryMagnitudeSquared (const Image &image1, const Image &image2, const Image &image3)
Compute the pixel-wise squared magnitude of three images.
Image Threshold (Image &&image1, double lower=0.0, double upper=1.0, double outsideValue=0.0)
Set image values to a user-specified value if they are below, above, or between simple threshold values.
Image Threshold (const Image &image1, double lower=0.0, double upper=1.0, double outsideValue=0.0)
Set image values to a user-specified value if they are below, above, or between simple threshold values.
Image ThresholdMaximumConnectedComponents (const Image &image1, uint32_t minimumObjectSizeInPixels=0u, double upperBoundary=std::numeric_limits< double >::max(), uint8_t insideValue=1u, uint8_t outsideValue=0u)
Finds the threshold value of an image based on maximizing the number of objects in the image that are larger than a given minimal size.
Image ThresholdSegmentationLevelSet (Image &&initialImage, const Image &featureImage, double lowerThreshold=0.0, double upperThreshold=255.0, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on intensity values.
Image ThresholdSegmentationLevelSet (const Image &initialImage, const Image &featureImage, double lowerThreshold=0.0, double upperThreshold=255.0, double maximumRMSError=0.02, double propagationScaling=1.0, double curvatureScaling=1.0, uint32_t numberOfIterations=1000u, bool reverseExpansionDirection=false)
Segments structures in images based on intensity values.
Image TikhonovDeconvolution (const Image &image1, const Image &image2, double regularizationConstant=0.0, bool normalize=false, TikhonovDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::TikhonovDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, TikhonovDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::TikhonovDeconvolutionImageFilter::SAME)
An inverse deconvolution filter regularized in the Tikhonov sense.
Image Tile (const std::vector< Image > &images, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Tile (const Image &image1, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Tile (const Image &image1, const Image &image2, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Tile (const Image &image1, const Image &image2, const Image &image3, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Tile (const Image &image1, const Image &image2, const Image &image3, const Image &image4, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Tile (const Image &image1, const Image &image2, const Image &image3, const Image &image4, const Image &image5, std::vector< uint32_t > layout=std::vector< uint32_t >(3, 100), double defaultPixelValue=0.0)
Tile multiple input images into a single output image.
Image Toboggan (const Image &image1)
toboggan image segmentation The Toboggan segmentation takes a gradient magnitude image as input and produces an (over-)segmentation of the image based on connecting each pixel to a local minimum of gradient. It is roughly equivalent to a watershed segmentation of the lowest level.
Image TransformGeometry (Image &&image, const Transform &transform)
itk::simple::TransformGeometryImageFilter Procedural Interface
Image TransformGeometry (const Image &image, const Transform &transform)
itk::simple::TransformGeometryImageFilter Procedural Interface
Image TriangleThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Triangle Threshold.
Image TriangleThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Triangle Threshold.
Image UnaryMinus (Image &&image1)
Implements pixel-wise generic operation on one image.
Image UnaryMinus (const Image &image1)
Implements pixel-wise generic operation on one image.
Image UnsharpMask (const Image &image1, std::vector< double > sigmas=std::vector< double >(3, 1.0), double amount=0.5, double threshold=0.0)
Edge enhancement filter.
Image ValuedRegionalMaxima (const Image &image1, bool fullyConnected=false)
Transforms the image so that any pixel that is not a regional maxima is set to the minimum value for the pixel type. Pixels that are regional maxima retain their value.
Image ValuedRegionalMinima (const Image &image1, bool fullyConnected=false)
Transforms the image so that any pixel that is not a regional minima is set to the maximum value for the pixel type. Pixels that are regional minima retain their value.
Image VectorConfidenceConnected (const Image &image1, std::vector< std::vector< unsigned int > > seedList=std::vector< std::vector< unsigned int > >(), unsigned int numberOfIterations=4u, double multiplier=4.5, unsigned int initialNeighborhoodRadius=1u, uint8_t replaceValue=1u)
Segment pixels with similar statistics using connectivity.
Image VectorConnectedComponent (const Image &image1, double distanceThreshold=1.0, bool fullyConnected=false)
A connected components filter that labels the objects in a vector image. Two vectors are pointing similar directions if one minus their dot product is less than a threshold. Vectors that are 180 degrees out of phase are similar. Assumes that vectors are normalized.
Image VectorIndexSelectionCast (Image &&image1, unsigned int index=0u, PixelIDValueEnum outputPixelType=itk::simple::sitkUnknown)
Extracts the selected index of the vector that is the input pixel type.
Image VectorIndexSelectionCast (const Image &image1, unsigned int index=0u, PixelIDValueEnum outputPixelType=itk::simple::sitkUnknown)
Extracts the selected index of the vector that is the input pixel type.
Image VectorMagnitude (Image &&image1)
Take an image of vectors as input and produce an image with the magnitude of those vectors.
Image VectorMagnitude (const Image &image1)
Take an image of vectors as input and produce an image with the magnitude of those vectors.
Image VotingBinaryHoleFilling (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), unsigned int majorityThreshold=1u, double foregroundValue=1.0, double backgroundValue=0.0)
Fills in holes and cavities by applying a voting operation on each pixel.
Image VotingBinary (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), unsigned int birthThreshold=1u, unsigned int survivalThreshold=1u, double foregroundValue=1.0, double backgroundValue=0.0)
Applies a voting operation in a neighborhood of each pixel.
Image VotingBinaryIterativeHoleFilling (const Image &image1, std::vector< unsigned int > radius=std::vector< unsigned int >(3, 1), unsigned int maximumNumberOfIterations=10u, unsigned int majorityThreshold=1u, double foregroundValue=1.0, double backgroundValue=0.0)
Fills in holes and cavities by iteratively applying a voting operation.
Image Warp (const Image &image, const Image &displacementField, InterpolatorEnum interpolator=itk::simple::sitkLinear, std::vector< uint32_t > outputSize=std::vector< uint32_t >(3, 0), std::vector< double > outputOrigin=std::vector< double >(3, 0.0), std::vector< double > outputSpacing=std::vector< double >(3, 1.0), std::vector< double > outputDirection=std::vector< double >(), double edgePaddingValue=0.0)
Warps an image using an input displacement field.
Image WhiteTopHat (const Image &image1, std::vector< unsigned int > kernelRadius=std::vector< uint32_t >(3, 1), KernelEnum kernelType=itk::simple::sitkBall, bool safeBorder=true)
White top hat extracts local maxima that are larger than the structuring element.
Image WienerDeconvolution (const Image &image1, const Image &image2, double noiseVariance=0.0, bool normalize=false, WienerDeconvolutionImageFilter::BoundaryConditionType boundaryCondition=itk::simple::WienerDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, WienerDeconvolutionImageFilter::OutputRegionModeType outputRegionMode=itk::simple::WienerDeconvolutionImageFilter::SAME)
The Wiener deconvolution image filter is designed to restore an image convolved with a blurring kernel while keeping noise enhancement to a minimum.
Image WrapPad (const Image &image1, std::vector< unsigned int > padLowerBound=std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound=std::vector< unsigned int >(3, 0))
Increase the image size by padding with replicants of the input image value.
Image Xor (Image &&image1, const Image &image2)
Computes the XOR bitwise operator pixel-wise between two images.
Image Xor (const Image &image1, const Image &image2)
Computes the XOR bitwise operator pixel-wise between two images.
Image YenThreshold (const Image &image, const Image &maskImage, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Yen Threshold.
Image YenThreshold (const Image &image, uint8_t insideValue=1u, uint8_t outsideValue=0u, uint32_t numberOfHistogramBins=256u, bool maskOutput=true, uint8_t maskValue=255u)
Threshold an image using the Yen Threshold.
Image ZeroCrossingBasedEdgeDetection (const Image &image1, double variance=1.0, uint8_t foregroundValue=1u, uint8_t backgroundValue=0u, double maximumError=0.1)
This filter implements a zero-crossing based edge detecor.
Image ZeroCrossing (const Image &image1, uint8_t foregroundValue=1u, uint8_t backgroundValue=0u)
This filter finds the closest pixel to the zero-crossings (sign changes) in a signed itk::Image .
Image ZeroFluxNeumannPad (const Image &image1, std::vector< unsigned int > padLowerBound=std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound=std::vector< unsigned int >(3, 0))
Increase the image size by padding according to the zero-flux Neumann boundary condition.
Image Resample (const Image &image1, Transform transform=itk::simple::Transform(), InterpolatorEnum interpolator=itk::simple::sitkLinear, double defaultPixelValue=0.0, PixelIDValueEnum outputPixelType=sitkUnknown, bool useNearestNeighborExtrapolator=false)
itk::simple::ResampleImageFilter Procedural Interface
Image Resample (const Image &image1, const Image &referenceImage, Transform transform=itk::simple::Transform(), InterpolatorEnum interpolator=itk::simple::sitkLinear, double defaultPixelValue=0.0, PixelIDValueEnum outputPixelType=sitkUnknown, bool useNearestNeighborExtrapolator=false)
itk::simple::ResampleImageFilter Procedural Interface
Image Resample (const Image &image1, const std::vector< uint32_t > &size, Transform transform=itk::simple::Transform(), InterpolatorEnum interpolator=itk::simple::sitkLinear, const std::vector< double > &outputOrigin=std::vector< double >(3, 0.0), const std::vector< double > &outputSpacing=std::vector< double >(3, 1.0), const std::vector< double > &outputDirection=std::vector< double >(), double defaultPixelValue=0.0, PixelIDValueEnum outputPixelType=sitkUnknown, bool useNearestNeighborExtrapolator=false)
itk::simple::ResampleImageFilter Procedural Interface
Image Extract (Image &&image1, std::vector< unsigned int > size=std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > index=std::vector< int >(SITK_MAX_DIMENSION, 0), ExtractImageFilter::DirectionCollapseToStrategyType directionCollapseToStrategy=itk::simple::ExtractImageFilter::DIRECTIONCOLLAPSETOGUESS)
Decrease the image size by cropping the image to the selected region bounds.
Image Extract (const Image &image1, std::vector< unsigned int > size=std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > index=std::vector< int >(SITK_MAX_DIMENSION, 0), ExtractImageFilter::DirectionCollapseToStrategyType directionCollapseToStrategy=itk::simple::ExtractImageFilter::DIRECTIONCOLLAPSETOGUESS)
Decrease the image size by cropping the image to the selected region bounds.
Image operator+ (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator+ (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator+ (const Image &img, double s)
Performs the operator on a per pixel basis.
Image operator+ (Image &&img, double s)
Performs the operator on a per pixel basis.
Image operator+ (double s, const Image &img)
Performs the operator on a per pixel basis.
Image operator- (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator- (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator- (const Image &img, double s)
Performs the operator on a per pixel basis.
Image operator- (Image &&img, double s)
Performs the operator on a per pixel basis.
Image operator- (double s, const Image &img)
Performs the operator on a per pixel basis.
Image operator* (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator* (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator* (const Image &img, double s)
Performs the operator on a per pixel basis.
Image operator* (Image &&img, double s)
Performs the operator on a per pixel basis.
Image operator* (double s, const Image &img)
Performs the operator on a per pixel basis.
Image operator/ (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator/ (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator/ (const Image &img, double s)
Performs the operator on a per pixel basis.
Image operator/ (Image &&img, double s)
Performs the operator on a per pixel basis.
Image operator/ (double s, const Image &img)
Performs the operator on a per pixel basis.
Image operator% (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator% (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator% (const Image &img, uint32_t s)
Performs the operator on a per pixel basis.
Image operator% (Image &&img, uint32_t s)
Performs the operator on a per pixel basis.
Image operator% (uint32_t s, const Image &img)
Performs the operator on a per pixel basis.
Image operator- (const Image &img)
Performs the operator on a per pixel basis.
Image operator- (Image &&img)
Performs the operator on a per pixel basis.
Image operator~ (const Image &img)
Performs the operator on a per pixel basis.
Image operator~ (Image &&img)
Performs the operator on a per pixel basis.
Image operator& (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator& (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator& (const Image &img, int s)
Performs the operator on a per pixel basis.
Image operator& (Image &&img, int s)
Performs the operator on a per pixel basis.
Image operator& (int s, const Image &img)
Performs the operator on a per pixel basis.
Image operator| (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator| (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator| (const Image &img, int s)
Performs the operator on a per pixel basis.
Image operator| (Image &&img, int s)
Performs the operator on a per pixel basis.
Image operator| (int s, const Image &img)
Performs the operator on a per pixel basis.
Image operator^ (const Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator^ (Image &&img1, const Image &img2)
Performs the operator on a per pixel basis.
Image operator^ (const Image &img, int s)
Performs the operator on a per pixel basis.
Image operator^ (Image &&img, int s)
Performs the operator on a per pixel basis.
Image operator^ (int s, const Image &img)
Performs the operator on a per pixel basis.
Image & operator+= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator+= (Image &img1, double s)
Performs the operator on a per pixel basis.
Image & operator-= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator-= (Image &img1, double s)
Performs the operator on a per pixel basis.
Image & operator*= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator*= (Image &img1, double s)
Performs the operator on a per pixel basis.
Image & operator/= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator/= (Image &img1, double s)
Performs the operator on a per pixel basis.
Image & operator%= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator%= (Image &img1, uint32_t s)
Performs the operator on a per pixel basis.
Image & operator&= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator&= (Image &img1, int s)
Performs the operator on a per pixel basis.
Image & operator|= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator|= (Image &img1, int s)
Performs the operator on a per pixel basis.
Image & operator^= (Image &img1, const Image &img2)
Performs the operator on a per pixel basis.
Image & operator^= (Image &img1, int s)
Performs the operator on a per pixel basis.
Image Paste (Image &&destinationImage, const Image &sourceImage, std::vector< unsigned int > sourceSize=std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > sourceIndex=std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< int > destinationIndex=std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< bool > DestinationSkipAxes=std::vector< bool >())
Paste an image into another image.
Image Paste (const Image &destinationImage, const Image &sourceImage, std::vector< unsigned int > sourceSize=std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > sourceIndex=std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< int > destinationIndex=std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< bool > DestinationSkipAxes=std::vector< bool >())
Paste an image into another image.
Typedef Documentation
AllPixelIDTypeList
typedef typelist::Append<typelist::Append<BasicPixelIDTypeList,ComplexPixelIDTypeList>::Type,typelist::Append<VectorPixelIDTypeList,LabelPixelIDTypeList>::Type>::Type itk::simple::AllPixelIDTypeList
List of all pixel ids available, this include image of itk::Image, itk::VectorImage, and itk::LabelMap types.
Todo:
This needs to be extended to include LabelMap pixel ids.
See also
BasicPixelID
VectorPixelID
LabelPixelID
Definition at line 198 of file sitkPixelIDTypeLists.h.
BasicPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<int8_t>,BasicPixelID<uint8_t>,BasicPixelID<int16_t>,BasicPixelID<uint16_t>,BasicPixelID<int32_t>,BasicPixelID<uint32_t>,BasicPixelID<float>,BasicPixelID<double>>::Type itk::simple::BasicPixelIDTypeList
List of all pixel ids for the itk::Image class.
Todo:
address vnl issues with long long types
See also
BasicPixelID
Definition at line 53 of file sitkPixelIDTypeLists.h.
ComplexPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<std::complex<float>>,BasicPixelID<std::complex<double>>>::Type itk::simple::ComplexPixelIDTypeList
List of pixel ids which are std::complex types for the itk::Image class.
See also
BasicPixelID
Definition at line 106 of file sitkPixelIDTypeLists.h.
FalseType
using itk::simple::FalseType = typedef std::false_type
Definition at line 32 of file sitkPixelIDTokens.h.
InstantiatedPixelIDTypeList
using itk::simple::InstantiatedPixelIDTypeList = typedef AllPixelIDTypeList
List of pixel ids which are instantiated for use in SimpleITK
this include image of itk::Image,itk::VectorImage, and itk::LabelMap types.
See also
BasicPixelID
VectorPixelID
LabelPixelID
Definition at line 210 of file sitkPixelIDTypeLists.h.
IntegerLabelPixelIDTypeList
using itk::simple::IntegerLabelPixelIDTypeList = typedef UnsignedIntegerPixelIDTypeList
Definition at line 170 of file sitkPixelIDTypeLists.h.
IntegerPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<int8_t>,BasicPixelID<uint8_t>,BasicPixelID<int16_t>,BasicPixelID<uint16_t>,BasicPixelID<int32_t>,BasicPixelID<uint32_t>>::Type itk::simple::IntegerPixelIDTypeList
List of pixel ids which are integer types for the itk::Image class.
See also
BasicPixelID
Definition at line 76 of file sitkPixelIDTypeLists.h.
LabelPixelIDTypeList
typedef typelist::MakeTypeList<LabelPixelID<uint8_t>,LabelPixelID<uint16_t>,LabelPixelID<uint32_t>>::Type itk::simple::LabelPixelIDTypeList
List of pixel ids which are for itk::LabelMap Image class.
See also
LabelPixelID
Definition at line 168 of file sitkPixelIDTypeLists.h.
MaskedPixelIDTypeList
using itk::simple::MaskedPixelIDTypeList = typedef typelist::MakeTypeList<BasicPixelID<uint8_t> >::Type
The conventional type used for a mask image as a list
Definition at line 91 of file sitkPixelIDTypeLists.h.
NonLabelPixelIDTypeList
typedef typelist::Append<typelist::Append<BasicPixelIDTypeList,ComplexPixelIDTypeList>::Type,VectorPixelIDTypeList>::Type itk::simple::NonLabelPixelIDTypeList
List of all pixel ids available, but itk::LabelMap this include image of itk::Image, itk::VectorImage
See also
BasicPixelID
VectorPixelID
LabelPixelID
Definition at line 183 of file sitkPixelIDTypeLists.h.
PixelIDValueType
using itk::simple::PixelIDValueType = typedef int
Definition at line 32 of file sitkPixelIDValues.h.
RealPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<float>,BasicPixelID<double>>::Type itk::simple::RealPixelIDTypeList
List of pixel ids which are real types for the itk::Image class.
See also
BasicPixelID
Definition at line 99 of file sitkPixelIDTypeLists.h.
RealVectorPixelIDTypeList
typedef typelist::MakeTypeList<VectorPixelID<float>,VectorPixelID<double>>::Type itk::simple::RealVectorPixelIDTypeList
List of pixel ids which are real vectors for itk::VectorImage class.
See also
VectorPixelID
Definition at line 145 of file sitkPixelIDTypeLists.h.
ScalarPixelIDTypeList
using itk::simple::ScalarPixelIDTypeList = typedef BasicPixelIDTypeList
List of all single valued images of the itk::Image class.
See also
BasicPixelID
Definition at line 59 of file sitkPixelIDTypeLists.h.
SignedPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<int8_t>,BasicPixelID<int16_t>,BasicPixelID<int32_t>,BasicPixelID<float>,BasicPixelID<double>>::Type itk::simple::SignedPixelIDTypeList
List of pixel ids which are signed
See also
BasicPixelID
Definition at line 119 of file sitkPixelIDTypeLists.h.
SignedVectorPixelIDTypeList
typedef typelist::MakeTypeList<VectorPixelID<int8_t>,VectorPixelID<int16_t>,VectorPixelID<int32_t>,VectorPixelID<float>,VectorPixelID<double>>::Type itk::simple::SignedVectorPixelIDTypeList
List of pixel ids which are signed of vectors
See also
BasicPixelID
Definition at line 155 of file sitkPixelIDTypeLists.h.
TrueType
using itk::simple::TrueType = typedef std::true_type
Definition at line 31 of file sitkPixelIDTokens.h.
UnsignedIntegerPixelIDTypeList
typedef typelist::MakeTypeList<BasicPixelID<uint8_t>,BasicPixelID<uint16_t>,BasicPixelID<uint32_t>>::Type itk::simple::UnsignedIntegerPixelIDTypeList
List of pixel ids which are unsigned integer types for the itk::Image class.
See also
BasicPixelID
Definition at line 88 of file sitkPixelIDTypeLists.h.
VectorPixelIDTypeList
typedef typelist::MakeTypeList<VectorPixelID<int8_t>,VectorPixelID<uint8_t>,VectorPixelID<int16_t>,VectorPixelID<uint16_t>,VectorPixelID<int32_t>,VectorPixelID<uint32_t>,VectorPixelID<float>,VectorPixelID<double>>::Type itk::simple::VectorPixelIDTypeList
List of pixel ids which are vectors for itk::VectorImage class.
See also
VectorPixelID
Definition at line 137 of file sitkPixelIDTypeLists.h.
Enumeration Type Documentation
EventEnum
enum itk::simple::EventEnum
Events which can be observed from ProcessObject.
For more information see the page CommandPage.
Enumerator
sitkAnyEvent
Occurs for all event types.
sitkAbortEvent
Occurs after the process has been aborted, but before exiting the Execute method.
sitkDeleteEvent
Occurs when the underlying itk::ProcessObject is deleted.
sitkEndEvent
Occurs at then end of normal processing.
sitkIterationEvent
Occurs with some algorithms that run for a fixed or undetermined number of iterations.
sitkProgressEvent
Occurs when the progress changes in most process objects.
sitkStartEvent
Occurs when then itk::ProcessObject is starting.
sitkMultiResolutionIterationEvent
Occurs when some filters change processing to a different scale.
Note
This event is a sub-event of the more general IterationEvent. The general iteration event will also be invoked.
sitkUserEvent
Other events may fall into this enumeration.
Examples
FilterProgressReporting/FilterProgressReporting.cs, FilterProgressReporting/FilterProgressReporting.java, ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.java, and ImageRegistrationMethod2/ImageRegistrationMethod2.cs.
Definition at line 31 of file sitkEvent.h.
InterpolatorEnum
enum itk::simple::InterpolatorEnum
Enumerator
sitkNearestNeighbor
Nearest-neighbor interpolation.
See also
itk::NearestNeighborInterpolateImageFunction
sitkLinear
N-D linear interpolation.
See also
itk::LinearInterpolateImageFunction
sitkBSpline1
B-Spline of order 1 interpolation.
See also
itk::BSplineInterpolateImageFunction
sitkBSpline2
B-Spline of order 2 interpolation.
See also
itk::BSplineInterpolateImageFunction
sitkBSpline
B-Spline of order 3 interpolation.
See also
itk::BSplineInterpolateImageFunction
sitkBSpline3
sitkBSpline4
B-Spline of order 4 interpolation.
See also
itk::BSplineInterpolateImageFunction
sitkBSpline5
B-Spline of order 5 interpolation.
See also
itk::BSplineInterpolateImageFunction
sitkGaussian
Gaussian interpolation.
Sigma is set to 0.8 input pixels and alpha is 4.0
See also
itk::GaussianInterpolateImageFunction
sitkLabelGaussian
Smoothly interpolate multi-label images.
Sigma is set to 1.0 input pixels and alpha is 1.0
See also
itk:LabelImageGaussianInterpolateImageFunction
sitkHammingWindowedSinc
Windowed sinc interpolation.
\[ w(x) = 0.54 + 0.46 cos(\frac{\pi x}{m}) \]
See also
itk::WindowedSincInterpolateImageFunction
itk::Function::HammingWindowFunction
sitkCosineWindowedSinc
Windowed sinc interpolation.
\[ w(x) = cos(\frac{\pi x}{2 m}) \]
See also
itk::WindowedSincInterpolateImageFunction
itk::Function::CosineWindowFunction
sitkWelchWindowedSinc
Windowed sinc interpolation.
\[ w(x) = 1 - (\frac{x^2}{m^2}) \]
See also
itk::WindowedSincInterpolateImageFunction
itk::Function::WelchWindowFunction
sitkLanczosWindowedSinc
Windowed sinc interpolation.
\[ w(x) = \textrm{sinc} (\frac{x}{m}) \]
See also
itk::WindowedSincInterpolateImageFunction
itk::Function::LanczosWindowFunction
sitkBlackmanWindowedSinc
Windowed sinc interpolation.
\[ w(x) = 0.42 + 0.5 cos(\frac{\pi x}{m}) + 0.08 cos(\frac{2 \pi x}{m}) \]
See also
itk::WindowedSincInterpolateImageFunction
itk::Function::BlackmanWindowFunction
sitkBSplineResampler
Interpolator for a BSpline coefficient image
This interpolator should be used with the resampling the image intensities of a BSpline coefficient image. The order specifies the order of the coefficient image, and defaults to 3.
See also
BSplineTransformation
itk::BSplineResampleImageFunction
sitkBSplineResamplerOrder3
Interpolator for a BSpline coefficient image, order 3.
sitkBSplineResamplerOrder1
Interpolator for a BSpline coefficient image, order 1.
sitkBSplineResamplerOrder2
Interpolator for a BSpline coefficient image, order 2.
sitkBSplineResamplerOrder4
Interpolator for a BSpline coefficient image, order 4.
sitkBSplineResamplerOrder5
Interpolator for a BSpline coefficient image, order 5.
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.java, and ImageRegistrationMethod2/ImageRegistrationMethod2.cs.
Definition at line 30 of file sitkInterpolator.h.
KernelEnum
enum itk::simple::KernelEnum
Enumerator
sitkAnnulus
sitkBall
sitkBox
sitkCross
sitkPolygon3
sitkPolygon4
sitkPolygon5
sitkPolygon6
sitkPolygon7
sitkPolygon8
sitkPolygon9
Definition at line 29 of file sitkKernel.h.
PixelIDValueEnum
enum itk::simple::PixelIDValueEnum
Enumerated values of pixelIDs.
Each PixelID's value corresponds to the index of the PixelID type, in the type list "InstantiatedPixelIDTypeList". It is possible that different configurations for SimpleITK could result in different values for pixelID. So these enumerated values should be used.
Additionally, not all PixelID an instantiated in for the tool kit. If a PixelID is not instantiated then it's value is -1. Therefore it is likely that multiple elements in the enumeration will have a zero value. Therefore the first preferred method is to use "if" statements, with the first branch checking for the Unknown value.
If a switch case statement is needed the ConditionalValue meta-programming object can be used as follows:
switch(pixelIDValue)
   {
 case sitk::sitkUnknown:
   // handle exceptional case
   break
 case sitk::ConditionalValue< sitk::sitkUInt8 != sitk::sitkUnknown, sitk::sitkUInt8, -2 >::Value:
   ...
   break;
 case sitk::ConditionalValue< sitk::sitkInt8 != sitk::sitkUnknown, sitk::sitkInt8, -3 >::Value:
   ...
   break;
 case sitk::ConditionalValue< sitk::N != sitk::sitkUnknown, sitk::N, -N >::Value:
   ...
   break;
 default:
    // handle another exceptional case
   }
Enumerator
sitkUnknown
sitkUInt8
Unsigned 8 bit integer.
sitkInt8
Signed 8 bit integer.
sitkUInt16
Unsigned 16 bit integer.
sitkInt16
Signed 16 bit integer.
sitkUInt32
Unsigned 32 bit integer.
sitkInt32
Signed 32 bit integer.
sitkUInt64
Unsigned 64 bit integer.
sitkInt64
Signed 64 bit integer.
sitkFloat32
32 bit float
sitkFloat64
64 bit float
sitkComplexFloat32
complex number of 32 bit float
sitkComplexFloat64
complex number of 64 bit float
sitkVectorUInt8
Multi-component of unsigned 8 bit integer.
sitkVectorInt8
Multi-component of signed 8 bit integer.
sitkVectorUInt16
Multi-component of unsigned 16 bit integer.
sitkVectorInt16
Multi-component of signed 16 bit integer.
sitkVectorUInt32
Multi-component of unsigned 32 bit integer.
sitkVectorInt32
Multi-component of signed 32 bit integer.
sitkVectorUInt64
Multi-component of unsigned 64 bit integer.
sitkVectorInt64
Multi-component of signed 64 bit integer.
sitkVectorFloat32
Multi-component of 32 bit float.
sitkVectorFloat64
Multi-component of 64 bit float.
sitkLabelUInt8
RLE label of unsigned 8 bit integers.
sitkLabelUInt16
RLE label of unsigned 16 bit integers.
sitkLabelUInt32
RLE label of unsigned 32 bit integers.
sitkLabelUInt64
RLE label of unsigned 64 bit integers.
Examples
CSharp/CannySegmentationLevelSetImageFilter.cs, CSharp/ConnectedThresholdSegmentation.cs, FastMarchingSegmentation/FastMarchingSegmentation.cs, HelloWorld/HelloWorld.cs, HelloWorld/HelloWorld.java, ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.java, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, Java/ImageGetSetBuffer.java, N4BiasFieldCorrection/N4BiasFieldCorrection.cs, SimpleIO/SimpleIO.cs, and SimpleIO/SimpleIO.java.
Definition at line 90 of file sitkPixelIDValues.h.
SeedEnum
enum itk::simple::SeedEnum
Enumerator
sitkWallClock
A sentinel value used for "seed" parameters to indicate it should be initialized by the wall clock for pseudo-random behavior.
Definition at line 28 of file sitkRandomSeed.h.
TransformEnum
enum itk::simple::TransformEnum
Enumerator
sitkUnknownTransform
sitkIdentity
sitkTranslation
sitkScale
sitkScaleLogarithmic
sitkEuler
sitkSimilarity
sitkQuaternionRigid
sitkVersor
sitkVersorRigid
sitkScaleSkewVersor
sitkComposeScaleSkewVersor
sitkScaleVersor
sitkAffine
sitkComposite
sitkDisplacementField
sitkBSplineTransform
Definition at line 43 of file sitkTransform.h.
Function Documentation
Abs() [1/2]
Image itk::simple::Abs (const Image & image1)
Computes the absolute value of each pixel.
\
This function directly calls the execute method of AbsImageFilter in order to support a procedural API
See also
itk::simple::AbsImageFilter for the object oriented interface
Abs() [2/2]
Image itk::simple::Abs (Image && image1)
Computes the absolute value of each pixel.
\
This function directly calls the execute method of AbsImageFilter in order to support a procedural API
See also
itk::simple::AbsImageFilter for the object oriented interface
AbsoluteValueDifference() [1/5]
Image itk::simple::AbsoluteValueDifference (const Image & image1, const Image & image2)
Implements pixel-wise the computation of absolute value difference.
\
This function directly calls the execute method of AbsoluteValueDifferenceImageFilter in order to support a procedural API
See also
itk::simple::AbsoluteValueDifferenceImageFilter for the object oriented interface
AbsoluteValueDifference() [2/5]
Image itk::simple::AbsoluteValueDifference (const Image & image1, double constant)
AbsoluteValueDifference() [3/5]
Image itk::simple::AbsoluteValueDifference (double constant, const Image & image2)
AbsoluteValueDifference() [4/5]
Image itk::simple::AbsoluteValueDifference (Image && image1, const Image & image2)
Implements pixel-wise the computation of absolute value difference.
\
This function directly calls the execute method of AbsoluteValueDifferenceImageFilter in order to support a procedural API
See also
itk::simple::AbsoluteValueDifferenceImageFilter for the object oriented interface
AbsoluteValueDifference() [5/5]
Image itk::simple::AbsoluteValueDifference (Image && image1, double constant)
Acos() [1/2]
Image itk::simple::Acos (const Image & image1)
Computes the inverse cosine of each pixel.
\
This function directly calls the execute method of AcosImageFilter in order to support a procedural API
See also
itk::simple::AcosImageFilter for the object oriented interface
Acos() [2/2]
Image itk::simple::Acos (Image && image1)
Computes the inverse cosine of each pixel.
\
This function directly calls the execute method of AcosImageFilter in order to support a procedural API
See also
itk::simple::AcosImageFilter for the object oriented interface
AdaptiveHistogramEqualization()
Image itk::simple::AdaptiveHistogramEqualization (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 5), float alpha = 0.3f, float beta = 0.3f)
Power Law Adaptive Histogram Equalization.
\
This function directly calls the execute method of AdaptiveHistogramEqualizationImageFilter in order to support a procedural API
See also
itk::simple::AdaptiveHistogramEqualizationImageFilter for the object oriented interface
Examples
SliceBySliceDecorator/SliceBySliceDecorator.cxx.
Add() [1/5]
Image itk::simple::Add (const Image & image1, const Image & image2)
Pixel-wise addition of two images.
\
This function directly calls the execute method of AddImageFilter in order to support a procedural API
See also
itk::simple::AddImageFilter for the object oriented interface
Add() [2/5]
Image itk::simple::Add (const Image & image1, double constant)
Add() [3/5]
Image itk::simple::Add (double constant, const Image & image2)
Add() [4/5]
Image itk::simple::Add (Image && image1, const Image & image2)
Pixel-wise addition of two images.
\
This function directly calls the execute method of AddImageFilter in order to support a procedural API
See also
itk::simple::AddImageFilter for the object oriented interface
Referenced by operator+(), and operator+=().
Add() [5/5]
Image itk::simple::Add (Image && image1, double constant)
AdditiveGaussianNoise() [1/2]
Image itk::simple::AdditiveGaussianNoise (const Image & image1, double standardDeviation = 1.0, double mean = 0.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with additive Gaussian white noise.
\
This function directly calls the execute method of AdditiveGaussianNoiseImageFilter in order to support a procedural API
See also
itk::simple::AdditiveGaussianNoiseImageFilter for the object oriented interface
AdditiveGaussianNoise() [2/2]
Image itk::simple::AdditiveGaussianNoise (Image && image1, double standardDeviation = 1.0, double mean = 0.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with additive Gaussian white noise.
\
This function directly calls the execute method of AdditiveGaussianNoiseImageFilter in order to support a procedural API
See also
itk::simple::AdditiveGaussianNoiseImageFilter for the object oriented interface
AggregateLabelMap() [1/2]
Image itk::simple::AggregateLabelMap (const Image & image1)
Collapses all labels into the first label.
\
This function directly calls the execute method of AggregateLabelMapFilter in order to support a procedural API
See also
itk::simple::AggregateLabelMapFilter for the object oriented interface
AggregateLabelMap() [2/2]
Image itk::simple::AggregateLabelMap (Image && image1)
Collapses all labels into the first label.
\
This function directly calls the execute method of AggregateLabelMapFilter in order to support a procedural API
See also
itk::simple::AggregateLabelMapFilter for the object oriented interface
And() [1/5]
Image itk::simple::And (const Image & image1, const Image & image2)
Implements the AND bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of AndImageFilter in order to support a procedural API
See also
itk::simple::AndImageFilter for the object oriented interface
And() [2/5]
Image itk::simple::And (const Image & image1, int constant)
And() [3/5]
Image itk::simple::And (Image && image1, const Image & image2)
Implements the AND bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of AndImageFilter in order to support a procedural API
See also
itk::simple::AndImageFilter for the object oriented interface
Referenced by operator&(), and operator&=().
And() [4/5]
Image itk::simple::And (Image && image1, int constant)
And() [5/5]
Image itk::simple::And (int constant, const Image & image2)
AntiAliasBinary() [1/2]
Image itk::simple::AntiAliasBinary (const Image & image1, double maximumRMSError = 0.07, uint32_t numberOfIterations = 1000u)
A method for estimation of a surface from a binary volume.
\
This function directly calls the execute method of AntiAliasBinaryImageFilter in order to support a procedural API
See also
itk::simple::AntiAliasBinaryImageFilter for the object oriented interface
AntiAliasBinary() [2/2]
Image itk::simple::AntiAliasBinary (Image && image1, double maximumRMSError = 0.07, uint32_t numberOfIterations = 1000u)
A method for estimation of a surface from a binary volume.
\
This function directly calls the execute method of AntiAliasBinaryImageFilter in order to support a procedural API
See also
itk::simple::AntiAliasBinaryImageFilter for the object oriented interface
ApproximateSignedDistanceMap()
Image itk::simple::ApproximateSignedDistanceMap (const Image & image1, double insideValue = 1u, double outsideValue = 0u)
Create a map of the approximate signed distance from the boundaries of a binary image.
\
This function directly calls the execute method of ApproximateSignedDistanceMapImageFilter in order to support a procedural API
See also
itk::simple::ApproximateSignedDistanceMapImageFilter for the object oriented interface
Asin() [1/2]
Image itk::simple::Asin (const Image & image1)
Computes the sine of each pixel.
\
This function directly calls the execute method of AsinImageFilter in order to support a procedural API
See also
itk::simple::AsinImageFilter for the object oriented interface
Asin() [2/2]
Image itk::simple::Asin (Image && image1)
Computes the sine of each pixel.
\
This function directly calls the execute method of AsinImageFilter in order to support a procedural API
See also
itk::simple::AsinImageFilter for the object oriented interface
Atan() [1/2]
Image itk::simple::Atan (const Image & image1)
Computes the one-argument inverse tangent of each pixel.
\
This function directly calls the execute method of AtanImageFilter in order to support a procedural API
See also
itk::simple::AtanImageFilter for the object oriented interface
Atan() [2/2]
Image itk::simple::Atan (Image && image1)
Computes the one-argument inverse tangent of each pixel.
\
This function directly calls the execute method of AtanImageFilter in order to support a procedural API
See also
itk::simple::AtanImageFilter for the object oriented interface
Atan2() [1/5]
Image itk::simple::Atan2 (const Image & image1, const Image & image2)
Computes two argument inverse tangent.
\
This function directly calls the execute method of Atan2ImageFilter in order to support a procedural API
See also
itk::simple::Atan2ImageFilter for the object oriented interface
Atan2() [2/5]
Image itk::simple::Atan2 (const Image & image1, double constant)
Atan2() [3/5]
Image itk::simple::Atan2 (double constant, const Image & image2)
Atan2() [4/5]
Image itk::simple::Atan2 (Image && image1, const Image & image2)
Computes two argument inverse tangent.
\
This function directly calls the execute method of Atan2ImageFilter in order to support a procedural API
See also
itk::simple::Atan2ImageFilter for the object oriented interface
Atan2() [5/5]
Image itk::simple::Atan2 (Image && image1, double constant)
Bilateral()
Image itk::simple::Bilateral (const Image & image1, double domainSigma = 4.0, double rangeSigma = 50.0, unsigned int numberOfRangeGaussianSamples = 100u)
Blurs an image while preserving edges.
\
This function directly calls the execute method of BilateralImageFilter in order to support a procedural API
See also
itk::simple::BilateralImageFilter for the object oriented interface
BinaryClosingByReconstruction()
Image itk::simple::BinaryClosingByReconstruction (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double foregroundValue = 1.0, bool fullyConnected = false)
binary closing by reconstruction of an image.
\
This function directly calls the execute method of BinaryClosingByReconstructionImageFilter in order to support a procedural API
See also
itk::simple::BinaryClosingByReconstructionImageFilter for the object oriented interface
BinaryContour() [1/2]
Image itk::simple::BinaryContour (const Image & image1, bool fullyConnected = false, double backgroundValue = 0.0, double foregroundValue = 1.0)
Labels the pixels on the border of the objects in a binary image.
\
This function directly calls the execute method of BinaryContourImageFilter in order to support a procedural API
See also
itk::simple::BinaryContourImageFilter for the object oriented interface
BinaryContour() [2/2]
Image itk::simple::BinaryContour (Image && image1, bool fullyConnected = false, double backgroundValue = 0.0, double foregroundValue = 1.0)
Labels the pixels on the border of the objects in a binary image.
\
This function directly calls the execute method of BinaryContourImageFilter in order to support a procedural API
See also
itk::simple::BinaryContourImageFilter for the object oriented interface
BinaryDilate()
Image itk::simple::BinaryDilate (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double backgroundValue = 0.0, double foregroundValue = 1.0, bool boundaryToForeground = false)
Fast binary dilation of a single intensity value in the image.
\
This function directly calls the execute method of BinaryDilateImageFilter in order to support a procedural API
See also
itk::simple::BinaryDilateImageFilter for the object oriented interface
BinaryErode()
Image itk::simple::BinaryErode (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double backgroundValue = 0.0, double foregroundValue = 1.0, bool boundaryToForeground = true)
Fast binary erosion of a single intensity value in the image.
\
This function directly calls the execute method of BinaryErodeImageFilter in order to support a procedural API
See also
itk::simple::BinaryErodeImageFilter for the object oriented interface
BinaryFillhole()
Image itk::simple::BinaryFillhole (const Image & image1, bool fullyConnected = false, double foregroundValue = 1.0)
Remove holes not connected to the boundary of the image.
\
This function directly calls the execute method of BinaryFillholeImageFilter in order to support a procedural API
See also
itk::simple::BinaryFillholeImageFilter for the object oriented interface
BinaryGrindPeak()
Image itk::simple::BinaryGrindPeak (const Image & image1, bool fullyConnected = false, double foregroundValue = 1.0, double backgroundValue = 0)
Remove the objects not connected to the boundary of the image.
\
This function directly calls the execute method of BinaryGrindPeakImageFilter in order to support a procedural API
See also
itk::simple::BinaryGrindPeakImageFilter for the object oriented interface
BinaryImageToLabelMap()
Image itk::simple::BinaryImageToLabelMap (const Image & image1, bool fullyConnected = false, double inputForegroundValue = 1.0, double outputBackgroundValue = 0.0)
Label the connected components in a binary image and produce a collection of label objects.
\
This function directly calls the execute method of BinaryImageToLabelMapFilter in order to support a procedural API
See also
itk::simple::BinaryImageToLabelMapFilter for the object oriented interface
BinaryMagnitude() [1/2]
Image itk::simple::BinaryMagnitude (const Image & image1, const Image & image2)
Computes the square root of the sum of squares of corresponding input pixels.
\
This function directly calls the execute method of BinaryMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::BinaryMagnitudeImageFilter for the object oriented interface
BinaryMagnitude() [2/2]
Image itk::simple::BinaryMagnitude (Image && image1, const Image & image2)
Computes the square root of the sum of squares of corresponding input pixels.
\
This function directly calls the execute method of BinaryMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::BinaryMagnitudeImageFilter for the object oriented interface
BinaryMedian()
Image itk::simple::BinaryMedian (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), double foregroundValue = 1.0, double backgroundValue = 0.0)
Applies a version of the median filter optimized for binary images.
\
This function directly calls the execute method of BinaryMedianImageFilter in order to support a procedural API
See also
itk::simple::BinaryMedianImageFilter for the object oriented interface
BinaryMinMaxCurvatureFlow() [1/2]
Image itk::simple::BinaryMinMaxCurvatureFlow (const Image & image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u, int stencilRadius = 2, double threshold = 0.0)
Denoise a binary image using min/max curvature flow.
\
This function directly calls the execute method of BinaryMinMaxCurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::BinaryMinMaxCurvatureFlowImageFilter for the object oriented interface
BinaryMinMaxCurvatureFlow() [2/2]
Image itk::simple::BinaryMinMaxCurvatureFlow (Image && image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u, int stencilRadius = 2, double threshold = 0.0)
Denoise a binary image using min/max curvature flow.
\
This function directly calls the execute method of BinaryMinMaxCurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::BinaryMinMaxCurvatureFlowImageFilter for the object oriented interface
BinaryMorphologicalClosing()
Image itk::simple::BinaryMorphologicalClosing (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double foregroundValue = 1.0, bool safeBorder = true)
binary morphological closing of an image.
\
This function directly calls the execute method of BinaryMorphologicalClosingImageFilter in order to support a procedural API
See also
itk::simple::BinaryMorphologicalClosingImageFilter for the object oriented interface
BinaryMorphologicalOpening()
Image itk::simple::BinaryMorphologicalOpening (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double backgroundValue = 0.0, double foregroundValue = 1.0)
binary morphological opening of an image.
\
This function directly calls the execute method of BinaryMorphologicalOpeningImageFilter in order to support a procedural API
See also
itk::simple::BinaryMorphologicalOpeningImageFilter for the object oriented interface
BinaryNot() [1/2]
Image itk::simple::BinaryNot (const Image & image1, double foregroundValue = 1.0, double backgroundValue = 0.0)
Implements the BinaryNot logical operator pixel-wise between two images.
\
This function directly calls the execute method of BinaryNotImageFilter in order to support a procedural API
See also
itk::simple::BinaryNotImageFilter for the object oriented interface
BinaryNot() [2/2]
Image itk::simple::BinaryNot (Image && image1, double foregroundValue = 1.0, double backgroundValue = 0.0)
Implements the BinaryNot logical operator pixel-wise between two images.
\
This function directly calls the execute method of BinaryNotImageFilter in order to support a procedural API
See also
itk::simple::BinaryNotImageFilter for the object oriented interface
BinaryOpeningByReconstruction()
Image itk::simple::BinaryOpeningByReconstruction (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double foregroundValue = 1.0, double backgroundValue = 0.0, bool fullyConnected = false)
binary morphological closing of an image.
\
This function directly calls the execute method of BinaryOpeningByReconstructionImageFilter in order to support a procedural API
See also
itk::simple::BinaryOpeningByReconstructionImageFilter for the object oriented interface
BinaryProjection()
Image itk::simple::BinaryProjection (const Image & image1, unsigned int projectionDimension = 0u, double foregroundValue = 1.0, double backgroundValue = 0.0)
Binary projection.
\
This function directly calls the execute method of BinaryProjectionImageFilter in order to support a procedural API
See also
itk::simple::BinaryProjectionImageFilter for the object oriented interface
BinaryPruning()
Image itk::simple::BinaryPruning (const Image & image1, uint32_t iteration = 3u)
This filter removes "spurs" of less than a certain length in the input image.
\
This function directly calls the execute method of BinaryPruningImageFilter in order to support a procedural API
See also
itk::simple::BinaryPruningImageFilter for the object oriented interface
BinaryReconstructionByDilation()
Image itk::simple::BinaryReconstructionByDilation (const Image & markerImage, const Image & maskImage, double backgroundValue = 0.0, double foregroundValue = 1.0, bool fullyConnected = false)
binary reconstruction by dilation of an image
\
This function directly calls the execute method of BinaryReconstructionByDilationImageFilter in order to support a procedural API
See also
itk::simple::BinaryReconstructionByDilationImageFilter for the object oriented interface
BinaryReconstructionByErosion()
Image itk::simple::BinaryReconstructionByErosion (const Image & markerImage, const Image & maskImage, double backgroundValue = 0.0, double foregroundValue = 1.0, bool fullyConnected = false)
binary reconstruction by erosion of an image
\
This function directly calls the execute method of BinaryReconstructionByErosionImageFilter in order to support a procedural API
See also
itk::simple::BinaryReconstructionByErosionImageFilter for the object oriented interface
BinaryThinning()
Image itk::simple::BinaryThinning (const Image & image1)
This filter computes one-pixel-wide edges of the input image.
\
This function directly calls the execute method of BinaryThinningImageFilter in order to support a procedural API
See also
itk::simple::BinaryThinningImageFilter for the object oriented interface
BinaryThreshold() [1/2]
Image itk::simple::BinaryThreshold (const Image & image1, double lowerThreshold = 0.0, double upperThreshold = 255.0, uint8_t insideValue = 1u, uint8_t outsideValue = 0u)
Binarize an input image by thresholding.
\
This function directly calls the execute method of BinaryThresholdImageFilter in order to support a procedural API
See also
itk::simple::BinaryThresholdImageFilter for the object oriented interface
BinaryThreshold() [2/2]
Image itk::simple::BinaryThreshold (Image && image1, double lowerThreshold = 0.0, double upperThreshold = 255.0, uint8_t insideValue = 1u, uint8_t outsideValue = 0u)
Binarize an input image by thresholding.
\
This function directly calls the execute method of BinaryThresholdImageFilter in order to support a procedural API
See also
itk::simple::BinaryThresholdImageFilter for the object oriented interface
Examples
HelloWorld/HelloWorld.cxx.
BinaryThresholdProjection()
Image itk::simple::BinaryThresholdProjection (const Image & image1, unsigned int projectionDimension = 0u, double thresholdValue = 0.0, uint8_t foregroundValue = 1u, uint8_t backgroundValue = 0u)
BinaryThreshold projection.
\
This function directly calls the execute method of BinaryThresholdProjectionImageFilter in order to support a procedural API
See also
itk::simple::BinaryThresholdProjectionImageFilter for the object oriented interface
BinomialBlur()
Image itk::simple::BinomialBlur (const Image & image1, unsigned int repetitions = 1u)
Performs a separable blur on each dimension of an image.
\
This function directly calls the execute method of BinomialBlurImageFilter in order to support a procedural API
See also
itk::simple::BinomialBlurImageFilter for the object oriented interface
BinShrink()
Image itk::simple::BinShrink (const Image & image1, std::vector< unsigned int > shrinkFactors = std::vector< unsigned int >(3, 1))
Reduce the size of an image by an integer factor in each dimension while performing averaging of an input neighborhood.
\
This function directly calls the execute method of BinShrinkImageFilter in order to support a procedural API
See also
itk::simple::BinShrinkImageFilter for the object oriented interface
BitwiseNot() [1/2]
Image itk::simple::BitwiseNot (const Image & image1)
Implements pixel-wise generic operation on one image.
\
This function directly calls the execute method of BitwiseNotImageFilter in order to support a procedural API
See also
itk::simple::BitwiseNotImageFilter for the object oriented interface
BitwiseNot() [2/2]
Image itk::simple::BitwiseNot (Image && image1)
Implements pixel-wise generic operation on one image.
\
This function directly calls the execute method of BitwiseNotImageFilter in order to support a procedural API
See also
itk::simple::BitwiseNotImageFilter for the object oriented interface
Referenced by operator~().
BlackTopHat()
Image itk::simple::BlackTopHat (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool safeBorder = true)
Black top hat extracts local minima that are smaller than the structuring element.
\
This function directly calls the execute method of BlackTopHatImageFilter in order to support a procedural API
See also
itk::simple::BlackTopHatImageFilter for the object oriented interface
BoundedReciprocal() [1/2]
Image itk::simple::BoundedReciprocal (const Image & image1)
Computes 1/(1+x) for each pixel in the image.
\
This function directly calls the execute method of BoundedReciprocalImageFilter in order to support a procedural API
See also
itk::simple::BoundedReciprocalImageFilter for the object oriented interface
BoundedReciprocal() [2/2]
Image itk::simple::BoundedReciprocal (Image && image1)
Computes 1/(1+x) for each pixel in the image.
\
This function directly calls the execute method of BoundedReciprocalImageFilter in order to support a procedural API
See also
itk::simple::BoundedReciprocalImageFilter for the object oriented interface
BoxMean()
Image itk::simple::BoxMean (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Implements a fast rectangular mean filter using the accumulator approach.
\
This function directly calls the execute method of BoxMeanImageFilter in order to support a procedural API
See also
itk::simple::BoxMeanImageFilter for the object oriented interface
BoxSigma()
Image itk::simple::BoxSigma (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Implements a fast rectangular sigma filter using the accumulator approach.
\
This function directly calls the execute method of BoxSigmaImageFilter in order to support a procedural API
See also
itk::simple::BoxSigmaImageFilter for the object oriented interface
BSplineDecomposition()
Image itk::simple::BSplineDecomposition (const Image & image1, uint32_t splineOrder = 3u)
Calculates the B-Spline coefficients of an image. Spline order may be from 0 to 5.
\
This function directly calls the execute method of BSplineDecompositionImageFilter in order to support a procedural API
See also
itk::simple::BSplineDecompositionImageFilter for the object oriented interface
BSplineTransformInitializer()
BSplineTransform itk::simple::BSplineTransformInitializer (const Image & image1, const std::vector< uint32_t > & transformDomainMeshSize = std::vector< uint32_t >(3, 1u), unsigned int order = 3u)
BSplineTransformInitializerFilter is a helper class intended to initialize the control point grid such that it has a physically consistent definition. It sets the transform domain origin, physical dimensions and direction from information obtained from the image. It also sets the mesh size if asked to do so by calling SetTransformDomainMeshSize()before calling InitializeTransform().
This function directly calls the execute method of BSplineTransformInitializerFilter in order to support a procedural API
See also
itk::simple::BSplineTransformInitializerFilter for the object oriented interface
Examples
ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, and ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx.
CannyEdgeDetection()
Image itk::simple::CannyEdgeDetection (const Image & image1, double lowerThreshold = 0.0, double upperThreshold = 0.0, std::vector< double > variance = std::vector< double >(3, 0.0), std::vector< double > maximumError = std::vector< double >(3, 0.01))
This filter is an implementation of a Canny edge detector for scalar-valued images.
\
This function directly calls the execute method of CannyEdgeDetectionImageFilter in order to support a procedural API
See also
itk::simple::CannyEdgeDetectionImageFilter for the object oriented interface
CannySegmentationLevelSet() [1/2]
Image itk::simple::CannySegmentationLevelSet (const Image & initialImage, const Image & featureImage, double threshold = 0.0, double variance = 0.0, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, double advectionScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false, double isoSurfaceValue = 0.0)
Segments structures in images based on image features derived from pseudo-canny-edges.
\
This function directly calls the execute method of CannySegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::CannySegmentationLevelSetImageFilter for the object oriented interface
CannySegmentationLevelSet() [2/2]
Image itk::simple::CannySegmentationLevelSet (Image && initialImage, const Image & featureImage, double threshold = 0.0, double variance = 0.0, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, double advectionScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false, double isoSurfaceValue = 0.0)
Segments structures in images based on image features derived from pseudo-canny-edges.
\
This function directly calls the execute method of CannySegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::CannySegmentationLevelSetImageFilter for the object oriented interface
Cast()
Image itk::simple::Cast (const Image & image, PixelIDValueEnum pixelID)
Examples
CppInPlace/CppInPlace.cxx, and SimpleGaussianFunctional.cxx.
CenteredTransformInitializer()
Transform itk::simple::CenteredTransformInitializer (const Image & fixedImage, const Image & movingImage, const Transform & transform, CenteredTransformInitializerFilter::OperationModeType operationMode = itk::simple::CenteredTransformInitializerFilter::MOMENTS)
CenteredTransformInitializer is a helper class intended to initialize the center of rotation and the translation of Transforms having the center of rotation among their parameters.
This function directly calls the execute method of CenteredTransformInitializerFilter in order to support a procedural API
See also
itk::simple::CenteredTransformInitializerFilter for the object oriented interface
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
CenteredVersorTransformInitializer()
Transform itk::simple::CenteredVersorTransformInitializer (const Image & fixedImage, const Image & movingImage, const Transform & transform, bool computeRotation = false)
CenteredVersorTransformInitializer is a helper class intended to initialize the center of rotation, versor, and translation of the VersorRigid3DTransform.
This function directly calls the execute method of CenteredVectorTransformInitializerFilter in order to support a procedural API.
See also
itk::simple::CenteredVersorTransformInitializerFilter for the object oriented interface
ChangeLabel() [1/2]
Image itk::simple::ChangeLabel (const Image & image1, std::map< double, double > changeMap = std::map< double, double >())
Change Sets of Labels.
\
This function directly calls the execute method of ChangeLabelImageFilter in order to support a procedural API
See also
itk::simple::ChangeLabelImageFilter for the object oriented interface
ChangeLabel() [2/2]
Image itk::simple::ChangeLabel (Image && image1, std::map< double, double > changeMap = std::map< double, double >())
Change Sets of Labels.
\
This function directly calls the execute method of ChangeLabelImageFilter in order to support a procedural API
See also
itk::simple::ChangeLabelImageFilter for the object oriented interface
ChangeLabelLabelMap() [1/2]
Image itk::simple::ChangeLabelLabelMap (const Image & image1, std::map< double, double > changeMap = std::map< double, double >())
Replace the label Ids of selected LabelObjects with new label Ids.
\
This function directly calls the execute method of ChangeLabelLabelMapFilter in order to support a procedural API
See also
itk::simple::ChangeLabelLabelMapFilter for the object oriented interface
ChangeLabelLabelMap() [2/2]
Image itk::simple::ChangeLabelLabelMap (Image && image1, std::map< double, double > changeMap = std::map< double, double >())
Replace the label Ids of selected LabelObjects with new label Ids.
\
This function directly calls the execute method of ChangeLabelLabelMapFilter in order to support a procedural API
See also
itk::simple::ChangeLabelLabelMapFilter for the object oriented interface
CheckerBoard()
Image itk::simple::CheckerBoard (const Image & image1, const Image & image2, std::vector< uint32_t > checkerPattern = std::vector< uint32_t >(3, 4))
Combines two images in a checkerboard pattern.
\
This function directly calls the execute method of CheckerBoardImageFilter in order to support a procedural API
See also
itk::simple::CheckerBoardImageFilter for the object oriented interface
Clamp() [1/2]
Image itk::simple::Clamp (const Image & image1, PixelIDValueEnum outputPixelType = itk::simple::sitkUnknown, double lowerBound = -std::numeric_limits< double >::max(), double upperBound = std::numeric_limits< double >::max())
Casts input pixels to output pixel type and clamps the output pixel values to a specified range.
\
This function directly calls the execute method of ClampImageFilter in order to support a procedural API
See also
itk::simple::ClampImageFilter for the object oriented interface
Clamp() [2/2]
Image itk::simple::Clamp (Image && image1, PixelIDValueEnum outputPixelType = itk::simple::sitkUnknown, double lowerBound = -std::numeric_limits< double >::max(), double upperBound = std::numeric_limits< double >::max())
Casts input pixels to output pixel type and clamps the output pixel values to a specified range.
\
This function directly calls the execute method of ClampImageFilter in order to support a procedural API
See also
itk::simple::ClampImageFilter for the object oriented interface
ClosingByReconstruction()
Image itk::simple::ClosingByReconstruction (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool fullyConnected = false, bool preserveIntensities = false)
Closing by reconstruction of an image.
\
This function directly calls the execute method of ClosingByReconstructionImageFilter in order to support a procedural API
See also
itk::simple::ClosingByReconstructionImageFilter for the object oriented interface
CollidingFronts()
Image itk::simple::CollidingFronts (const Image & image1, std::vector< std::vector< unsigned int > > seedPoints1 = std::vector< std::vector< unsigned int > >(), std::vector< std::vector< unsigned int > > seedPoints2 = std::vector< std::vector< unsigned int > >(), bool applyConnectivity = true, double negativeEpsilon = -1e-6, bool stopOnTargets = false)
Selects a region of space where two independent fronts run towards each other.
\
This function directly calls the execute method of CollidingFrontsImageFilter in order to support a procedural API
See also
itk::simple::CollidingFrontsImageFilter for the object oriented interface
ComplexToImaginary() [1/2]
Image itk::simple::ComplexToImaginary (const Image & image1)
Computes pixel-wise the imaginary part of a complex image.
\
This function directly calls the execute method of ComplexToImaginaryImageFilter in order to support a procedural API
See also
itk::simple::ComplexToImaginaryImageFilter for the object oriented interface
ComplexToImaginary() [2/2]
Image itk::simple::ComplexToImaginary (Image && image1)
Computes pixel-wise the imaginary part of a complex image.
\
This function directly calls the execute method of ComplexToImaginaryImageFilter in order to support a procedural API
See also
itk::simple::ComplexToImaginaryImageFilter for the object oriented interface
ComplexToModulus() [1/2]
Image itk::simple::ComplexToModulus (const Image & image1)
Computes pixel-wise the Modulus of a complex image.
\
This function directly calls the execute method of ComplexToModulusImageFilter in order to support a procedural API
See also
itk::simple::ComplexToModulusImageFilter for the object oriented interface
ComplexToModulus() [2/2]
Image itk::simple::ComplexToModulus (Image && image1)
Computes pixel-wise the Modulus of a complex image.
\
This function directly calls the execute method of ComplexToModulusImageFilter in order to support a procedural API
See also
itk::simple::ComplexToModulusImageFilter for the object oriented interface
ComplexToPhase() [1/2]
Image itk::simple::ComplexToPhase (const Image & image1)
Computes pixel-wise the modulus of a complex image.
\
This function directly calls the execute method of ComplexToPhaseImageFilter in order to support a procedural API
See also
itk::simple::ComplexToPhaseImageFilter for the object oriented interface
ComplexToPhase() [2/2]
Image itk::simple::ComplexToPhase (Image && image1)
Computes pixel-wise the modulus of a complex image.
\
This function directly calls the execute method of ComplexToPhaseImageFilter in order to support a procedural API
See also
itk::simple::ComplexToPhaseImageFilter for the object oriented interface
ComplexToReal() [1/2]
Image itk::simple::ComplexToReal (const Image & image1)
Computes pixel-wise the real(x) part of a complex image.
\
This function directly calls the execute method of ComplexToRealImageFilter in order to support a procedural API
See also
itk::simple::ComplexToRealImageFilter for the object oriented interface
ComplexToReal() [2/2]
Image itk::simple::ComplexToReal (Image && image1)
Computes pixel-wise the real(x) part of a complex image.
\
This function directly calls the execute method of ComplexToRealImageFilter in order to support a procedural API
See also
itk::simple::ComplexToRealImageFilter for the object oriented interface
Compose() [1/6]
Image itk::simple::Compose (const Image & image1)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
Compose() [2/6]
Image itk::simple::Compose (const Image & image1, const Image & image2)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
Compose() [3/6]
Image itk::simple::Compose (const Image & image1, const Image & image2, const Image & image3)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
Compose() [4/6]
Image itk::simple::Compose (const Image & image1, const Image & image2, const Image & image3, const Image & image4)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
Compose() [5/6]
Image itk::simple::Compose (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
Compose() [6/6]
Image itk::simple::Compose (const std::vector< Image > & images)
ComposeImageFilter combine several scalar images into a multicomponent image.
This function directly calls the execute method of ComposeImageFilter in order to support a procedural API
See also
itk::simple::ComposeImageFilter for the object oriented interface
ConfidenceConnected()
Image itk::simple::ConfidenceConnected (const Image & image1, std::vector< std::vector< unsigned int > > seedList = std::vector< std::vector< unsigned int > >(), unsigned int numberOfIterations = 4u, double multiplier = 4.5, unsigned int initialNeighborhoodRadius = 1u, uint8_t replaceValue = 1u)
Segment pixels with similar statistics using connectivity.
\
This function directly calls the execute method of ConfidenceConnectedImageFilter in order to support a procedural API
See also
itk::simple::ConfidenceConnectedImageFilter for the object oriented interface
ConnectedComponent() [1/2]
Image itk::simple::ConnectedComponent (const Image & image, bool fullyConnected = false)
Label the objects in a binary image.
\
This function directly calls the execute method of ConnectedComponentImageFilter in order to support a procedural API
See also
itk::simple::ConnectedComponentImageFilter for the object oriented interface
ConnectedComponent() [2/2]
Image itk::simple::ConnectedComponent (const Image & image, const Image & maskImage, bool fullyConnected = false)
Label the objects in a binary image.
\
This function directly calls the execute method of ConnectedComponentImageFilter in order to support a procedural API
See also
itk::simple::ConnectedComponentImageFilter for the object oriented interface
ConnectedThreshold()
Image itk::simple::ConnectedThreshold (const Image & image1, std::vector< std::vector< unsigned int > > seedList = std::vector< std::vector< unsigned int > >(), double lower = 0, double upper = 1, uint8_t replaceValue = 1u, ConnectedThresholdImageFilter::ConnectivityType connectivity = itk::simple::ConnectedThresholdImageFilter::FaceConnectivity)
Label pixels that are connected to a seed and lie within a range of values.
\
This function directly calls the execute method of ConnectedThresholdImageFilter in order to support a procedural API
See also
itk::simple::ConnectedThresholdImageFilter for the object oriented interface
ConstantPad()
Image itk::simple::ConstantPad (const Image & image1, std::vector< unsigned int > padLowerBound = std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound = std::vector< unsigned int >(3, 0), double constant = 0.0)
Increase the image size by padding with a constant value.
\
This function directly calls the execute method of ConstantPadImageFilter in order to support a procedural API
See also
itk::simple::ConstantPadImageFilter for the object oriented interface
Convolution()
Image itk::simple::Convolution (const Image & image, const Image & kernelImage, bool normalize = false, ConvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::ConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, ConvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::ConvolutionImageFilter::SAME)
Convolve a given image with an arbitrary image kernel.
\
This function directly calls the execute method of ConvolutionImageFilter in order to support a procedural API
See also
itk::simple::ConvolutionImageFilter for the object oriented interface
Cos() [1/2]
Image itk::simple::Cos (const Image & image1)
Computes the cosine of each pixel.
\
This function directly calls the execute method of CosImageFilter in order to support a procedural API
See also
itk::simple::CosImageFilter for the object oriented interface
Cos() [2/2]
Image itk::simple::Cos (Image && image1)
Computes the cosine of each pixel.
\
This function directly calls the execute method of CosImageFilter in order to support a procedural API
See also
itk::simple::CosImageFilter for the object oriented interface
CreateKernel()
template<unsigned int VImageDimension> itk::FlatStructuringElement< VImageDimension > itk::simple::CreateKernel (KernelEnum kernelType, const std::vector< uint32_t > & size)
Definition at line 36 of file sitkCreateKernel.h.
References sitkAnnulus, sitkBall, sitkBox, sitkCross, sitkExceptionMacro, and sitkKernelPolygonCreateMacro.
Crop() [1/2]
Image itk::simple::Crop (const Image & image1, std::vector< unsigned int > lowerBoundaryCropSize = std::vector< unsigned int >(3, 0), std::vector< unsigned int > upperBoundaryCropSize = std::vector< unsigned int >(3, 0))
Decrease the image size by cropping the image by an itk::Size at both the upper and lower bounds of the largest possible region.
\
This function directly calls the execute method of CropImageFilter in order to support a procedural API
See also
itk::simple::CropImageFilter for the object oriented interface
Crop() [2/2]
Image itk::simple::Crop (Image && image1, std::vector< unsigned int > lowerBoundaryCropSize = std::vector< unsigned int >(3, 0), std::vector< unsigned int > upperBoundaryCropSize = std::vector< unsigned int >(3, 0))
Decrease the image size by cropping the image by an itk::Size at both the upper and lower bounds of the largest possible region.
\
This function directly calls the execute method of CropImageFilter in order to support a procedural API
See also
itk::simple::CropImageFilter for the object oriented interface
Referenced by itk::simple::LabelMapMaskImageFilter::SetCrop().
CurvatureAnisotropicDiffusion() [1/2]
Image itk::simple::CurvatureAnisotropicDiffusion (const Image & image1, double timeStep = 0.0625, double conductanceParameter = 3.0, unsigned int conductanceScalingUpdateInterval = 1u, uint32_t numberOfIterations = 5u)
itk::simple::CurvatureAnisotropicDiffusionImageFilter Procedural Interface
\
This function directly calls the execute method of CurvatureAnisotropicDiffusionImageFilter in order to support a procedural API
See also
itk::simple::CurvatureAnisotropicDiffusionImageFilter for the object oriented interface
CurvatureAnisotropicDiffusion() [2/2]
Image itk::simple::CurvatureAnisotropicDiffusion (Image && image1, double timeStep = 0.0625, double conductanceParameter = 3.0, unsigned int conductanceScalingUpdateInterval = 1u, uint32_t numberOfIterations = 5u)
itk::simple::CurvatureAnisotropicDiffusionImageFilter Procedural Interface
\
This function directly calls the execute method of CurvatureAnisotropicDiffusionImageFilter in order to support a procedural API
See also
itk::simple::CurvatureAnisotropicDiffusionImageFilter for the object oriented interface
CurvatureFlow() [1/2]
Image itk::simple::CurvatureFlow (const Image & image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u)
Denoise an image using curvature driven flow.
\
This function directly calls the execute method of CurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::CurvatureFlowImageFilter for the object oriented interface
CurvatureFlow() [2/2]
Image itk::simple::CurvatureFlow (Image && image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u)
Denoise an image using curvature driven flow.
\
This function directly calls the execute method of CurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::CurvatureFlowImageFilter for the object oriented interface
CyclicShift()
Image itk::simple::CyclicShift (const Image & image1, std::vector< int > shift = std::vector< int >(3, 0))
Perform a cyclic spatial shift of image intensities on the image grid.
\
This function directly calls the execute method of CyclicShiftImageFilter in order to support a procedural API
See also
itk::simple::CyclicShiftImageFilter for the object oriented interface
DanielssonDistanceMap()
Image itk::simple::DanielssonDistanceMap (const Image & image1, bool inputIsBinary = false, bool squaredDistance = false, bool useImageSpacing = false)
This filter computes the distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
\
This function directly calls the execute method of DanielssonDistanceMapImageFilter in order to support a procedural API
See also
itk::simple::DanielssonDistanceMapImageFilter for the object oriented interface
Derivative()
Image itk::simple::Derivative (const Image & image1, unsigned int direction = 0u, unsigned int order = 1u, bool useImageSpacing = true)
Computes the directional derivative of an image. The directional derivative at each pixel location is computed by convolution with a derivative operator of user-specified order.
\
This function directly calls the execute method of DerivativeImageFilter in order to support a procedural API
See also
itk::simple::DerivativeImageFilter for the object oriented interface
DICOMOrient()
Image itk::simple::DICOMOrient (const Image & image1, std::string desiredCoordinateOrientation = std::string("LPS"))
Permute axes and flip images as needed to obtain an approximation to the desired orientation.
\
This function directly calls the execute method of DICOMOrientImageFilter in order to support a procedural API
See also
itk::simple::DICOMOrientImageFilter for the object oriented interface
DilateObjectMorphology()
Image itk::simple::DilateObjectMorphology (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double objectValue = 1)
dilation of an object in an image
\
This function directly calls the execute method of DilateObjectMorphologyImageFilter in order to support a procedural API
See also
itk::simple::DilateObjectMorphologyImageFilter for the object oriented interface
DiscreteGaussian() [1/2]
Image itk::simple::DiscreteGaussian (const Image & image1, double variance, unsigned int maximumKernelWidth = 32u, double maximumError = 0.01, bool useImageSpacing = true)
Blurs an image by separable convolution with discrete gaussian kernels. This filter performs Gaussian blurring by separable convolution of an image and a discrete Gaussian operator (kernel).
This function directly calls the execute method of DiscreteGaussianImageFilter in order to support a procedural API
See also
itk::simple::DiscreteGaussianImageFilter for the object oriented interface
DiscreteGaussian() [2/2]
Image itk::simple::DiscreteGaussian (const Image & image1, std::vector< double > variance = std::vector< double >(3, 1.0), unsigned int maximumKernelWidth = 32u, std::vector< double > maximumError = std::vector< double >(3, 0.01), bool useImageSpacing = true)
Blurs an image by separable convolution with discrete gaussian kernels. This filter performs Gaussian blurring by separable convolution of an image and a discrete Gaussian operator (kernel).
\
This function directly calls the execute method of DiscreteGaussianImageFilter in order to support a procedural API
See also
itk::simple::DiscreteGaussianImageFilter for the object oriented interface
Examples
ImageRegistrationMethod2/ImageRegistrationMethod2.cxx.
DiscreteGaussianDerivative()
Image itk::simple::DiscreteGaussianDerivative (const Image & image1, std::vector< double > variance = std::vector< double >(3, 0.0), std::vector< unsigned int > order = std::vector< unsigned int >(3, 1), unsigned int maximumKernelWidth = 32u, double maximumError = 0.01, bool useImageSpacing = true, bool normalizeAcrossScale = false)
Calculates image derivatives using discrete derivative gaussian kernels. This filter calculates Gaussian derivative by separable convolution of an image and a discrete Gaussian derivative operator (kernel).
\
This function directly calls the execute method of DiscreteGaussianDerivativeImageFilter in order to support a procedural API
See also
itk::simple::DiscreteGaussianDerivativeImageFilter for the object oriented interface
DisplacementFieldJacobianDeterminant()
Image itk::simple::DisplacementFieldJacobianDeterminant (const Image & image1, bool useImageSpacing = true, std::vector< double > derivativeWeights = std::vector< double >())
Computes a scalar image from a vector image (e.g., deformation field) input, where each output scalar at each pixel is the Jacobian determinant of the vector field at that location. This calculation is correct in the case where the vector image is a "displacement" from the current location. The computation for the jacobian determinant is: det[ dT/dx ] = det[ I + du/dx ].
\
This function directly calls the execute method of DisplacementFieldJacobianDeterminantFilter in order to support a procedural API
See also
itk::simple::DisplacementFieldJacobianDeterminantFilter for the object oriented interface
Divide() [1/5]
Image itk::simple::Divide (const Image & image1, const Image & image2)
Pixel-wise division of two images.
\
This function directly calls the execute method of DivideImageFilter in order to support a procedural API
See also
itk::simple::DivideImageFilter for the object oriented interface
Divide() [2/5]
Image itk::simple::Divide (const Image & image1, double constant)
Divide() [3/5]
Image itk::simple::Divide (double constant, const Image & image2)
Divide() [4/5]
Image itk::simple::Divide (Image && image1, const Image & image2)
Pixel-wise division of two images.
\
This function directly calls the execute method of DivideImageFilter in order to support a procedural API
See also
itk::simple::DivideImageFilter for the object oriented interface
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Referenced by operator/(), and operator/=().
Divide() [5/5]
Image itk::simple::Divide (Image && image1, double constant)
DivideFloor() [1/5]
Image itk::simple::DivideFloor (const Image & image1, const Image & image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of DivideFloorImageFilter in order to support a procedural API
See also
itk::simple::DivideFloorImageFilter for the object oriented interface
DivideFloor() [2/5]
Image itk::simple::DivideFloor (const Image & image1, double constant)
DivideFloor() [3/5]
Image itk::simple::DivideFloor (double constant, const Image & image2)
DivideFloor() [4/5]
Image itk::simple::DivideFloor (Image && image1, const Image & image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of DivideFloorImageFilter in order to support a procedural API
See also
itk::simple::DivideFloorImageFilter for the object oriented interface
DivideFloor() [5/5]
Image itk::simple::DivideFloor (Image && image1, double constant)
DivideReal() [1/5]
Image itk::simple::DivideReal (const Image & image1, const Image & image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of DivideRealImageFilter in order to support a procedural API
See also
itk::simple::DivideRealImageFilter for the object oriented interface
DivideReal() [2/5]
Image itk::simple::DivideReal (const Image & image1, double constant)
DivideReal() [3/5]
Image itk::simple::DivideReal (double constant, const Image & image2)
DivideReal() [4/5]
Image itk::simple::DivideReal (Image && image1, const Image & image2)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of DivideRealImageFilter in order to support a procedural API
See also
itk::simple::DivideRealImageFilter for the object oriented interface
DivideReal() [5/5]
Image itk::simple::DivideReal (Image && image1, double constant)
DoubleThreshold()
Image itk::simple::DoubleThreshold (const Image & image1, double threshold1 = 0.0, double threshold2 = 1.0, double threshold3 = 254.0, double threshold4 = 255.0, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, bool fullyConnected = false)
Binarize an input image using double thresholding.
\
This function directly calls the execute method of DoubleThresholdImageFilter in order to support a procedural API
See also
itk::simple::DoubleThresholdImageFilter for the object oriented interface
EdgePotential() [1/2]
Image itk::simple::EdgePotential (const Image & image1)
Computes the edge potential of an image from the image gradient.
\
This function directly calls the execute method of EdgePotentialImageFilter in order to support a procedural API
See also
itk::simple::EdgePotentialImageFilter for the object oriented interface
EdgePotential() [2/2]
Image itk::simple::EdgePotential (Image && image1)
Computes the edge potential of an image from the image gradient.
\
This function directly calls the execute method of EdgePotentialImageFilter in order to support a procedural API
See also
itk::simple::EdgePotentialImageFilter for the object oriented interface
Equal() [1/5]
Image itk::simple::Equal (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of EqualImageFilter in order to support a procedural API
See also
itk::simple::EqualImageFilter for the object oriented interface
Equal() [2/5]
Image itk::simple::Equal (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Equal() [3/5]
Image itk::simple::Equal (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Equal() [4/5]
Image itk::simple::Equal (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of EqualImageFilter in order to support a procedural API
See also
itk::simple::EqualImageFilter for the object oriented interface
Equal() [5/5]
Image itk::simple::Equal (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
ErodeObjectMorphology()
Image itk::simple::ErodeObjectMorphology (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, double objectValue = 1, double backgroundValue = 0)
Erosion of an object in an image.
\
This function directly calls the execute method of ErodeObjectMorphologyImageFilter in order to support a procedural API
See also
itk::simple::ErodeObjectMorphologyImageFilter for the object oriented interface
Exp() [1/2]
Image itk::simple::Exp (const Image & image1)
Computes the exponential function of each pixel.
\
This function directly calls the execute method of ExpImageFilter in order to support a procedural API
See also
itk::simple::ExpImageFilter for the object oriented interface
Exp() [2/2]
Image itk::simple::Exp (Image && image1)
Computes the exponential function of each pixel.
\
This function directly calls the execute method of ExpImageFilter in order to support a procedural API
See also
itk::simple::ExpImageFilter for the object oriented interface
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Expand()
Image itk::simple::Expand (const Image & image1, std::vector< unsigned int > expandFactors = std::vector< unsigned int >(3, 1), InterpolatorEnum interpolator = itk::simple::sitkLinear)
Expand the size of an image by an integer factor in each dimension.
\
This function directly calls the execute method of ExpandImageFilter in order to support a procedural API
See also
itk::simple::ExpandImageFilter for the object oriented interface
ExpNegative() [1/2]
Image itk::simple::ExpNegative (const Image & image1)
Computes the function exp(-K.x) for each input pixel.
\
This function directly calls the execute method of ExpNegativeImageFilter in order to support a procedural API
See also
itk::simple::ExpNegativeImageFilter for the object oriented interface
ExpNegative() [2/2]
Image itk::simple::ExpNegative (Image && image1)
Computes the function exp(-K.x) for each input pixel.
\
This function directly calls the execute method of ExpNegativeImageFilter in order to support a procedural API
See also
itk::simple::ExpNegativeImageFilter for the object oriented interface
Extract() [1/2]
Image itk::simple::Extract (const Image & image1, std::vector< unsigned int > size = std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > index = std::vector< int >(SITK_MAX_DIMENSION, 0), ExtractImageFilter::DirectionCollapseToStrategyType directionCollapseToStrategy = itk::simple::ExtractImageFilter::DIRECTIONCOLLAPSETOGUESS)
Decrease the image size by cropping the image to the selected region bounds.
\
This function directly calls the execute method of ExtractImageFilter in order to support a procedural API
See also
itk::simple::ExtractImageFilter for the object oriented interface
Extract() [2/2]
Image itk::simple::Extract (Image && image1, std::vector< unsigned int > size = std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > index = std::vector< int >(SITK_MAX_DIMENSION, 0), ExtractImageFilter::DirectionCollapseToStrategyType directionCollapseToStrategy = itk::simple::ExtractImageFilter::DIRECTIONCOLLAPSETOGUESS)
Decrease the image size by cropping the image to the selected region bounds.
\
This function directly calls the execute method of ExtractImageFilter in order to support a procedural API
See also
itk::simple::ExtractImageFilter for the object oriented interface
FastApproximateRank()
Image itk::simple::FastApproximateRank (const Image & image1, double rank = 0.5, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
A separable rank filter.
\
This function directly calls the execute method of FastApproximateRankImageFilter in order to support a procedural API
See also
itk::simple::FastApproximateRankImageFilter for the object oriented interface
FastMarching()
Image itk::simple::FastMarching (const Image & image1, std::vector< std::vector< unsigned int > > trialPoints = std::vector< std::vector< unsigned int > >(), double normalizationFactor = 1.0, double stoppingValue = std::numeric_limits< double >::max()/2.0)
Solve an Eikonal equation using Fast Marching.
\
This function directly calls the execute method of FastMarchingImageFilter in order to support a procedural API
See also
itk::simple::FastMarchingImageFilter for the object oriented interface
FastMarchingBase()
Image itk::simple::FastMarchingBase (const Image & image1, std::vector< std::vector< unsigned int > > trialPoints = std::vector< std::vector< unsigned int > >(), double normalizationFactor = 1.0, double stoppingValue = std::numeric_limits< float >::max()/2.0, FastMarchingBaseImageFilter::TopologyCheckType topologyCheck = itk::simple::FastMarchingBaseImageFilter::Nothing)
Apply the Fast Marching method to solve an Eikonal equation on an image.
\
This function directly calls the execute method of FastMarchingBaseImageFilter in order to support a procedural API
See also
itk::simple::FastMarchingBaseImageFilter for the object oriented interface
FastMarchingUpwindGradient()
Image itk::simple::FastMarchingUpwindGradient (const Image & image1, std::vector< std::vector< unsigned int > > trialPoints = std::vector< std::vector< unsigned int > >(), unsigned int numberOfTargets = 0u, std::vector< std::vector< unsigned int > > targetPoints = std::vector< std::vector< unsigned int > >(), double targetOffset = 1.0, double normalizationFactor = 1.0)
Generates the upwind gradient field of fast marching arrival times.
\
This function directly calls the execute method of FastMarchingUpwindGradientImageFilter in order to support a procedural API
See also
itk::simple::FastMarchingUpwindGradientImageFilter for the object oriented interface
FFTConvolution()
Image itk::simple::FFTConvolution (const Image & image, const Image & kernelImage, bool normalize = false, FFTConvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::FFTConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, FFTConvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::FFTConvolutionImageFilter::SAME)
Convolve a given image with an arbitrary image kernel using multiplication in the Fourier domain.
\
This function directly calls the execute method of FFTConvolutionImageFilter in order to support a procedural API
See also
itk::simple::FFTConvolutionImageFilter for the object oriented interface
FFTNormalizedCorrelation()
Image itk::simple::FFTNormalizedCorrelation (const Image & image1, const Image & image2, uint64_t requiredNumberOfOverlappingPixels = 0u)
Calculate normalized cross correlation using FFTs.
\
This function directly calls the execute method of FFTNormalizedCorrelationImageFilter in order to support a procedural API
See also
itk::simple::FFTNormalizedCorrelationImageFilter for the object oriented interface
FFTPad()
Image itk::simple::FFTPad (const Image & image1, FFTPadImageFilter::BoundaryConditionType boundaryCondition = itk::simple::FFTPadImageFilter::ZERO_FLUX_NEUMANN_PAD, int sizeGreatestPrimeFactor = 5)
Pad an image to make it suitable for an FFT transformation.
\
This function directly calls the execute method of FFTPadImageFilter in order to support a procedural API
See also
itk::simple::FFTPadImageFilter for the object oriented interface
FFTShift()
Image itk::simple::FFTShift (const Image & image1, bool inverse = false)
Shift the zero-frequency components of a Fourier transform to the center of the image.
\
This function directly calls the execute method of FFTShiftImageFilter in order to support a procedural API
See also
itk::simple::FFTShiftImageFilter for the object oriented interface
Flip()
Image itk::simple::Flip (const Image & image1, std::vector< bool > flipAxes = std::vector< bool >(3, false), bool flipAboutOrigin = false)
Flips an image across user specified axes.
\
This function directly calls the execute method of FlipImageFilter in order to support a procedural API
See also
itk::simple::FlipImageFilter for the object oriented interface
ForwardFFT()
Image itk::simple::ForwardFFT (const Image & image1)
Base class for forward Fast Fourier Transform .
\
This function directly calls the execute method of ForwardFFTImageFilter in order to support a procedural API
See also
itk::simple::ForwardFFTImageFilter for the object oriented interface
GaborSource()
Image itk::simple::GaborSource (PixelIDValueEnum outputPixelType = itk::simple::sitkFloat32, std::vector< unsigned int > size = std::vector< unsigned int >(3, 64), std::vector< double > sigma = std::vector< double >(3, 16.0), std::vector< double > mean = std::vector< double >(3, 32.0), double frequency = 0.4, std::vector< double > origin = std::vector< double >(3, 0.0), std::vector< double > spacing = std::vector< double >(3, 1.0), std::vector< double > direction = std::vector< double >())
Generate an n-dimensional image of a Gabor filter.
This function directly calls the execute method of GaborImageSource in order to support a procedural API
See also
itk::simple::GaborImageSource for the object oriented interface
GaussianSource()
Image itk::simple::GaussianSource (PixelIDValueEnum outputPixelType = itk::simple::sitkFloat32, std::vector< unsigned int > size = std::vector< unsigned int >(3, 64), std::vector< double > sigma = std::vector< double >(3, 16.0), std::vector< double > mean = std::vector< double >(3, 32.0), double scale = 255, std::vector< double > origin = std::vector< double >(3, 0.0), std::vector< double > spacing = std::vector< double >(3, 1.0), std::vector< double > direction = std::vector< double >(), bool normalized = false)
Generate an n-dimensional image of a Gaussian.
This function directly calls the execute method of GaussianImageSource in order to support a procedural API
See also
itk::simple::GaussianImageSource for the object oriented interface
Examples
CppCMake/Source/sitk_example.cxx, and HelloWorld/HelloWorld.cxx.
GeodesicActiveContourLevelSet() [1/2]
Image itk::simple::GeodesicActiveContourLevelSet (const Image & initialImage, const Image & featureImage, double maximumRMSError = 0.01, double propagationScaling = 1.0, double curvatureScaling = 1.0, double advectionScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a user supplied edge potential map.
\
This function directly calls the execute method of GeodesicActiveContourLevelSetImageFilter in order to support a procedural API
See also
itk::simple::GeodesicActiveContourLevelSetImageFilter for the object oriented interface
GeodesicActiveContourLevelSet() [2/2]
Image itk::simple::GeodesicActiveContourLevelSet (Image && initialImage, const Image & featureImage, double maximumRMSError = 0.01, double propagationScaling = 1.0, double curvatureScaling = 1.0, double advectionScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a user supplied edge potential map.
\
This function directly calls the execute method of GeodesicActiveContourLevelSetImageFilter in order to support a procedural API
See also
itk::simple::GeodesicActiveContourLevelSetImageFilter for the object oriented interface
GetImageFromVectorImage()
template<typename TPixelType , unsigned int ImageDimension> SITKCommon_HIDDEN itk::Image< itk::Vector< TPixelType, ImageDimension >, ImageDimension >::Pointer itk::simple::GetImageFromVectorImage (itk::VectorImage< TPixelType, ImageDimension > * img, bool transferOwnership = false)
A utility method to help convert between itk image types efficiently.
GetPixelIDValueAsString() [1/2]
const std::string SITKCommon_EXPORT itk::simple::GetPixelIDValueAsString (PixelIDValueEnum type)
GetPixelIDValueAsString() [2/2]
const std::string SITKCommon_EXPORT itk::simple::GetPixelIDValueAsString (PixelIDValueType type)
Referenced by itk::simple::ProcessObject::CastImageToITK().
GetPixelIDValueFromString()
PixelIDValueType SITKCommon_EXPORT itk::simple::GetPixelIDValueFromString (const std::string & enumString)
Function mapping enumeration names in std::string to values.
This function is intended for use by the R bindings. R stores the enumeration values using the names : "sitkUnknown", "sitkUInt8", etc from PixelIDValueEnum above. This function is used to provide the integer values using calls like:
val = GetPixelIDValueFromString("sitkInt32")
If the pixel type has not been instantiated then the sitkUnknown value (-1) will be returned. If the pixel type string is not recognized (i.e. is not in the set of tested names) then the return value is -99. The idea is to provide a warning (via the R package) if this function needs to be updated to match changes to PixelIDValueEnum - i.e. if a new pixel type is added.
GetVectorImageFromImage() [1/3]
template<class TPixelType , unsigned int NImageDimension, unsigned int NLength> SITKCommon_HIDDEN itk::VectorImage< TPixelType, NImageDimension >::Pointer itk::simple::GetVectorImageFromImage (itk::Image< itk::CovariantVector< TPixelType, NLength >, NImageDimension > * img, bool transferOwnership = false)
GetVectorImageFromImage() [2/3]
template<unsigned int NImageDimension, unsigned int NLength> SITKCommon_HIDDEN itk::VectorImage< typenamestd::conditional< sizeof(typenameitk::Offset< NLength >::OffsetValueType)==sizeof(int64_t), int64_t, FalseType >::type, NImageDimension >::Pointer itk::simple::GetVectorImageFromImage (itk::Image< itk::Offset< NLength >, NImageDimension > * img, bool transferOwnership = false)
GetVectorImageFromImage() [3/3]
template<class TPixelType , unsigned int NImageDimension, unsigned int NLength> SITKCommon_HIDDEN itk::VectorImage< TPixelType, NImageDimension >::Pointer itk::simple::GetVectorImageFromImage (itk::Image< itk::Vector< TPixelType, NLength >, NImageDimension > * img, bool transferOwnership = false)
Referenced by itk::simple::ProcessObject::CastITKToImage().
Gradient()
Image itk::simple::Gradient (const Image & image1, bool useImageSpacing = true, bool useImageDirection = false)
Computes the gradient of an image using directional derivatives.
\
This function directly calls the execute method of GradientImageFilter in order to support a procedural API
See also
itk::simple::GradientImageFilter for the object oriented interface
GradientAnisotropicDiffusion() [1/2]
Image itk::simple::GradientAnisotropicDiffusion (const Image & image1, double timeStep = 0.125, double conductanceParameter = 3, unsigned int conductanceScalingUpdateInterval = 1u, uint32_t numberOfIterations = 5u)
itk::simple::GradientAnisotropicDiffusionImageFilter Procedural Interface
\
This function directly calls the execute method of GradientAnisotropicDiffusionImageFilter in order to support a procedural API
See also
itk::simple::GradientAnisotropicDiffusionImageFilter for the object oriented interface
GradientAnisotropicDiffusion() [2/2]
Image itk::simple::GradientAnisotropicDiffusion (Image && image1, double timeStep = 0.125, double conductanceParameter = 3, unsigned int conductanceScalingUpdateInterval = 1u, uint32_t numberOfIterations = 5u)
itk::simple::GradientAnisotropicDiffusionImageFilter Procedural Interface
\
This function directly calls the execute method of GradientAnisotropicDiffusionImageFilter in order to support a procedural API
See also
itk::simple::GradientAnisotropicDiffusionImageFilter for the object oriented interface
GradientMagnitude()
Image itk::simple::GradientMagnitude (const Image & image1, bool useImageSpacing = true)
Computes the gradient magnitude of an image region at each pixel.
\
This function directly calls the execute method of GradientMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::GradientMagnitudeImageFilter for the object oriented interface
GradientMagnitudeRecursiveGaussian() [1/2]
Image itk::simple::GradientMagnitudeRecursiveGaussian (const Image & image1, double sigma = 1.0, bool normalizeAcrossScale = false)
Computes the Magnitude of the Gradient of an image by convolution with the first derivative of a Gaussian.
\
This function directly calls the execute method of GradientMagnitudeRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::GradientMagnitudeRecursiveGaussianImageFilter for the object oriented interface
GradientMagnitudeRecursiveGaussian() [2/2]
Image itk::simple::GradientMagnitudeRecursiveGaussian (Image && image1, double sigma = 1.0, bool normalizeAcrossScale = false)
Computes the Magnitude of the Gradient of an image by convolution with the first derivative of a Gaussian.
\
This function directly calls the execute method of GradientMagnitudeRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::GradientMagnitudeRecursiveGaussianImageFilter for the object oriented interface
GradientRecursiveGaussian()
Image itk::simple::GradientRecursiveGaussian (const Image & image1, double sigma = 1.0, bool normalizeAcrossScale = false, bool useImageDirection = false)
Computes the gradient of an image by convolution with the first derivative of a Gaussian.
\
This function directly calls the execute method of GradientRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::GradientRecursiveGaussianImageFilter for the object oriented interface
GrayscaleConnectedClosing()
Image itk::simple::GrayscaleConnectedClosing (const Image & image1, std::vector< uint32_t > seed = std::vector< uint32_t >(3, 0), bool fullyConnected = false)
Enhance pixels associated with a dark object (identified by a seed pixel) where the dark object is surrounded by a brighter object.
\
This function directly calls the execute method of GrayscaleConnectedClosingImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleConnectedClosingImageFilter for the object oriented interface
GrayscaleConnectedOpening()
Image itk::simple::GrayscaleConnectedOpening (const Image & image1, std::vector< unsigned int > seed = std::vector< unsigned int >(3, 0), bool fullyConnected = false)
Enhance pixels associated with a bright object (identified by a seed pixel) where the bright object is surrounded by a darker object.
\
This function directly calls the execute method of GrayscaleConnectedOpeningImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleConnectedOpeningImageFilter for the object oriented interface
GrayscaleDilate()
Image itk::simple::GrayscaleDilate (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall)
Grayscale dilation of an image.
\
This function directly calls the execute method of GrayscaleDilateImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleDilateImageFilter for the object oriented interface
GrayscaleErode()
Image itk::simple::GrayscaleErode (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall)
Grayscale erosion of an image.
\
This function directly calls the execute method of GrayscaleErodeImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleErodeImageFilter for the object oriented interface
Examples
BufferImportExport.cxx.
GrayscaleFillhole()
Image itk::simple::GrayscaleFillhole (const Image & image1, bool fullyConnected = false)
Remove local minima not connected to the boundary of the image.
\
This function directly calls the execute method of GrayscaleFillholeImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleFillholeImageFilter for the object oriented interface
GrayscaleGeodesicDilate()
Image itk::simple::GrayscaleGeodesicDilate (const Image & image1, const Image & image2, bool runOneIteration = false, bool fullyConnected = false)
geodesic gray scale dilation of an image
\
This function directly calls the execute method of GrayscaleGeodesicDilateImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleGeodesicDilateImageFilter for the object oriented interface
GrayscaleGeodesicErode()
Image itk::simple::GrayscaleGeodesicErode (const Image & image1, const Image & image2, bool runOneIteration = false, bool fullyConnected = false)
geodesic gray scale erosion of an image
\
This function directly calls the execute method of GrayscaleGeodesicErodeImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleGeodesicErodeImageFilter for the object oriented interface
GrayscaleGrindPeak()
Image itk::simple::GrayscaleGrindPeak (const Image & image1, bool fullyConnected = false)
Remove local maxima not connected to the boundary of the image.
\
This function directly calls the execute method of GrayscaleGrindPeakImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleGrindPeakImageFilter for the object oriented interface
GrayscaleMorphologicalClosing()
Image itk::simple::GrayscaleMorphologicalClosing (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool safeBorder = true)
gray scale dilation of an image
\
This function directly calls the execute method of GrayscaleMorphologicalClosingImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleMorphologicalClosingImageFilter for the object oriented interface
GrayscaleMorphologicalOpening()
Image itk::simple::GrayscaleMorphologicalOpening (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool safeBorder = true)
gray scale dilation of an image
\
This function directly calls the execute method of GrayscaleMorphologicalOpeningImageFilter in order to support a procedural API
See also
itk::simple::GrayscaleMorphologicalOpeningImageFilter for the object oriented interface
Greater() [1/5]
Image itk::simple::Greater (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of GreaterImageFilter in order to support a procedural API
See also
itk::simple::GreaterImageFilter for the object oriented interface
Greater() [2/5]
Image itk::simple::Greater (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Greater() [3/5]
Image itk::simple::Greater (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Greater() [4/5]
Image itk::simple::Greater (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of GreaterImageFilter in order to support a procedural API
See also
itk::simple::GreaterImageFilter for the object oriented interface
Greater() [5/5]
Image itk::simple::Greater (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
GreaterEqual() [1/5]
Image itk::simple::GreaterEqual (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of GreaterEqualImageFilter in order to support a procedural API
See also
itk::simple::GreaterEqualImageFilter for the object oriented interface
GreaterEqual() [2/5]
Image itk::simple::GreaterEqual (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
GreaterEqual() [3/5]
Image itk::simple::GreaterEqual (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
GreaterEqual() [4/5]
Image itk::simple::GreaterEqual (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of GreaterEqualImageFilter in order to support a procedural API
See also
itk::simple::GreaterEqualImageFilter for the object oriented interface
GreaterEqual() [5/5]
Image itk::simple::GreaterEqual (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
GridSource()
Image itk::simple::GridSource (PixelIDValueEnum outputPixelType = itk::simple::sitkFloat32, std::vector< unsigned int > size = std::vector< unsigned int >(3, 64), std::vector< double > sigma = std::vector< double >(3, 0.5), std::vector< double > gridSpacing = std::vector< double >(3, 4.0), std::vector< double > gridOffset = std::vector< double >(3, 0.0), double scale = 255.0, std::vector< double > origin = std::vector< double >(3, 0.0), std::vector< double > spacing = std::vector< double >(3, 1.0), std::vector< double > direction = std::vector< double >())
Generate an n-dimensional image of a grid.
This function directly calls the execute method of GridImageSource in order to support a procedural API
See also
itk::simple::GridImageSource for the object oriented interface
HalfHermitianToRealInverseFFT()
Image itk::simple::HalfHermitianToRealInverseFFT (const Image & image1, bool actualXDimensionIsOdd = false)
Base class for specialized complex-to-real inverse Fast Fourier Transform .
\
This function directly calls the execute method of HalfHermitianToRealInverseFFTImageFilter in order to support a procedural API
See also
itk::simple::HalfHermitianToRealInverseFFTImageFilter for the object oriented interface
Hash()
std::string itk::simple::Hash (const Image & image, HashImageFilter::HashFunction function = HashImageFilter::SHA1)
HConcave()
Image itk::simple::HConcave (const Image & image1, double height = 2.0, bool fullyConnected = false)
Identify local minima whose depth below the baseline is greater than h.
\
This function directly calls the execute method of HConcaveImageFilter in order to support a procedural API
See also
itk::simple::HConcaveImageFilter for the object oriented interface
HConvex()
Image itk::simple::HConvex (const Image & image1, double height = 2.0, bool fullyConnected = false)
Identify local maxima whose height above the baseline is greater than h.
\
This function directly calls the execute method of HConvexImageFilter in order to support a procedural API
See also
itk::simple::HConvexImageFilter for the object oriented interface
HistogramMatching()
Image itk::simple::HistogramMatching (const Image & image, const Image & referenceImage, uint32_t numberOfHistogramLevels = 256u, uint32_t numberOfMatchPoints = 1u, bool thresholdAtMeanIntensity = true)
Normalize the grayscale values for a source image by matching the shape of the source image histogram to a reference histogram.
\
This function directly calls the execute method of HistogramMatchingImageFilter in order to support a procedural API
See also
itk::simple::HistogramMatchingImageFilter for the object oriented interface
HMaxima()
Image itk::simple::HMaxima (const Image & image1, double height = 2.0)
Suppress local maxima whose height above the baseline is less than h.
\
This function directly calls the execute method of HMaximaImageFilter in order to support a procedural API
See also
itk::simple::HMaximaImageFilter for the object oriented interface
HMinima()
Image itk::simple::HMinima (const Image & image1, double height = 2.0, bool fullyConnected = false)
Suppress local minima whose depth below the baseline is less than h.
\
This function directly calls the execute method of HMinimaImageFilter in order to support a procedural API
See also
itk::simple::HMinimaImageFilter for the object oriented interface
HuangThreshold() [1/2]
Image itk::simple::HuangThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 128u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Huang Threshold.
\
This function directly calls the execute method of HuangThresholdImageFilter in order to support a procedural API
See also
itk::simple::HuangThresholdImageFilter for the object oriented interface
HuangThreshold() [2/2]
Image itk::simple::HuangThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 128u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Huang Threshold.
\
This function directly calls the execute method of HuangThresholdImageFilter in order to support a procedural API
See also
itk::simple::HuangThresholdImageFilter for the object oriented interface
ImportAsDouble()
Image SITKIO_EXPORT itk::simple::ImportAsDouble (double * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsFloat()
Image SITKIO_EXPORT itk::simple::ImportAsFloat (float * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsInt16()
Image SITKIO_EXPORT itk::simple::ImportAsInt16 (int16_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsInt32()
Image SITKIO_EXPORT itk::simple::ImportAsInt32 (int32_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsInt64()
Image SITKIO_EXPORT itk::simple::ImportAsInt64 (int64_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsInt8()
Image SITKIO_EXPORT itk::simple::ImportAsInt8 (int8_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsUInt16()
Image SITKIO_EXPORT itk::simple::ImportAsUInt16 (uint16_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsUInt32()
Image SITKIO_EXPORT itk::simple::ImportAsUInt32 (uint32_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsUInt64()
Image SITKIO_EXPORT itk::simple::ImportAsUInt64 (uint64_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
ImportAsUInt8()
Image SITKIO_EXPORT itk::simple::ImportAsUInt8 (uint8_t * buffer, const std::vector< unsigned int > & size, const std::vector< double > & spacing = std::vector< double >(3, 1.0), const std::vector< double > & origin = std::vector< double >(3, 0.0), const std::vector< double > & direction = std::vector< double >(), unsigned int numberOfComponents = 1)
IntensityWindowing() [1/2]
Image itk::simple::IntensityWindowing (const Image & image1, double windowMinimum = 0.0, double windowMaximum = 255.0, double outputMinimum = 0.0, double outputMaximum = 255.0)
Applies a linear transformation to the intensity levels of the input Image that are inside a user-defined interval. Values below this interval are mapped to a constant. Values over the interval are mapped to another constant.
\
This function directly calls the execute method of IntensityWindowingImageFilter in order to support a procedural API
See also
itk::simple::IntensityWindowingImageFilter for the object oriented interface
IntensityWindowing() [2/2]
Image itk::simple::IntensityWindowing (Image && image1, double windowMinimum = 0.0, double windowMaximum = 255.0, double outputMinimum = 0.0, double outputMaximum = 255.0)
Applies a linear transformation to the intensity levels of the input Image that are inside a user-defined interval. Values below this interval are mapped to a constant. Values over the interval are mapped to another constant.
\
This function directly calls the execute method of IntensityWindowingImageFilter in order to support a procedural API
See also
itk::simple::IntensityWindowingImageFilter for the object oriented interface
IntermodesThreshold() [1/2]
Image itk::simple::IntermodesThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Intermodes Threshold.
\
This function directly calls the execute method of IntermodesThresholdImageFilter in order to support a procedural API
See also
itk::simple::IntermodesThresholdImageFilter for the object oriented interface
IntermodesThreshold() [2/2]
Image itk::simple::IntermodesThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Intermodes Threshold.
\
This function directly calls the execute method of IntermodesThresholdImageFilter in order to support a procedural API
See also
itk::simple::IntermodesThresholdImageFilter for the object oriented interface
InverseDeconvolution()
Image itk::simple::InverseDeconvolution (const Image & image1, const Image & image2, double kernelZeroMagnitudeThreshold = 1.0e-4, bool normalize = false, InverseDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::InverseDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, InverseDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::InverseDeconvolutionImageFilter::SAME)
The direct linear inverse deconvolution filter.
\
This function directly calls the execute method of InverseDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::InverseDeconvolutionImageFilter for the object oriented interface
InverseDisplacementField()
Image itk::simple::InverseDisplacementField (const Image & image1, std::vector< uint32_t > size = std::vector< uint32_t >(3, 0), std::vector< double > outputOrigin = std::vector< double >(3, 0.0), std::vector< double > outputSpacing = std::vector< double >(3, 1.0), unsigned int subsamplingFactor = 16u)
Computes the inverse of a displacement field.
\
This function directly calls the execute method of InverseDisplacementFieldImageFilter in order to support a procedural API
See also
itk::simple::InverseDisplacementFieldImageFilter for the object oriented interface
InverseFFT()
Image itk::simple::InverseFFT (const Image & image1)
Base class for inverse Fast Fourier Transform .
\
This function directly calls the execute method of InverseFFTImageFilter in order to support a procedural API
See also
itk::simple::InverseFFTImageFilter for the object oriented interface
InvertDisplacementField()
Image itk::simple::InvertDisplacementField (const Image & image1, uint32_t maximumNumberOfIterations = 10u, double maxErrorToleranceThreshold = 0.1, double meanErrorToleranceThreshold = 0.001, bool enforceBoundaryCondition = true)
Iteratively estimate the inverse field of a displacement field.
\
This function directly calls the execute method of InvertDisplacementFieldImageFilter in order to support a procedural API
See also
itk::simple::InvertDisplacementFieldImageFilter for the object oriented interface
InvertIntensity() [1/2]
Image itk::simple::InvertIntensity (const Image & image1, double maximum = 255)
Invert the intensity of an image.
\
This function directly calls the execute method of InvertIntensityImageFilter in order to support a procedural API
See also
itk::simple::InvertIntensityImageFilter for the object oriented interface
InvertIntensity() [2/2]
Image itk::simple::InvertIntensity (Image && image1, double maximum = 255)
Invert the intensity of an image.
\
This function directly calls the execute method of InvertIntensityImageFilter in order to support a procedural API
See also
itk::simple::InvertIntensityImageFilter for the object oriented interface
IsoContourDistance()
Image itk::simple::IsoContourDistance (const Image & image1, double levelSetValue = 0.0, double farValue = 10)
Compute an approximate distance from an interpolated isocontour to the close grid points.
\
This function directly calls the execute method of IsoContourDistanceImageFilter in order to support a procedural API
See also
itk::simple::IsoContourDistanceImageFilter for the object oriented interface
IsoDataThreshold() [1/2]
Image itk::simple::IsoDataThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the IsoData Threshold.
\
This function directly calls the execute method of IsoDataThresholdImageFilter in order to support a procedural API
See also
itk::simple::IsoDataThresholdImageFilter for the object oriented interface
IsoDataThreshold() [2/2]
Image itk::simple::IsoDataThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the IsoData Threshold.
\
This function directly calls the execute method of IsoDataThresholdImageFilter in order to support a procedural API
See also
itk::simple::IsoDataThresholdImageFilter for the object oriented interface
IsolatedConnected()
Image itk::simple::IsolatedConnected (const Image & image1, std::vector< unsigned int > seed1 = std::vector< unsigned int >(3, 0), std::vector< unsigned int > seed2 = std::vector< unsigned int >(3, 0), double lower = 0, double upper = 1, uint8_t replaceValue = 1u, double isolatedValueTolerance = 1.0, bool findUpperThreshold = true)
Label pixels that are connected to one set of seeds but not another.
\
This function directly calls the execute method of IsolatedConnectedImageFilter in order to support a procedural API
See also
itk::simple::IsolatedConnectedImageFilter for the object oriented interface
IsolatedWatershed()
Image itk::simple::IsolatedWatershed (const Image & image1, std::vector< uint32_t > seed1 = std::vector< uint32_t >(3, 0), std::vector< uint32_t > seed2 = std::vector< uint32_t >(3, 0), double threshold = 0.0, double upperValueLimit = 1.0, double isolatedValueTolerance = 0.001, uint8_t replaceValue1 = 1u, uint8_t replaceValue2 = 2u)
Isolate watershed basins using two seeds.
\
This function directly calls the execute method of IsolatedWatershedImageFilter in order to support a procedural API
See also
itk::simple::IsolatedWatershedImageFilter for the object oriented interface
IterativeInverseDisplacementField()
Image itk::simple::IterativeInverseDisplacementField (const Image & image1, uint32_t numberOfIterations = 5u, double stopValue = 0.0)
Computes the inverse of a displacement field.
\
This function directly calls the execute method of IterativeInverseDisplacementFieldImageFilter in order to support a procedural API
See also
itk::simple::IterativeInverseDisplacementFieldImageFilter for the object oriented interface
JoinSeries() [1/6]
Image itk::simple::JoinSeries (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
JoinSeries() [2/6]
Image itk::simple::JoinSeries (const Image & image1, const Image & image2, const Image & image3, const Image & image4, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
JoinSeries() [3/6]
Image itk::simple::JoinSeries (const Image & image1, const Image & image2, const Image & image3, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
JoinSeries() [4/6]
Image itk::simple::JoinSeries (const Image & image1, const Image & image2, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
JoinSeries() [5/6]
Image itk::simple::JoinSeries (const Image & image1, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
JoinSeries() [6/6]
Image itk::simple::JoinSeries (const std::vector< Image > & images, double origin = 0.0, double spacing = 1.0)
Join N-D images into an (N+1)-D image.
This function directly calls the execute method of JoinSeriesImageFilter in order to support a procedural API
See also
itk::simple::JoinSeriesImageFilter for the object oriented interface
KittlerIllingworthThreshold() [1/2]
Image itk::simple::KittlerIllingworthThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the KittlerIllingworth Threshold.
\
This function directly calls the execute method of KittlerIllingworthThresholdImageFilter in order to support a procedural API
See also
itk::simple::KittlerIllingworthThresholdImageFilter for the object oriented interface
KittlerIllingworthThreshold() [2/2]
Image itk::simple::KittlerIllingworthThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the KittlerIllingworth Threshold.
\
This function directly calls the execute method of KittlerIllingworthThresholdImageFilter in order to support a procedural API
See also
itk::simple::KittlerIllingworthThresholdImageFilter for the object oriented interface
LabelContour() [1/2]
Image itk::simple::LabelContour (const Image & image1, bool fullyConnected = false, double backgroundValue = 0)
Labels the pixels on the border of the objects in a labeled image.
\
This function directly calls the execute method of LabelContourImageFilter in order to support a procedural API
See also
itk::simple::LabelContourImageFilter for the object oriented interface
LabelContour() [2/2]
Image itk::simple::LabelContour (Image && image1, bool fullyConnected = false, double backgroundValue = 0)
Labels the pixels on the border of the objects in a labeled image.
\
This function directly calls the execute method of LabelContourImageFilter in order to support a procedural API
See also
itk::simple::LabelContourImageFilter for the object oriented interface
LabelImageToLabelMap()
Image itk::simple::LabelImageToLabelMap (const Image & image1, double backgroundValue = 0)
convert a labeled image to a label collection image
\
This function directly calls the execute method of LabelImageToLabelMapFilter in order to support a procedural API
See also
itk::simple::LabelImageToLabelMapFilter for the object oriented interface
LabelMapContourOverlay()
Image itk::simple::LabelMapContourOverlay (const Image & labelMapImage, const Image & featureImage, double opacity = 0.5, std::vector< unsigned int > dilationRadius = std::vector< unsigned int >(3, 1), std::vector< unsigned int > contourThickness = std::vector< unsigned int >(3, 1), unsigned int sliceDimension = 0u, LabelMapContourOverlayImageFilter::ContourTypeType contourType = itk::simple::LabelMapContourOverlayImageFilter::CONTOUR, LabelMapContourOverlayImageFilter::PriorityType priority = itk::simple::LabelMapContourOverlayImageFilter::HIGH_LABEL_ON_TOP, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Apply a colormap to the contours (outlines) of each object in a label map and superimpose it on top of the feature image.
\
This function directly calls the execute method of LabelMapContourOverlayImageFilter in order to support a procedural API
See also
itk::simple::LabelMapContourOverlayImageFilter for the object oriented interface
LabelMapMask()
Image itk::simple::LabelMapMask (const Image & labelMapImage, const Image & featureImage, uint64_t label = 1u, double backgroundValue = 0, bool negated = false, bool crop = false, std::vector< unsigned int > cropBorder = std::vector< unsigned int >(3, 0))
Mask and image with a LabelMap .
\
This function directly calls the execute method of LabelMapMaskImageFilter in order to support a procedural API
See also
itk::simple::LabelMapMaskImageFilter for the object oriented interface
LabelMapOverlay()
Image itk::simple::LabelMapOverlay (const Image & labelMapImage, const Image & featureImage, double opacity = 0.5, std::vector< unsigned char > colormap = std::vector< unsigned char >())
Apply a colormap to a label map and superimpose it on an image.
\
This function directly calls the execute method of LabelMapOverlayImageFilter in order to support a procedural API
See also
itk::simple::LabelMapOverlayImageFilter for the object oriented interface
LabelMapToBinary()
Image itk::simple::LabelMapToBinary (const Image & image1, double backgroundValue = 0, double foregroundValue = 1.0)
Convert a LabelMap to a binary image.
\
This function directly calls the execute method of LabelMapToBinaryImageFilter in order to support a procedural API
See also
itk::simple::LabelMapToBinaryImageFilter for the object oriented interface
LabelMapToLabel()
Image itk::simple::LabelMapToLabel (const Image & image1)
Converts a LabelMap to a labeled image.
\
This function directly calls the execute method of LabelMapToLabelImageFilter in order to support a procedural API
See also
itk::simple::LabelMapToLabelImageFilter for the object oriented interface
LabelMapToRGB()
Image itk::simple::LabelMapToRGB (const Image & image1, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Convert a LabelMap to a colored image.
\
This function directly calls the execute method of LabelMapToRGBImageFilter in order to support a procedural API
See also
itk::simple::LabelMapToRGBImageFilter for the object oriented interface
LabelOverlay() [1/2]
Image itk::simple::LabelOverlay (const Image & image, const Image & labelImage, double opacity = 0.5, double backgroundValue = 0.0, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Apply a colormap to a label image and put it on top of the input image.
\
This function directly calls the execute method of LabelOverlayImageFilter in order to support a procedural API
See also
itk::simple::LabelOverlayImageFilter for the object oriented interface
LabelOverlay() [2/2]
Image itk::simple::LabelOverlay (Image && image, const Image & labelImage, double opacity = 0.5, double backgroundValue = 0.0, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Apply a colormap to a label image and put it on top of the input image.
\
This function directly calls the execute method of LabelOverlayImageFilter in order to support a procedural API
See also
itk::simple::LabelOverlayImageFilter for the object oriented interface
LabelToRGB() [1/2]
Image itk::simple::LabelToRGB (const Image & image1, double backgroundValue = 0.0, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Apply a colormap to a label image.
\
This function directly calls the execute method of LabelToRGBImageFilter in order to support a procedural API
See also
itk::simple::LabelToRGBImageFilter for the object oriented interface
LabelToRGB() [2/2]
Image itk::simple::LabelToRGB (Image && image1, double backgroundValue = 0.0, std::vector< uint8_t > colormap = std::vector< uint8_t >())
Apply a colormap to a label image.
\
This function directly calls the execute method of LabelToRGBImageFilter in order to support a procedural API
See also
itk::simple::LabelToRGBImageFilter for the object oriented interface
LabelUniqueLabelMap() [1/2]
Image itk::simple::LabelUniqueLabelMap (const Image & image1, bool reverseOrdering = false)
Make sure that the objects are not overlapping.
\
This function directly calls the execute method of LabelUniqueLabelMapFilter in order to support a procedural API
See also
itk::simple::LabelUniqueLabelMapFilter for the object oriented interface
LabelUniqueLabelMap() [2/2]
Image itk::simple::LabelUniqueLabelMap (Image && image1, bool reverseOrdering = false)
Make sure that the objects are not overlapping.
\
This function directly calls the execute method of LabelUniqueLabelMapFilter in order to support a procedural API
See also
itk::simple::LabelUniqueLabelMapFilter for the object oriented interface
LabelVoting() [1/6]
Image itk::simple::LabelVoting (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LabelVoting() [2/6]
Image itk::simple::LabelVoting (const Image & image1, const Image & image2, const Image & image3, const Image & image4, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LabelVoting() [3/6]
Image itk::simple::LabelVoting (const Image & image1, const Image & image2, const Image & image3, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LabelVoting() [4/6]
Image itk::simple::LabelVoting (const Image & image1, const Image & image2, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LabelVoting() [5/6]
Image itk::simple::LabelVoting (const Image & image1, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LabelVoting() [6/6]
Image itk::simple::LabelVoting (const std::vector< Image > & images, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max())
This filter performs pixelwise voting among an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of LabelVotingImageFilter in order to support a procedural API
See also
itk::simple::LabelVotingImageFilter for the object oriented interface
LandmarkBasedTransformInitializer()
Transform itk::simple::LandmarkBasedTransformInitializer (const Transform & transform, const std::vector< double > & fixedLandmarks = std::vector< double >(), const std::vector< double > & movingLandmarks = std::vector< double >(), const std::vector< double > & landmarkWeight = std::vector< double >(), const Image & referenceImage = Image(), unsigned int numberOfControlPoints = 4u)
itk::simple::LandmarkBasedTransformInitializerFilter Procedural Interface
This function directly calls the execute method of LandmarkBasedTransformInitializerFilter in order to support a procedural API
See also
itk::simple::LandmarkBasedTransformInitializerFilter for the object oriented interface
LandweberDeconvolution()
Image itk::simple::LandweberDeconvolution (const Image & image1, const Image & image2, double alpha = 0.1, int numberOfIterations = 1, bool normalize = false, LandweberDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::LandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, LandweberDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::LandweberDeconvolutionImageFilter::SAME)
Deconvolve an image using the Landweber deconvolution algorithm.
\
This function directly calls the execute method of LandweberDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::LandweberDeconvolutionImageFilter for the object oriented interface
Laplacian()
Image itk::simple::Laplacian (const Image & image1, bool useImageSpacing = true)
itk::simple::LaplacianImageFilter Procedural Interface
\
This function directly calls the execute method of LaplacianImageFilter in order to support a procedural API
See also
itk::simple::LaplacianImageFilter for the object oriented interface
LaplacianRecursiveGaussian()
Image itk::simple::LaplacianRecursiveGaussian (const Image & image1, double sigma = 1.0, bool normalizeAcrossScale = false)
Computes the Laplacian of Gaussian (LoG) of an image.
\
This function directly calls the execute method of LaplacianRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::LaplacianRecursiveGaussianImageFilter for the object oriented interface
LaplacianSegmentationLevelSet() [1/2]
Image itk::simple::LaplacianSegmentationLevelSet (const Image & initialImage, const Image & featureImage, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a second derivative image features.
\
This function directly calls the execute method of LaplacianSegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::LaplacianSegmentationLevelSetImageFilter for the object oriented interface
LaplacianSegmentationLevelSet() [2/2]
Image itk::simple::LaplacianSegmentationLevelSet (Image && initialImage, const Image & featureImage, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a second derivative image features.
\
This function directly calls the execute method of LaplacianSegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::LaplacianSegmentationLevelSetImageFilter for the object oriented interface
LaplacianSharpening()
Image itk::simple::LaplacianSharpening (const Image & image1, bool useImageSpacing = true)
This filter sharpens an image using a Laplacian. LaplacianSharpening highlights regions of rapid intensity change and therefore highlights or enhances the edges. The result is an image that appears more in focus.
\
This function directly calls the execute method of LaplacianSharpeningImageFilter in order to support a procedural API
See also
itk::simple::LaplacianSharpeningImageFilter for the object oriented interface
Less() [1/5]
Image itk::simple::Less (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of LessImageFilter in order to support a procedural API
See also
itk::simple::LessImageFilter for the object oriented interface
Less() [2/5]
Image itk::simple::Less (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Less() [3/5]
Image itk::simple::Less (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Less() [4/5]
Image itk::simple::Less (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of LessImageFilter in order to support a procedural API
See also
itk::simple::LessImageFilter for the object oriented interface
Less() [5/5]
Image itk::simple::Less (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
LessEqual() [1/5]
Image itk::simple::LessEqual (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of LessEqualImageFilter in order to support a procedural API
See also
itk::simple::LessEqualImageFilter for the object oriented interface
LessEqual() [2/5]
Image itk::simple::LessEqual (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
LessEqual() [3/5]
Image itk::simple::LessEqual (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
LessEqual() [4/5]
Image itk::simple::LessEqual (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of LessEqualImageFilter in order to support a procedural API
See also
itk::simple::LessEqualImageFilter for the object oriented interface
LessEqual() [5/5]
Image itk::simple::LessEqual (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
LiThreshold() [1/2]
Image itk::simple::LiThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Li Threshold.
\
This function directly calls the execute method of LiThresholdImageFilter in order to support a procedural API
See also
itk::simple::LiThresholdImageFilter for the object oriented interface
LiThreshold() [2/2]
Image itk::simple::LiThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Li Threshold.
\
This function directly calls the execute method of LiThresholdImageFilter in order to support a procedural API
See also
itk::simple::LiThresholdImageFilter for the object oriented interface
Log() [1/2]
Image itk::simple::Log (const Image & image1)
Computes the log() of each pixel.
\
This function directly calls the execute method of LogImageFilter in order to support a procedural API
See also
itk::simple::LogImageFilter for the object oriented interface
Log() [2/2]
Image itk::simple::Log (Image && image1)
Computes the log() of each pixel.
\
This function directly calls the execute method of LogImageFilter in order to support a procedural API
See also
itk::simple::LogImageFilter for the object oriented interface
Log10() [1/2]
Image itk::simple::Log10 (const Image & image1)
Computes the log10 of each pixel.
\
This function directly calls the execute method of Log10ImageFilter in order to support a procedural API
See also
itk::simple::Log10ImageFilter for the object oriented interface
Log10() [2/2]
Image itk::simple::Log10 (Image && image1)
Computes the log10 of each pixel.
\
This function directly calls the execute method of Log10ImageFilter in order to support a procedural API
See also
itk::simple::Log10ImageFilter for the object oriented interface
MagnitudeAndPhaseToComplex() [1/5]
Image itk::simple::MagnitudeAndPhaseToComplex (const Image & image1, const Image & image2)
Implements pixel-wise conversion of magnitude and phase data into complex voxels.
\
This function directly calls the execute method of MagnitudeAndPhaseToComplexImageFilter in order to support a procedural API
See also
itk::simple::MagnitudeAndPhaseToComplexImageFilter for the object oriented interface
MagnitudeAndPhaseToComplex() [2/5]
Image itk::simple::MagnitudeAndPhaseToComplex (const Image & image1, double constant)
MagnitudeAndPhaseToComplex() [3/5]
Image itk::simple::MagnitudeAndPhaseToComplex (double constant, const Image & image2)
MagnitudeAndPhaseToComplex() [4/5]
Image itk::simple::MagnitudeAndPhaseToComplex (Image && image1, const Image & image2)
Implements pixel-wise conversion of magnitude and phase data into complex voxels.
\
This function directly calls the execute method of MagnitudeAndPhaseToComplexImageFilter in order to support a procedural API
See also
itk::simple::MagnitudeAndPhaseToComplexImageFilter for the object oriented interface
MagnitudeAndPhaseToComplex() [5/5]
Image itk::simple::MagnitudeAndPhaseToComplex (Image && image1, double constant)
make_scope_exit()
template<typename F > scope_exit< F > itk::simple::make_scope_exit (F && f) noexcept
Definition at line 253 of file sitkTemplateFunctions.h.
Mask() [1/2]
Image itk::simple::Mask (const Image & image, const Image & maskImage, double outsideValue = 0, double maskingValue = 0)
Mask an image with a mask.
\
This function directly calls the execute method of MaskImageFilter in order to support a procedural API
See also
itk::simple::MaskImageFilter for the object oriented interface
Mask() [2/2]
Image itk::simple::Mask (Image && image, const Image & maskImage, double outsideValue = 0, double maskingValue = 0)
Mask an image with a mask.
\
This function directly calls the execute method of MaskImageFilter in order to support a procedural API
See also
itk::simple::MaskImageFilter for the object oriented interface
MaskedFFTNormalizedCorrelation()
Image itk::simple::MaskedFFTNormalizedCorrelation (const Image & fixedImage, const Image & movingImage, const Image & fixedImageMask, const Image & movingImageMask, uint64_t requiredNumberOfOverlappingPixels = 0u, float requiredFractionOfOverlappingPixels = 0.0)
Calculate masked normalized cross correlation using FFTs.
\
This function directly calls the execute method of MaskedFFTNormalizedCorrelationImageFilter in order to support a procedural API
See also
itk::simple::MaskedFFTNormalizedCorrelationImageFilter for the object oriented interface
MaskNegated() [1/2]
Image itk::simple::MaskNegated (const Image & image, const Image & maskImage, double outsideValue = 0, double maskingValue = 0)
Mask an image with the negation (or logical compliment) of a mask.
\
This function directly calls the execute method of MaskNegatedImageFilter in order to support a procedural API
See also
itk::simple::MaskNegatedImageFilter for the object oriented interface
MaskNegated() [2/2]
Image itk::simple::MaskNegated (Image && image, const Image & maskImage, double outsideValue = 0, double maskingValue = 0)
Mask an image with the negation (or logical compliment) of a mask.
\
This function directly calls the execute method of MaskNegatedImageFilter in order to support a procedural API
See also
itk::simple::MaskNegatedImageFilter for the object oriented interface
Maximum() [1/5]
Image itk::simple::Maximum (const Image & image1, const Image & image2)
Implements a pixel-wise operator Max(a,b) between two images.
\
This function directly calls the execute method of MaximumImageFilter in order to support a procedural API
See also
itk::simple::MaximumImageFilter for the object oriented interface
Maximum() [2/5]
Image itk::simple::Maximum (const Image & image1, double constant)
Maximum() [3/5]
Image itk::simple::Maximum (double constant, const Image & image2)
Maximum() [4/5]
Image itk::simple::Maximum (Image && image1, const Image & image2)
Implements a pixel-wise operator Max(a,b) between two images.
\
This function directly calls the execute method of MaximumImageFilter in order to support a procedural API
See also
itk::simple::MaximumImageFilter for the object oriented interface
Referenced by itk::simple::InvertIntensityImageFilter::SetMaximum().
Maximum() [5/5]
Image itk::simple::Maximum (Image && image1, double constant)
MaximumEntropyThreshold() [1/2]
Image itk::simple::MaximumEntropyThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the MaximumEntropy Threshold.
\
This function directly calls the execute method of MaximumEntropyThresholdImageFilter in order to support a procedural API
See also
itk::simple::MaximumEntropyThresholdImageFilter for the object oriented interface
MaximumEntropyThreshold() [2/2]
Image itk::simple::MaximumEntropyThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the MaximumEntropy Threshold.
\
This function directly calls the execute method of MaximumEntropyThresholdImageFilter in order to support a procedural API
See also
itk::simple::MaximumEntropyThresholdImageFilter for the object oriented interface
MaximumProjection()
Image itk::simple::MaximumProjection (const Image & image1, unsigned int projectionDimension = 0u)
Maximum projection.
\
This function directly calls the execute method of MaximumProjectionImageFilter in order to support a procedural API
See also
itk::simple::MaximumProjectionImageFilter for the object oriented interface
Mean()
Image itk::simple::Mean (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Applies an averaging filter to an image.
\
This function directly calls the execute method of MeanImageFilter in order to support a procedural API
See also
itk::simple::MeanImageFilter for the object oriented interface
Referenced by itk::simple::AdditiveGaussianNoiseImageFilter::SetMean(), itk::simple::GaborImageSource::SetMean(), and itk::simple::GaussianImageSource::SetMean().
MeanProjection()
Image itk::simple::MeanProjection (const Image & image1, unsigned int projectionDimension = 0u)
Mean projection.
\
This function directly calls the execute method of MeanProjectionImageFilter in order to support a procedural API
See also
itk::simple::MeanProjectionImageFilter for the object oriented interface
Median()
Image itk::simple::Median (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Applies a median filter to an image.
\
This function directly calls the execute method of MedianImageFilter in order to support a procedural API
See also
itk::simple::MedianImageFilter for the object oriented interface
MedianProjection()
Image itk::simple::MedianProjection (const Image & image1, unsigned int projectionDimension = 0u)
Median projection.
\
This function directly calls the execute method of MedianProjectionImageFilter in order to support a procedural API
See also
itk::simple::MedianProjectionImageFilter for the object oriented interface
MergeLabelMap() [1/6]
Image itk::simple::MergeLabelMap (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
MergeLabelMap() [2/6]
Image itk::simple::MergeLabelMap (const Image & image1, const Image & image2, const Image & image3, const Image & image4, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
MergeLabelMap() [3/6]
Image itk::simple::MergeLabelMap (const Image & image1, const Image & image2, const Image & image3, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
MergeLabelMap() [4/6]
Image itk::simple::MergeLabelMap (const Image & image1, const Image & image2, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
MergeLabelMap() [5/6]
Image itk::simple::MergeLabelMap (const Image & image1, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
MergeLabelMap() [6/6]
Image itk::simple::MergeLabelMap (const std::vector< Image > & images, MergeLabelMapFilter::MethodType method = itk::simple::MergeLabelMapFilter::Keep)
Merges several Label Maps.
This function directly calls the execute method of MergeLabelMapFilter in order to support a procedural API
See also
itk::simple::MergeLabelMapFilter for the object oriented interface
Minimum() [1/5]
Image itk::simple::Minimum (const Image & image1, const Image & image2)
Implements a pixel-wise operator Min(a,b) between two images.
\
This function directly calls the execute method of MinimumImageFilter in order to support a procedural API
See also
itk::simple::MinimumImageFilter for the object oriented interface
Minimum() [2/5]
Image itk::simple::Minimum (const Image & image1, double constant)
Minimum() [3/5]
Image itk::simple::Minimum (double constant, const Image & image2)
Minimum() [4/5]
Image itk::simple::Minimum (Image && image1, const Image & image2)
Implements a pixel-wise operator Min(a,b) between two images.
\
This function directly calls the execute method of MinimumImageFilter in order to support a procedural API
See also
itk::simple::MinimumImageFilter for the object oriented interface
Minimum() [5/5]
Image itk::simple::Minimum (Image && image1, double constant)
MinimumProjection()
Image itk::simple::MinimumProjection (const Image & image1, unsigned int projectionDimension = 0u)
Minimum projection.
\
This function directly calls the execute method of MinimumProjectionImageFilter in order to support a procedural API
See also
itk::simple::MinimumProjectionImageFilter for the object oriented interface
MinMaxCurvatureFlow() [1/2]
Image itk::simple::MinMaxCurvatureFlow (const Image & image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u, int stencilRadius = 2)
Denoise an image using min/max curvature flow.
\
This function directly calls the execute method of MinMaxCurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::MinMaxCurvatureFlowImageFilter for the object oriented interface
MinMaxCurvatureFlow() [2/2]
Image itk::simple::MinMaxCurvatureFlow (Image && image1, double timeStep = 0.05, uint32_t numberOfIterations = 5u, int stencilRadius = 2)
Denoise an image using min/max curvature flow.
\
This function directly calls the execute method of MinMaxCurvatureFlowImageFilter in order to support a procedural API
See also
itk::simple::MinMaxCurvatureFlowImageFilter for the object oriented interface
MirrorPad()
Image itk::simple::MirrorPad (const Image & image1, std::vector< unsigned int > padLowerBound = std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound = std::vector< unsigned int >(3, 0), double decayBase = 1.0)
Increase the image size by padding with replicants of the input image value.
\
This function directly calls the execute method of MirrorPadImageFilter in order to support a procedural API
See also
itk::simple::MirrorPadImageFilter for the object oriented interface
Modulus() [1/5]
Image itk::simple::Modulus (const Image & image1, const Image & image2)
Computes the modulus (x % dividend) pixel-wise.
\
This function directly calls the execute method of ModulusImageFilter in order to support a procedural API
See also
itk::simple::ModulusImageFilter for the object oriented interface
Modulus() [2/5]
Image itk::simple::Modulus (const Image & image1, uint32_t constant)
Modulus() [3/5]
Image itk::simple::Modulus (Image && image1, const Image & image2)
Computes the modulus (x % dividend) pixel-wise.
\
This function directly calls the execute method of ModulusImageFilter in order to support a procedural API
See also
itk::simple::ModulusImageFilter for the object oriented interface
Referenced by operator%(), and operator%=().
Modulus() [4/5]
Image itk::simple::Modulus (Image && image1, uint32_t constant)
Modulus() [5/5]
Image itk::simple::Modulus (uint32_t constant, const Image & image2)
MomentsThreshold() [1/2]
Image itk::simple::MomentsThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Moments Threshold.
\
This function directly calls the execute method of MomentsThresholdImageFilter in order to support a procedural API
See also
itk::simple::MomentsThresholdImageFilter for the object oriented interface
MomentsThreshold() [2/2]
Image itk::simple::MomentsThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Moments Threshold.
\
This function directly calls the execute method of MomentsThresholdImageFilter in order to support a procedural API
See also
itk::simple::MomentsThresholdImageFilter for the object oriented interface
MorphologicalGradient()
Image itk::simple::MorphologicalGradient (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall)
gray scale dilation of an image
\
This function directly calls the execute method of MorphologicalGradientImageFilter in order to support a procedural API
See also
itk::simple::MorphologicalGradientImageFilter for the object oriented interface
MorphologicalWatershed()
Image itk::simple::MorphologicalWatershed (const Image & image1, double level = 0.0, bool markWatershedLine = true, bool fullyConnected = false)
Watershed segmentation implementation with morphological operators.
\
This function directly calls the execute method of MorphologicalWatershedImageFilter in order to support a procedural API
See also
itk::simple::MorphologicalWatershedImageFilter for the object oriented interface
MorphologicalWatershedFromMarkers()
Image itk::simple::MorphologicalWatershedFromMarkers (const Image & image, const Image & markerImage, bool markWatershedLine = true, bool fullyConnected = false)
Morphological watershed transform from markers.
\
This function directly calls the execute method of MorphologicalWatershedFromMarkersImageFilter in order to support a procedural API
See also
itk::simple::MorphologicalWatershedFromMarkersImageFilter for the object oriented interface
MultiLabelSTAPLE() [1/6]
Image itk::simple::MultiLabelSTAPLE (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
MultiLabelSTAPLE() [2/6]
Image itk::simple::MultiLabelSTAPLE (const Image & image1, const Image & image2, const Image & image3, const Image & image4, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
MultiLabelSTAPLE() [3/6]
Image itk::simple::MultiLabelSTAPLE (const Image & image1, const Image & image2, const Image & image3, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
MultiLabelSTAPLE() [4/6]
Image itk::simple::MultiLabelSTAPLE (const Image & image1, const Image & image2, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
MultiLabelSTAPLE() [5/6]
Image itk::simple::MultiLabelSTAPLE (const Image & image1, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
MultiLabelSTAPLE() [6/6]
Image itk::simple::MultiLabelSTAPLE (const std::vector< Image > & images, uint64_t labelForUndecidedPixels = std::numeric_limits< uint64_t >::max(), float terminationUpdateThreshold = 1e-5f, unsigned int maximumNumberOfIterations = std::numeric_limits< unsigned int >::max(), std::vector< float > priorProbabilities = std::vector< float >())
This filter performs a pixelwise combination of an arbitrary number of input images, where each of them represents a segmentation of the same scene (i.e., image).
This function directly calls the execute method of MultiLabelSTAPLEImageFilter in order to support a procedural API
See also
itk::simple::MultiLabelSTAPLEImageFilter for the object oriented interface
Multiply() [1/5]
Image itk::simple::Multiply (const Image & image1, const Image & image2)
Pixel-wise multiplication of two images.
\
This function directly calls the execute method of MultiplyImageFilter in order to support a procedural API
See also
itk::simple::MultiplyImageFilter for the object oriented interface
Multiply() [2/5]
Image itk::simple::Multiply (const Image & image1, double constant)
Multiply() [3/5]
Image itk::simple::Multiply (double constant, const Image & image2)
Multiply() [4/5]
Image itk::simple::Multiply (Image && image1, const Image & image2)
Pixel-wise multiplication of two images.
\
This function directly calls the execute method of MultiplyImageFilter in order to support a procedural API
See also
itk::simple::MultiplyImageFilter for the object oriented interface
Referenced by operator*(), and operator*=().
Multiply() [5/5]
Image itk::simple::Multiply (Image && image1, double constant)
N4BiasFieldCorrection() [1/2]
Image itk::simple::N4BiasFieldCorrection (const Image & image, const Image & maskImage, double convergenceThreshold = 0.001, std::vector< uint32_t > maximumNumberOfIterations = std::vector< uint32_t >(4, 50), double biasFieldFullWidthAtHalfMaximum = 0.15, double wienerFilterNoise = 0.01, uint32_t numberOfHistogramBins = 200u, std::vector< uint32_t > numberOfControlPoints = std::vector< uint32_t >(3, 4), uint32_t splineOrder = 3u, bool useMaskLabel = true, uint8_t maskLabel = 1)
Implementation of the N4 bias field correction algorithm.
\
This function directly calls the execute method of N4BiasFieldCorrectionImageFilter in order to support a procedural API
See also
itk::simple::N4BiasFieldCorrectionImageFilter for the object oriented interface
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cs.
N4BiasFieldCorrection() [2/2]
Image itk::simple::N4BiasFieldCorrection (const Image & image, double convergenceThreshold = 0.001, std::vector< uint32_t > maximumNumberOfIterations = std::vector< uint32_t >(4, 50), double biasFieldFullWidthAtHalfMaximum = 0.15, double wienerFilterNoise = 0.01, uint32_t numberOfHistogramBins = 200u, std::vector< uint32_t > numberOfControlPoints = std::vector< uint32_t >(3, 4), uint32_t splineOrder = 3u, bool useMaskLabel = true, uint8_t maskLabel = 1)
Implementation of the N4 bias field correction algorithm.
\
This function directly calls the execute method of N4BiasFieldCorrectionImageFilter in order to support a procedural API
See also
itk::simple::N4BiasFieldCorrectionImageFilter for the object oriented interface
NaryAdd() [1/6]
Image itk::simple::NaryAdd (const Image & image1)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryAdd() [2/6]
Image itk::simple::NaryAdd (const Image & image1, const Image & image2)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryAdd() [3/6]
Image itk::simple::NaryAdd (const Image & image1, const Image & image2, const Image & image3)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryAdd() [4/6]
Image itk::simple::NaryAdd (const Image & image1, const Image & image2, const Image & image3, const Image & image4)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryAdd() [5/6]
Image itk::simple::NaryAdd (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryAdd() [6/6]
Image itk::simple::NaryAdd (const std::vector< Image > & images)
Pixel-wise addition of N images.
This function directly calls the execute method of NaryAddImageFilter in order to support a procedural API
See also
itk::simple::NaryAddImageFilter for the object oriented interface
NaryMaximum() [1/6]
Image itk::simple::NaryMaximum (const Image & image1)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NaryMaximum() [2/6]
Image itk::simple::NaryMaximum (const Image & image1, const Image & image2)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NaryMaximum() [3/6]
Image itk::simple::NaryMaximum (const Image & image1, const Image & image2, const Image & image3)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NaryMaximum() [4/6]
Image itk::simple::NaryMaximum (const Image & image1, const Image & image2, const Image & image3, const Image & image4)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NaryMaximum() [5/6]
Image itk::simple::NaryMaximum (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NaryMaximum() [6/6]
Image itk::simple::NaryMaximum (const std::vector< Image > & images)
Computes the pixel-wise maximum of several images.
This function directly calls the execute method of NaryMaximumImageFilter in order to support a procedural API
See also
itk::simple::NaryMaximumImageFilter for the object oriented interface
NeighborhoodConnected()
Image itk::simple::NeighborhoodConnected (const Image & image1, std::vector< std::vector< unsigned int > > seedList = std::vector< std::vector< unsigned int > >(), double lower = 0, double upper = 1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), double replaceValue = 1)
Label pixels that are connected to a seed and lie within a neighborhood.
\
This function directly calls the execute method of NeighborhoodConnectedImageFilter in order to support a procedural API
See also
itk::simple::NeighborhoodConnectedImageFilter for the object oriented interface
Noise()
Image itk::simple::Noise (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Calculate the local noise in an image.
\
This function directly calls the execute method of NoiseImageFilter in order to support a procedural API
See also
itk::simple::NoiseImageFilter for the object oriented interface
Normalize()
Image itk::simple::Normalize (const Image & image1)
Normalize an image by setting its mean to zero and variance to one.
\
This function directly calls the execute method of NormalizeImageFilter in order to support a procedural API
See also
itk::simple::NormalizeImageFilter for the object oriented interface
Examples
ImageRegistrationMethod2/ImageRegistrationMethod2.cxx.
Referenced by itk::simple::ConvolutionImageFilter::SetNormalize(), itk::simple::FFTConvolutionImageFilter::SetNormalize(), itk::simple::InverseDeconvolutionImageFilter::SetNormalize(), itk::simple::LandweberDeconvolutionImageFilter::SetNormalize(), itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetNormalize(), itk::simple::RichardsonLucyDeconvolutionImageFilter::SetNormalize(), itk::simple::TikhonovDeconvolutionImageFilter::SetNormalize(), and itk::simple::WienerDeconvolutionImageFilter::SetNormalize().
NormalizedCorrelation()
Image itk::simple::NormalizedCorrelation (const Image & image, const Image & maskImage, const Image & templateImage)
Computes the normalized correlation of an image and a template.
\
This function directly calls the execute method of NormalizedCorrelationImageFilter in order to support a procedural API
See also
itk::simple::NormalizedCorrelationImageFilter for the object oriented interface
NormalizeToConstant()
Image itk::simple::NormalizeToConstant (const Image & image1, double constant = 1.0)
Scales image pixel intensities to make the sum of all pixels equal a user-defined constant.
\
This function directly calls the execute method of NormalizeToConstantImageFilter in order to support a procedural API
See also
itk::simple::NormalizeToConstantImageFilter for the object oriented interface
Not() [1/2]
Image itk::simple::Not (const Image & image1)
Implements the NOT logical operator pixel-wise on an image.
\
This function directly calls the execute method of NotImageFilter in order to support a procedural API
See also
itk::simple::NotImageFilter for the object oriented interface
Not() [2/2]
Image itk::simple::Not (Image && image1)
Implements the NOT logical operator pixel-wise on an image.
\
This function directly calls the execute method of NotImageFilter in order to support a procedural API
See also
itk::simple::NotImageFilter for the object oriented interface
NotEqual() [1/5]
Image itk::simple::NotEqual (const Image & image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of NotEqualImageFilter in order to support a procedural API
See also
itk::simple::NotEqualImageFilter for the object oriented interface
NotEqual() [2/5]
Image itk::simple::NotEqual (const Image & image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
NotEqual() [3/5]
Image itk::simple::NotEqual (double constant, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
NotEqual() [4/5]
Image itk::simple::NotEqual (Image && image1, const Image & image2, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
Implements pixel-wise generic operation of two images, or of an image and a constant.
\
This function directly calls the execute method of NotEqualImageFilter in order to support a procedural API
See also
itk::simple::NotEqualImageFilter for the object oriented interface
NotEqual() [5/5]
Image itk::simple::NotEqual (Image && image1, double constant, uint8_t backgroundValue = 0u, uint8_t foregroundValue = 1u)
ObjectnessMeasure()
Image itk::simple::ObjectnessMeasure (const Image & image1, double alpha = 0.5, double beta = 0.5, double gamma = 5.0, bool scaleObjectnessMeasure = true, unsigned int objectDimension = 1u, bool brightObject = true)
Enhance M-dimensional objects in N-dimensional images.
\
This function directly calls the execute method of ObjectnessMeasureImageFilter in order to support a procedural API
See also
itk::simple::ObjectnessMeasureImageFilter for the object oriented interface
OpeningByReconstruction()
Image itk::simple::OpeningByReconstruction (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool fullyConnected = false, bool preserveIntensities = false)
Opening by reconstruction of an image.
\
This function directly calls the execute method of OpeningByReconstructionImageFilter in order to support a procedural API
See also
itk::simple::OpeningByReconstructionImageFilter for the object oriented interface
operator%() [1/5]
Image itk::simple::operator% (const Image & img, uint32_t s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 66 of file sitkImageOperators.h.
References Modulus().
operator%() [2/5]
Image itk::simple::operator% (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 64 of file sitkImageOperators.h.
References Modulus().
operator%() [3/5]
Image itk::simple::operator% (Image && img, uint32_t s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 67 of file sitkImageOperators.h.
References Modulus().
operator%() [4/5]
Image itk::simple::operator% (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 65 of file sitkImageOperators.h.
References Modulus().
operator%() [5/5]
Image itk::simple::operator% (uint32_t s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 68 of file sitkImageOperators.h.
References Modulus().
operator%=() [1/2]
Image & itk::simple::operator%= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 104 of file sitkImageOperators.h.
References Modulus().
operator%=() [2/2]
Image & itk::simple::operator%= (Image & img1, uint32_t s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 105 of file sitkImageOperators.h.
References Modulus().
operator&() [1/5]
Image itk::simple::operator& (const Image & img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 79 of file sitkImageOperators.h.
References And().
operator&() [2/5]
Image itk::simple::operator& (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 77 of file sitkImageOperators.h.
References And().
operator&() [3/5]
Image itk::simple::operator& (Image && img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 80 of file sitkImageOperators.h.
References And().
operator&() [4/5]
Image itk::simple::operator& (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 78 of file sitkImageOperators.h.
References And().
operator&() [5/5]
Image itk::simple::operator& (int s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 81 of file sitkImageOperators.h.
References And().
operator&=() [1/2]
Image & itk::simple::operator&= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 106 of file sitkImageOperators.h.
References And().
operator&=() [2/2]
Image & itk::simple::operator&= (Image & img1, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 107 of file sitkImageOperators.h.
References And().
operator*() [1/5]
Image itk::simple::operator* (const Image & img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 56 of file sitkImageOperators.h.
References Multiply().
operator*() [2/5]
Image itk::simple::operator* (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 54 of file sitkImageOperators.h.
References Multiply().
operator*() [3/5]
Image itk::simple::operator* (double s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 58 of file sitkImageOperators.h.
References Multiply().
operator*() [4/5]
Image itk::simple::operator* (Image && img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 57 of file sitkImageOperators.h.
References Multiply().
operator*() [5/5]
Image itk::simple::operator* (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 55 of file sitkImageOperators.h.
References Multiply().
operator*=() [1/2]
Image & itk::simple::operator*= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 100 of file sitkImageOperators.h.
References Multiply().
operator*=() [2/2]
Image & itk::simple::operator*= (Image & img1, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 101 of file sitkImageOperators.h.
References Multiply().
operator+() [1/5]
Image itk::simple::operator+ (const Image & img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 46 of file sitkImageOperators.h.
References Add().
operator+() [2/5]
Image itk::simple::operator+ (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 44 of file sitkImageOperators.h.
References Add().
operator+() [3/5]
Image itk::simple::operator+ (double s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 48 of file sitkImageOperators.h.
References Add().
operator+() [4/5]
Image itk::simple::operator+ (Image && img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 47 of file sitkImageOperators.h.
References Add().
operator+() [5/5]
Image itk::simple::operator+ (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 45 of file sitkImageOperators.h.
References Add().
operator+=() [1/2]
Image & itk::simple::operator+= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 96 of file sitkImageOperators.h.
References Add().
operator+=() [2/2]
Image & itk::simple::operator+= (Image & img1, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 97 of file sitkImageOperators.h.
References Add().
operator-() [1/7]
Image itk::simple::operator- (const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 70 of file sitkImageOperators.h.
References UnaryMinus().
operator-() [2/7]
Image itk::simple::operator- (const Image & img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 51 of file sitkImageOperators.h.
References Subtract().
operator-() [3/7]
Image itk::simple::operator- (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 49 of file sitkImageOperators.h.
References Subtract().
operator-() [4/7]
Image itk::simple::operator- (double s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 53 of file sitkImageOperators.h.
References Subtract().
operator-() [5/7]
Image itk::simple::operator- (Image && img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 71 of file sitkImageOperators.h.
References UnaryMinus().
operator-() [6/7]
Image itk::simple::operator- (Image && img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 52 of file sitkImageOperators.h.
References Subtract().
operator-() [7/7]
Image itk::simple::operator- (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 50 of file sitkImageOperators.h.
References Subtract().
operator-=() [1/2]
Image & itk::simple::operator-= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 98 of file sitkImageOperators.h.
References Subtract().
operator-=() [2/2]
Image & itk::simple::operator-= (Image & img1, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 99 of file sitkImageOperators.h.
References Subtract().
operator/() [1/5]
Image itk::simple::operator/ (const Image & img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 61 of file sitkImageOperators.h.
References Divide().
operator/() [2/5]
Image itk::simple::operator/ (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 59 of file sitkImageOperators.h.
References Divide().
operator/() [3/5]
Image itk::simple::operator/ (double s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 63 of file sitkImageOperators.h.
References Divide().
operator/() [4/5]
Image itk::simple::operator/ (Image && img, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 62 of file sitkImageOperators.h.
References Divide().
operator/() [5/5]
Image itk::simple::operator/ (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 60 of file sitkImageOperators.h.
References Divide().
operator/=() [1/2]
Image & itk::simple::operator/= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 102 of file sitkImageOperators.h.
References Divide().
operator/=() [2/2]
Image & itk::simple::operator/= (Image & img1, double s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 103 of file sitkImageOperators.h.
References Divide().
operator<<() [1/5]
SITKCommon_EXPORT std::ostream & itk::simple::operator<< (std::ostream & os, const EventEnum k)
operator<<() [2/5]
SITKCommon_EXPORT std::ostream & itk::simple::operator<< (std::ostream & os, const InterpolatorEnum i)
Convert Interpolator enum to a string for printing etc..
operator<<() [3/5]
SITKCommon_EXPORT std::ostream & itk::simple::operator<< (std::ostream & os, const KernelEnum k)
operator<<() [4/5]
SITKCommon_EXPORT std::ostream & itk::simple::operator<< (std::ostream & os, const PixelIDValueEnum id)
operator<<() [5/5]
template<typename T > SITKCommon_HIDDEN std::ostream & itk::simple::operator<< (std::ostream & os, const std::vector< T > & v)
Output the element of an std::vector to the output stream.
The elements of the std::vector are required to have operator<<.
The format of the output should be "[ T, T, T ]".
Definition at line 52 of file sitkTemplateFunctions.h.
operator^() [1/5]
Image itk::simple::operator^ (const Image & img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 91 of file sitkImageOperators.h.
References Xor().
operator^() [2/5]
Image itk::simple::operator^ (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 89 of file sitkImageOperators.h.
References Xor().
operator^() [3/5]
Image itk::simple::operator^ (Image && img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 92 of file sitkImageOperators.h.
References Xor().
operator^() [4/5]
Image itk::simple::operator^ (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 90 of file sitkImageOperators.h.
References Xor().
operator^() [5/5]
Image itk::simple::operator^ (int s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 93 of file sitkImageOperators.h.
References Xor().
operator^=() [1/2]
Image & itk::simple::operator^= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 110 of file sitkImageOperators.h.
References Xor().
operator^=() [2/2]
Image & itk::simple::operator^= (Image & img1, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 111 of file sitkImageOperators.h.
References Xor().
operator|() [1/5]
Image itk::simple::operator| (const Image & img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 85 of file sitkImageOperators.h.
References Or().
operator|() [2/5]
Image itk::simple::operator| (const Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 83 of file sitkImageOperators.h.
References Or().
operator|() [3/5]
Image itk::simple::operator| (Image && img, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 86 of file sitkImageOperators.h.
References Or().
operator|() [4/5]
Image itk::simple::operator| (Image && img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 84 of file sitkImageOperators.h.
References Or().
operator|() [5/5]
Image itk::simple::operator| (int s, const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 87 of file sitkImageOperators.h.
References Or().
operator|=() [1/2]
Image & itk::simple::operator|= (Image & img1, const Image & img2) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 108 of file sitkImageOperators.h.
References Or().
operator|=() [2/2]
Image & itk::simple::operator|= (Image & img1, int s) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 109 of file sitkImageOperators.h.
References Or().
operator~() [1/2]
Image itk::simple::operator~ (const Image & img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 74 of file sitkImageOperators.h.
References BitwiseNot().
operator~() [2/2]
Image itk::simple::operator~ (Image && img) inline
Performs the operator on a per pixel basis.
All overloaded simpleITK operators are performed on a per-pixel basis, and implemented with the corresponding image filters. These operators generally don't work with label images, and the logical operators don't work with images of real components or vector images.
Definition at line 75 of file sitkImageOperators.h.
References BitwiseNot().
Or() [1/5]
Image itk::simple::Or (const Image & image1, const Image & image2)
Implements the OR bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of OrImageFilter in order to support a procedural API
See also
itk::simple::OrImageFilter for the object oriented interface
Or() [2/5]
Image itk::simple::Or (const Image & image1, int constant)
Or() [3/5]
Image itk::simple::Or (Image && image1, const Image & image2)
Implements the OR bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of OrImageFilter in order to support a procedural API
See also
itk::simple::OrImageFilter for the object oriented interface
Referenced by operator|(), and operator|=().
Or() [4/5]
Image itk::simple::Or (Image && image1, int constant)
Or() [5/5]
Image itk::simple::Or (int constant, const Image & image2)
OtsuMultipleThresholds()
Image itk::simple::OtsuMultipleThresholds (const Image & image1, uint8_t numberOfThresholds = 1u, uint8_t labelOffset = 0u, uint32_t numberOfHistogramBins = 128u, bool valleyEmphasis = false, bool returnBinMidpoint = false)
Threshold an image using multiple Otsu Thresholds.
\
This function directly calls the execute method of OtsuMultipleThresholdsImageFilter in order to support a procedural API
See also
itk::simple::OtsuMultipleThresholdsImageFilter for the object oriented interface
OtsuThreshold() [1/2]
Image itk::simple::OtsuThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 128u, bool maskOutput = true, uint8_t maskValue = 255u, bool returnBinMidpoint = false)
Threshold an image using the Otsu Threshold.
\
This function directly calls the execute method of OtsuThresholdImageFilter in order to support a procedural API
See also
itk::simple::OtsuThresholdImageFilter for the object oriented interface
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
OtsuThreshold() [2/2]
Image itk::simple::OtsuThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 128u, bool maskOutput = true, uint8_t maskValue = 255u, bool returnBinMidpoint = false)
Threshold an image using the Otsu Threshold.
\
This function directly calls the execute method of OtsuThresholdImageFilter in order to support a procedural API
See also
itk::simple::OtsuThresholdImageFilter for the object oriented interface
Paste() [1/2]
Image itk::simple::Paste (const Image & destinationImage, const Image & sourceImage, std::vector< unsigned int > sourceSize = std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > sourceIndex = std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< int > destinationIndex = std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< bool > DestinationSkipAxes = std::vector< bool >())
Paste an image into another image.
\
This function directly calls the execute method of PasteImageFilter in order to support a procedural API
See also
itk::simple::PasteImageFilter for the object oriented interface
Paste() [2/2]
Image itk::simple::Paste (Image && destinationImage, const Image & sourceImage, std::vector< unsigned int > sourceSize = std::vector< unsigned int >(SITK_MAX_DIMENSION, 1), std::vector< int > sourceIndex = std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< int > destinationIndex = std::vector< int >(SITK_MAX_DIMENSION, 0), std::vector< bool > DestinationSkipAxes = std::vector< bool >())
Paste an image into another image.
\
This function directly calls the execute method of PasteImageFilter in order to support a procedural API
See also
itk::simple::PasteImageFilter for the object oriented interface
Examples
HelloWorld/HelloWorld.cxx.
PatchBasedDenoising() [1/2]
Image itk::simple::PatchBasedDenoising (const Image & image1, double kernelBandwidthSigma = 400.0, uint32_t patchRadius = 4u, uint32_t numberOfIterations = 1u, uint32_t numberOfSamplePatches = 200u, double sampleVariance = 400.0)
PatchBasedDenoising() [2/2]
Image itk::simple::PatchBasedDenoising (const Image & image1, itk::simple::PatchBasedDenoisingImageFilter::NoiseModelType noiseModel, double kernelBandwidthSigma = 400.0, uint32_t patchRadius = 4u, uint32_t numberOfIterations = 1u, uint32_t numberOfSamplePatches = 200u, double sampleVariance = 400.0, double noiseSigma = 0.0, double noiseModelFidelityWeight = 0.0)
itk::simple::PatchBasedDenoisingImageFilter Procedural Interface
This function directly calls the execute method of PatchBasedDenoisingImageFilter in order to support a procedural API
See also
itk::simple::PatchBasedDenoisingImageFilter for the object oriented interface
PermuteAxes()
Image itk::simple::PermuteAxes (const Image & image1, std::vector< unsigned int > order = std::vector< unsigned int >(itk::simple::PermuteAxesImageFilter::DefaultOrder))
Permutes the image axes according to a user specified order.
\
This function directly calls the execute method of PermuteAxesImageFilter in order to support a procedural API
See also
itk::simple::PermuteAxesImageFilter for the object oriented interface
PhysicalPointSource()
Image itk::simple::PhysicalPointSource (PixelIDValueEnum outputPixelType = itk::simple::sitkVectorFloat32, std::vector< unsigned int > size = std::vector< unsigned int >(3, 64), std::vector< double > origin = std::vector< double >(3, 0.0), std::vector< double > spacing = std::vector< double >(3, 1.0), std::vector< double > direction = std::vector< double >())
Generate an image of the physical locations of each pixel.
This function directly calls the execute method of PhysicalPointImageSource in order to support a procedural API
See also
itk::simple::PhysicalPointImageSource for the object oriented interface
Pow() [1/5]
Image itk::simple::Pow (const Image & image1, const Image & image2)
Computes the powers of 2 images.
\
This function directly calls the execute method of PowImageFilter in order to support a procedural API
See also
itk::simple::PowImageFilter for the object oriented interface
Pow() [2/5]
Image itk::simple::Pow (const Image & image1, double constant)
Pow() [3/5]
Image itk::simple::Pow (double constant, const Image & image2)
Pow() [4/5]
Image itk::simple::Pow (Image && image1, const Image & image2)
Computes the powers of 2 images.
\
This function directly calls the execute method of PowImageFilter in order to support a procedural API
See also
itk::simple::PowImageFilter for the object oriented interface
Pow() [5/5]
Image itk::simple::Pow (Image && image1, double constant)
ProjectedLandweberDeconvolution()
Image itk::simple::ProjectedLandweberDeconvolution (const Image & image1, const Image & image2, double alpha = 0.1, int numberOfIterations = 1, bool normalize = false, ProjectedLandweberDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::ProjectedLandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, ProjectedLandweberDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::ProjectedLandweberDeconvolutionImageFilter::SAME)
Deconvolve an image using the projected Landweber deconvolution algorithm.
\
This function directly calls the execute method of ProjectedLandweberDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::ProjectedLandweberDeconvolutionImageFilter for the object oriented interface
Rank()
Image itk::simple::Rank (const Image & image1, double rank = 0.5, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1))
Rank filter of a greyscale image.
\
This function directly calls the execute method of RankImageFilter in order to support a procedural API
See also
itk::simple::RankImageFilter for the object oriented interface
Referenced by itk::simple::FastApproximateRankImageFilter::SetRank(), and itk::simple::RankImageFilter::SetRank().
ReadImage() [1/2]
SITKIO_EXPORT Image itk::simple::ReadImage (const std::string & filename, PixelIDValueEnum outputPixelType = sitkUnknown, const std::string & imageIO = "")
ReadImage is a procedural interface to the ImageFileReader class which is convenient for most image reading tasks.
Parameters
filename the filename of an Image e.g. "cthead.mha"
outputPixelType see ImageReaderBase::SetOutputPixelType
imageIO see ImageReaderBase::SetImageIO
See also
itk::simple::ImageFileReader for reading a single file.
itk::simple::ImageSeriesReader for reading a series and meta-data dictionaries.
Examples
DemonsRegistration1/DemonsRegistration1.cxx, DemonsRegistration2/DemonsRegistration2.cxx, FastMarchingSegmentation/FastMarchingSegmentation.cxx, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx, N4BiasFieldCorrection/N4BiasFieldCorrection.cxx, SimpleGaussianFunctional.cxx, SimpleIO/SimpleIO.cxx, and SliceBySliceDecorator/SliceBySliceDecorator.cxx.
ReadImage() [2/2]
SITKIO_EXPORT Image itk::simple::ReadImage (const std::vector< std::string > & fileNames, PixelIDValueEnum outputPixelType = sitkUnknown, const std::string & imageIO = "")
ReadImage is a procedural interface to the ImageSeriesReader class which is convenient for most image reading tasks.
Parameters
fileNames a vector of file names
outputPixelType see ImageReaderBase::SetOutputPixelType
imageIO see ImageReaderBase::SetImageIO
Note
When reading a series of images that have meta-data associated with them (e.g. a DICOM series) the resulting image will have an empty meta-data dictionary. If you need the meta-data dictionaries associated with each slice then you should use the ImageSeriesReader class.
See also
itk::simple::ImageFileReader for reading a single file.
itk::simple::ImageSeriesReader for reading a series and meta-data dictionaries.
ReadTransform()
SITKCommon_EXPORT Transform itk::simple::ReadTransform (const std::string & filename)
Examples
DemonsRegistration2/DemonsRegistration2.cxx, and SimpleIO/SimpleIO.cxx.
RealAndImaginaryToComplex()
Image itk::simple::RealAndImaginaryToComplex (const Image & image1, const Image & image2)
ComposeImageFilter combine several scalar images into a multicomponent image.
\
This function directly calls the execute method of RealAndImaginaryToComplexImageFilter in order to support a procedural API
See also
itk::simple::RealAndImaginaryToComplexImageFilter for the object oriented interface
RealToHalfHermitianForwardFFT()
Image itk::simple::RealToHalfHermitianForwardFFT (const Image & image1)
Base class for specialized real-to-complex forward Fast Fourier Transform .
\
This function directly calls the execute method of RealToHalfHermitianForwardFFTImageFilter in order to support a procedural API
See also
itk::simple::RealToHalfHermitianForwardFFTImageFilter for the object oriented interface
ReconstructionByDilation()
Image itk::simple::ReconstructionByDilation (const Image & markerImage, const Image & maskImage, bool fullyConnected = false, bool useInternalCopy = true)
grayscale reconstruction by dilation of an image
\
This function directly calls the execute method of ReconstructionByDilationImageFilter in order to support a procedural API
See also
itk::simple::ReconstructionByDilationImageFilter for the object oriented interface
ReconstructionByErosion()
Image itk::simple::ReconstructionByErosion (const Image & markerImage, const Image & maskImage, bool fullyConnected = false, bool useInternalCopy = true)
grayscale reconstruction by erosion of an image
\
This function directly calls the execute method of ReconstructionByErosionImageFilter in order to support a procedural API
See also
itk::simple::ReconstructionByErosionImageFilter for the object oriented interface
RecursiveGaussian() [1/2]
Image itk::simple::RecursiveGaussian (const Image & image1, double sigma = 1.0, bool normalizeAcrossScale = false, RecursiveGaussianImageFilter::OrderType order = itk::simple::RecursiveGaussianImageFilter::ZeroOrder, unsigned int direction = 0u)
Base class for computing IIR convolution with an approximation of a Gaussian kernel.
\
This function directly calls the execute method of RecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::RecursiveGaussianImageFilter for the object oriented interface
RecursiveGaussian() [2/2]
Image itk::simple::RecursiveGaussian (Image && image1, double sigma = 1.0, bool normalizeAcrossScale = false, RecursiveGaussianImageFilter::OrderType order = itk::simple::RecursiveGaussianImageFilter::ZeroOrder, unsigned int direction = 0u)
Base class for computing IIR convolution with an approximation of a Gaussian kernel.
\
This function directly calls the execute method of RecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::RecursiveGaussianImageFilter for the object oriented interface
RegionalMaxima()
Image itk::simple::RegionalMaxima (const Image & image1, double backgroundValue = 0.0, double foregroundValue = 1.0, bool fullyConnected = false, bool flatIsMaxima = true)
Produce a binary image where foreground is the regional maxima of the input image.
\
This function directly calls the execute method of RegionalMaximaImageFilter in order to support a procedural API
See also
itk::simple::RegionalMaximaImageFilter for the object oriented interface
RegionalMinima()
Image itk::simple::RegionalMinima (const Image & image1, double backgroundValue = 0.0, double foregroundValue = 1.0, bool fullyConnected = false, bool flatIsMinima = true)
Produce a binary image where foreground is the regional minima of the input image.
\
This function directly calls the execute method of RegionalMinimaImageFilter in order to support a procedural API
See also
itk::simple::RegionalMinimaImageFilter for the object oriented interface
RegionOfInterest()
Image itk::simple::RegionOfInterest (const Image & image1, std::vector< unsigned int > size = std::vector< unsigned int >(3, 1), std::vector< int > index = std::vector< int >(3, 0))
Extract a region of interest from the input image.
\
This function directly calls the execute method of RegionOfInterestImageFilter in order to support a procedural API
See also
itk::simple::RegionOfInterestImageFilter for the object oriented interface
RelabelComponent() [1/2]
Image itk::simple::RelabelComponent (const Image & image1, uint64_t minimumObjectSize = 0u, bool sortByObjectSize = true)
Relabel the components in an image such that consecutive labels are used.
\
This function directly calls the execute method of RelabelComponentImageFilter in order to support a procedural API
See also
itk::simple::RelabelComponentImageFilter for the object oriented interface
RelabelComponent() [2/2]
Image itk::simple::RelabelComponent (Image && image1, uint64_t minimumObjectSize = 0u, bool sortByObjectSize = true)
Relabel the components in an image such that consecutive labels are used.
\
This function directly calls the execute method of RelabelComponentImageFilter in order to support a procedural API
See also
itk::simple::RelabelComponentImageFilter for the object oriented interface
RelabelLabelMap() [1/2]
Image itk::simple::RelabelLabelMap (const Image & image1, bool reverseOrdering = true)
This filter relabels the LabelObjects; the new labels are arranged consecutively with consideration for the background value.
\
This function directly calls the execute method of RelabelLabelMapFilter in order to support a procedural API
See also
itk::simple::RelabelLabelMapFilter for the object oriented interface
RelabelLabelMap() [2/2]
Image itk::simple::RelabelLabelMap (Image && image1, bool reverseOrdering = true)
This filter relabels the LabelObjects; the new labels are arranged consecutively with consideration for the background value.
\
This function directly calls the execute method of RelabelLabelMapFilter in order to support a procedural API
See also
itk::simple::RelabelLabelMapFilter for the object oriented interface
RenyiEntropyThreshold() [1/2]
Image itk::simple::RenyiEntropyThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the RenyiEntropy Threshold.
\
This function directly calls the execute method of RenyiEntropyThresholdImageFilter in order to support a procedural API
See also
itk::simple::RenyiEntropyThresholdImageFilter for the object oriented interface
RenyiEntropyThreshold() [2/2]
Image itk::simple::RenyiEntropyThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the RenyiEntropy Threshold.
\
This function directly calls the execute method of RenyiEntropyThresholdImageFilter in order to support a procedural API
See also
itk::simple::RenyiEntropyThresholdImageFilter for the object oriented interface
Resample() [1/3]
Image itk::simple::Resample (const Image & image1, const Image & referenceImage, Transform transform = itk::simple::Transform(), InterpolatorEnum interpolator = itk::simple::sitkLinear, double defaultPixelValue = 0.0, PixelIDValueEnum outputPixelType = sitkUnknown, bool useNearestNeighborExtrapolator = false)
itk::simple::ResampleImageFilter Procedural Interface
These functions call the execute method of ResampleImageFilter in order to support a procedural API.
The difference between the three functions is in the way the output image's domain parameters are specified (origin, spacing, direction). The first function uses the parameters from the input image, the second uses the parameters of a reference image, and the third uses explicitly specified parameters.
See also
itk::simple::ResampleImageFilter for the object oriented interface
Resample() [2/3]
Image itk::simple::Resample (const Image & image1, const std::vector< uint32_t > & size, Transform transform = itk::simple::Transform(), InterpolatorEnum interpolator = itk::simple::sitkLinear, const std::vector< double > & outputOrigin = std::vector< double >(3, 0.0), const std::vector< double > & outputSpacing = std::vector< double >(3, 1.0), const std::vector< double > & outputDirection = std::vector< double >(), double defaultPixelValue = 0.0, PixelIDValueEnum outputPixelType = sitkUnknown, bool useNearestNeighborExtrapolator = false)
itk::simple::ResampleImageFilter Procedural Interface
These functions call the execute method of ResampleImageFilter in order to support a procedural API.
The difference between the three functions is in the way the output image's domain parameters are specified (origin, spacing, direction). The first function uses the parameters from the input image, the second uses the parameters of a reference image, and the third uses explicitly specified parameters.
See also
itk::simple::ResampleImageFilter for the object oriented interface
Resample() [3/3]
Image itk::simple::Resample (const Image & image1, Transform transform = itk::simple::Transform(), InterpolatorEnum interpolator = itk::simple::sitkLinear, double defaultPixelValue = 0.0, PixelIDValueEnum outputPixelType = sitkUnknown, bool useNearestNeighborExtrapolator = false)
itk::simple::ResampleImageFilter Procedural Interface
These functions call the execute method of ResampleImageFilter in order to support a procedural API.
The difference between the three functions is in the way the output image's domain parameters are specified (origin, spacing, direction). The first function uses the parameters from the input image, the second uses the parameters of a reference image, and the third uses explicitly specified parameters.
See also
itk::simple::ResampleImageFilter for the object oriented interface
RescaleIntensity() [1/2]
Image itk::simple::RescaleIntensity (const Image & image1, double outputMinimum = 0, double outputMaximum = 255)
Applies a linear transformation to the intensity levels of the input Image .
\
This function directly calls the execute method of RescaleIntensityImageFilter in order to support a procedural API
See also
itk::simple::RescaleIntensityImageFilter for the object oriented interface
RescaleIntensity() [2/2]
Image itk::simple::RescaleIntensity (Image && image1, double outputMinimum = 0, double outputMaximum = 255)
Applies a linear transformation to the intensity levels of the input Image .
\
This function directly calls the execute method of RescaleIntensityImageFilter in order to support a procedural API
See also
itk::simple::RescaleIntensityImageFilter for the object oriented interface
RichardsonLucyDeconvolution()
Image itk::simple::RichardsonLucyDeconvolution (const Image & image1, const Image & image2, int numberOfIterations = 1, bool normalize = false, RichardsonLucyDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::RichardsonLucyDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, RichardsonLucyDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::RichardsonLucyDeconvolutionImageFilter::SAME)
Deconvolve an image using the Richardson-Lucy deconvolution algorithm.
\
This function directly calls the execute method of RichardsonLucyDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::RichardsonLucyDeconvolutionImageFilter for the object oriented interface
Round() [1/2]
Image itk::simple::Round (const Image & image1)
Rounds the value of each pixel.
\
This function directly calls the execute method of RoundImageFilter in order to support a procedural API
See also
itk::simple::RoundImageFilter for the object oriented interface
Round() [2/2]
Image itk::simple::Round (Image && image1)
Rounds the value of each pixel.
\
This function directly calls the execute method of RoundImageFilter in order to support a procedural API
See also
itk::simple::RoundImageFilter for the object oriented interface
SaltAndPepperNoise() [1/2]
Image itk::simple::SaltAndPepperNoise (const Image & image1, double probability = 0.01, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with fixed value impulse noise, often called salt and pepper noise.
\
This function directly calls the execute method of SaltAndPepperNoiseImageFilter in order to support a procedural API
See also
itk::simple::SaltAndPepperNoiseImageFilter for the object oriented interface
SaltAndPepperNoise() [2/2]
Image itk::simple::SaltAndPepperNoise (Image && image1, double probability = 0.01, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with fixed value impulse noise, often called salt and pepper noise.
\
This function directly calls the execute method of SaltAndPepperNoiseImageFilter in order to support a procedural API
See also
itk::simple::SaltAndPepperNoiseImageFilter for the object oriented interface
ScalarChanAndVeseDenseLevelSet()
Image itk::simple::ScalarChanAndVeseDenseLevelSet (const Image & initialImage, const Image & featureImage, double maximumRMSError = 0.02, uint32_t numberOfIterations = 1000u, double lambda1 = 1.0, double lambda2 = 1.0, double epsilon = 1.0, double curvatureWeight = 1.0, double areaWeight = 0.0, double reinitializationSmoothingWeight = 0.0, double volume = 0.0, double volumeMatchingWeight = 0.0, ScalarChanAndVeseDenseLevelSetImageFilter::HeavisideStepFunctionType heavisideStepFunction = itk::simple::ScalarChanAndVeseDenseLevelSetImageFilter::AtanRegularizedHeaviside, bool useImageSpacing = true)
Dense implementation of the Chan and Vese multiphase level set image filter.
\
This function directly calls the execute method of ScalarChanAndVeseDenseLevelSetImageFilter in order to support a procedural API
See also
itk::simple::ScalarChanAndVeseDenseLevelSetImageFilter for the object oriented interface
ScalarConnectedComponent() [1/2]
Image itk::simple::ScalarConnectedComponent (const Image & image, const Image & maskImage, double distanceThreshold = 0.0, bool fullyConnected = false)
A connected components filter that labels the objects in an arbitrary image. Two pixels are similar if they are within threshold of each other. Uses ConnectedComponentFunctorImageFilter .
\
This function directly calls the execute method of ScalarConnectedComponentImageFilter in order to support a procedural API
See also
itk::simple::ScalarConnectedComponentImageFilter for the object oriented interface
ScalarConnectedComponent() [2/2]
Image itk::simple::ScalarConnectedComponent (const Image & image, double distanceThreshold = 0.0, bool fullyConnected = false)
A connected components filter that labels the objects in an arbitrary image. Two pixels are similar if they are within threshold of each other. Uses ConnectedComponentFunctorImageFilter .
\
This function directly calls the execute method of ScalarConnectedComponentImageFilter in order to support a procedural API
See also
itk::simple::ScalarConnectedComponentImageFilter for the object oriented interface
ScalarImageKmeans()
Image itk::simple::ScalarImageKmeans (const Image & image1, std::vector< double > classWithInitialMean = std::vector< double >(), bool useNonContiguousLabels = false)
Classifies the intensity values of a scalar image using the K-Means algorithm.
\
This function directly calls the execute method of ScalarImageKmeansImageFilter in order to support a procedural API
See also
itk::simple::ScalarImageKmeansImageFilter for the object oriented interface
ScalarToRGBColormap()
Image itk::simple::ScalarToRGBColormap (const Image & image1, ScalarToRGBColormapImageFilter::ColormapType colormap = itk::simple::ScalarToRGBColormapImageFilter::Grey, bool useInputImageExtremaForScaling = true)
Implements pixel-wise intensity->rgb mapping operation on one image.
\
This function directly calls the execute method of ScalarToRGBColormapImageFilter in order to support a procedural API
See also
itk::simple::ScalarToRGBColormapImageFilter for the object oriented interface
ShanbhagThreshold() [1/2]
Image itk::simple::ShanbhagThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Shanbhag Threshold.
\
This function directly calls the execute method of ShanbhagThresholdImageFilter in order to support a procedural API
See also
itk::simple::ShanbhagThresholdImageFilter for the object oriented interface
ShanbhagThreshold() [2/2]
Image itk::simple::ShanbhagThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Shanbhag Threshold.
\
This function directly calls the execute method of ShanbhagThresholdImageFilter in order to support a procedural API
See also
itk::simple::ShanbhagThresholdImageFilter for the object oriented interface
ShapeDetectionLevelSet() [1/2]
Image itk::simple::ShapeDetectionLevelSet (const Image & initialImage, const Image & featureImage, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a user supplied edge potential map.
\
This function directly calls the execute method of ShapeDetectionLevelSetImageFilter in order to support a procedural API
See also
itk::simple::ShapeDetectionLevelSetImageFilter for the object oriented interface
ShapeDetectionLevelSet() [2/2]
Image itk::simple::ShapeDetectionLevelSet (Image && initialImage, const Image & featureImage, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on a user supplied edge potential map.
\
This function directly calls the execute method of ShapeDetectionLevelSetImageFilter in order to support a procedural API
See also
itk::simple::ShapeDetectionLevelSetImageFilter for the object oriented interface
ShiftScale()
Image itk::simple::ShiftScale (const Image & image1, double shift = 0, double scale = 1.0, PixelIDValueEnum outputPixelType = itk::simple::sitkUnknown)
Shift and scale the pixels in an image.
\
This function directly calls the execute method of ShiftScaleImageFilter in order to support a procedural API
See also
itk::simple::ShiftScaleImageFilter for the object oriented interface
ShotNoise() [1/2]
Image itk::simple::ShotNoise (const Image & image1, double scale = 1.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with shot noise.
\
This function directly calls the execute method of ShotNoiseImageFilter in order to support a procedural API
See also
itk::simple::ShotNoiseImageFilter for the object oriented interface
ShotNoise() [2/2]
Image itk::simple::ShotNoise (Image && image1, double scale = 1.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with shot noise.
\
This function directly calls the execute method of ShotNoiseImageFilter in order to support a procedural API
See also
itk::simple::ShotNoiseImageFilter for the object oriented interface
Show()
void SITKIO_EXPORT itk::simple::Show (const Image & image, const std::string & title = "", const bool debugOn = ProcessObject::GetGlobalDefaultDebug())
Display an image in an external viewer (Fiji by default)
This function directly calls the execute method of ImageViewer in order to support a procedural API
Examples
BufferImportExport.cxx, DicomSeriesReader/DicomSeriesReader.cxx, HelloWorld/HelloWorld.cxx, and N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Shrink()
Image itk::simple::Shrink (const Image & image1, std::vector< unsigned int > shrinkFactors = std::vector< unsigned int >(3, 1))
Reduce the size of an image by an integer factor in each dimension.
\
This function directly calls the execute method of ShrinkImageFilter in order to support a procedural API
See also
itk::simple::ShrinkImageFilter for the object oriented interface
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Sigmoid() [1/2]
Image itk::simple::Sigmoid (const Image & image1, double alpha = 1, double beta = 0, double outputMaximum = 255, double outputMinimum = 0)
Computes the sigmoid function pixel-wise.
\
This function directly calls the execute method of SigmoidImageFilter in order to support a procedural API
See also
itk::simple::SigmoidImageFilter for the object oriented interface
Sigmoid() [2/2]
Image itk::simple::Sigmoid (Image && image1, double alpha = 1, double beta = 0, double outputMaximum = 255, double outputMinimum = 0)
Computes the sigmoid function pixel-wise.
\
This function directly calls the execute method of SigmoidImageFilter in order to support a procedural API
See also
itk::simple::SigmoidImageFilter for the object oriented interface
SignedDanielssonDistanceMap()
Image itk::simple::SignedDanielssonDistanceMap (const Image & image1, bool insideIsPositive = false, bool squaredDistance = false, bool useImageSpacing = false)
itk::simple::SignedDanielssonDistanceMapImageFilter Procedural Interface
\
This function directly calls the execute method of SignedDanielssonDistanceMapImageFilter in order to support a procedural API
See also
itk::simple::SignedDanielssonDistanceMapImageFilter for the object oriented interface
SignedMaurerDistanceMap()
Image itk::simple::SignedMaurerDistanceMap (const Image & image1, bool insideIsPositive = false, bool squaredDistance = true, bool useImageSpacing = false, double backgroundValue = 0.0)
This filter calculates the Euclidean distance transform of a binary image in linear time for arbitrary dimensions.
\
This function directly calls the execute method of SignedMaurerDistanceMapImageFilter in order to support a procedural API
See also
itk::simple::SignedMaurerDistanceMapImageFilter for the object oriented interface
SimpleContourExtractor()
Image itk::simple::SimpleContourExtractor (const Image & image1, double inputForegroundValue = 1.0, double inputBackgroundValue = 0.0, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), double outputForegroundValue = 1.0, double outputBackgroundValue = 0.0)
Computes an image of contours which will be the contour of the first image.
\
This function directly calls the execute method of SimpleContourExtractorImageFilter in order to support a procedural API
See also
itk::simple::SimpleContourExtractorImageFilter for the object oriented interface
Sin() [1/2]
Image itk::simple::Sin (const Image & image1)
Computes the sine of each pixel.
\
This function directly calls the execute method of SinImageFilter in order to support a procedural API
See also
itk::simple::SinImageFilter for the object oriented interface
Sin() [2/2]
Image itk::simple::Sin (Image && image1)
Computes the sine of each pixel.
\
This function directly calls the execute method of SinImageFilter in order to support a procedural API
See also
itk::simple::SinImageFilter for the object oriented interface
sitkITKDirectionToSTL()
template<typename TDirectionType > std::vector< double > SITKCommon_HIDDEN itk::simple::sitkITKDirectionToSTL (const TDirectionType & d)
Definition at line 199 of file sitkTemplateFunctions.h.
sitkITKImageRegionToSTL()
template<unsigned int VImageDimension> std::vector< unsigned int > SITKCommon_HIDDEN itk::simple::sitkITKImageRegionToSTL (const ImageRegion< VImageDimension > & in)
Convert an ITK ImageRegion to and std::vector with the first part being the start index followed by the size.
Definition at line 160 of file sitkTemplateFunctions.h.
References itk::ImageRegion< VImageDimension >::GetIndex(), and itk::ImageRegion< VImageDimension >::GetSize().
sitkITKVectorToSTL() [1/2]
template<typename TType , typename TITKVector > std::vector< TType > SITKCommon_HIDDEN itk::simple::sitkITKVectorToSTL (const std::vector< TITKVector > & in)
Definition at line 139 of file sitkTemplateFunctions.h.
sitkITKVectorToSTL() [2/2]
template<typename TType , typename TITKVector > std::vector< TType > SITKCommon_HIDDEN itk::simple::sitkITKVectorToSTL (const TITKVector & in)
Convert an ITK fixed width vector to a std::vector.
Definition at line 109 of file sitkTemplateFunctions.h.
sitkITKVersorToSTL()
template<typename TType , typename T > std::vector< TType > SITKCommon_HIDDEN itk::simple::sitkITKVersorToSTL (const itk::Versor< T > & in)
Definition at line 222 of file sitkTemplateFunctions.h.
References itk::Versor< T >::GetW(), itk::Versor< T >::GetX(), itk::Versor< T >::GetY(), and itk::Versor< T >::GetZ().
sitkSTLToITKDirection()
template<typename TDirectionType > TDirectionType SITKCommon_HIDDEN itk::simple::sitkSTLToITKDirection (const std::vector< double > & direction)
Definition at line 177 of file sitkTemplateFunctions.h.
References sitkExceptionMacro.
sitkSTLVectorToITK()
template<typename TITKVector , typename TType > TITKVector SITKCommon_HIDDEN itk::simple::sitkSTLVectorToITK (const std::vector< TType > & in)
Copy the elements of an std::vector into an ITK fixed width vector.
If there are more elements in parameter "in" than the templated ITK vector type, they are truncated. If less, then an exception is generated.
Definition at line 89 of file sitkTemplateFunctions.h.
References sitkExceptionMacro.
sitkSTLVectorToITKPointVector()
template<typename TITKPointVector , typename TType > TITKPointVector SITKCommon_HIDDEN itk::simple::sitkSTLVectorToITKPointVector (const std::vector< TType > & in)
Definition at line 65 of file sitkTemplateFunctions.h.
References Dimension.
sitkSTLVectorToITKVersor()
template<typename T , typename TType > itk::Versor< T > SITKCommon_HIDDEN itk::simple::sitkSTLVectorToITKVersor (const std::vector< TType > & in)
Definition at line 206 of file sitkTemplateFunctions.h.
References sitkExceptionMacro.
sitkVectorOfITKVectorToSTL()
template<typename TType , typename TVectorOfITKVector > std::vector< TType > SITKCommon_HIDDEN itk::simple::sitkVectorOfITKVectorToSTL (const TVectorOfITKVector & in)
Convert an ITK style array of ITK fixed width vector to std::vector.
An example input type is itk::FixedArray<itk::Point<3>, 3>
Definition at line 124 of file sitkTemplateFunctions.h.
SLIC()
Image itk::simple::SLIC (const Image & image1, std::vector< unsigned int > superGridSize = std::vector< unsigned int >(3, 50), double spatialProximityWeight = 10.0, uint32_t maximumNumberOfIterations = 5u, bool enforceConnectivity = true, bool initializationPerturbation = true)
Simple Linear Iterative Clustering (SLIC) super-pixel segmentation.
\
This function directly calls the execute method of SLICImageFilter in order to support a procedural API
See also
itk::simple::SLICImageFilter for the object oriented interface
Slice()
Image itk::simple::Slice (const Image & image1, std::vector< int32_t > start = std::vector< int32_t >(3, 0), std::vector< int32_t > stop = std::vector< int32_t >(3, std::numeric_limits< int32_t >::max()), std::vector< int > step = std::vector< int >(3, 1))
Slices an image based on a starting index and a stopping index, and a step size.
\
This function directly calls the execute method of SliceImageFilter in order to support a procedural API
See also
itk::simple::SliceImageFilter for the object oriented interface
SmoothingRecursiveGaussian() [1/3]
Image itk::simple::SmoothingRecursiveGaussian (const Image & image1, double sigma, bool normalizeAcrossScale = false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
This function directly calls the execute method of SmoothingRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::SmoothingRecursiveGaussianImageFilter for the object oriented interface
SmoothingRecursiveGaussian() [2/3]
Image itk::simple::SmoothingRecursiveGaussian (const Image & image1, std::vector< double > sigma = std::vector< double >(3, 1.0), bool normalizeAcrossScale = false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
\
This function directly calls the execute method of SmoothingRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::SmoothingRecursiveGaussianImageFilter for the object oriented interface
SmoothingRecursiveGaussian() [3/3]
Image itk::simple::SmoothingRecursiveGaussian (Image && image1, std::vector< double > sigma = std::vector< double >(3, 1.0), bool normalizeAcrossScale = false)
Computes the smoothing of an image by convolution with the Gaussian kernels implemented as IIR filters.
\
This function directly calls the execute method of SmoothingRecursiveGaussianImageFilter in order to support a procedural API
See also
itk::simple::SmoothingRecursiveGaussianImageFilter for the object oriented interface
Examples
SimpleGaussianFunctional.cxx.
SobelEdgeDetection()
Image itk::simple::SobelEdgeDetection (const Image & image1)
A 2D or 3D edge detection using the Sobel operator.
\
This function directly calls the execute method of SobelEdgeDetectionImageFilter in order to support a procedural API
See also
itk::simple::SobelEdgeDetectionImageFilter for the object oriented interface
SpeckleNoise() [1/2]
Image itk::simple::SpeckleNoise (const Image & image1, double standardDeviation = 1.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with speckle (multiplicative) noise.
\
This function directly calls the execute method of SpeckleNoiseImageFilter in order to support a procedural API
See also
itk::simple::SpeckleNoiseImageFilter for the object oriented interface
SpeckleNoise() [2/2]
Image itk::simple::SpeckleNoise (Image && image1, double standardDeviation = 1.0, uint32_t seed = (uint32_t) itk::simple::sitkWallClock)
Alter an image with speckle (multiplicative) noise.
\
This function directly calls the execute method of SpeckleNoiseImageFilter in order to support a procedural API
See also
itk::simple::SpeckleNoiseImageFilter for the object oriented interface
Sqrt() [1/2]
Image itk::simple::Sqrt (const Image & image1)
Computes the square root of each pixel.
\
This function directly calls the execute method of SqrtImageFilter in order to support a procedural API
See also
itk::simple::SqrtImageFilter for the object oriented interface
Sqrt() [2/2]
Image itk::simple::Sqrt (Image && image1)
Computes the square root of each pixel.
\
This function directly calls the execute method of SqrtImageFilter in order to support a procedural API
See also
itk::simple::SqrtImageFilter for the object oriented interface
Square() [1/2]
Image itk::simple::Square (const Image & image1)
Computes the square of the intensity values pixel-wise.
\
This function directly calls the execute method of SquareImageFilter in order to support a procedural API
See also
itk::simple::SquareImageFilter for the object oriented interface
Square() [2/2]
Image itk::simple::Square (Image && image1)
Computes the square of the intensity values pixel-wise.
\
This function directly calls the execute method of SquareImageFilter in order to support a procedural API
See also
itk::simple::SquareImageFilter for the object oriented interface
SquaredDifference() [1/5]
Image itk::simple::SquaredDifference (const Image & image1, const Image & image2)
Implements pixel-wise the computation of squared difference.
\
This function directly calls the execute method of SquaredDifferenceImageFilter in order to support a procedural API
See also
itk::simple::SquaredDifferenceImageFilter for the object oriented interface
SquaredDifference() [2/5]
Image itk::simple::SquaredDifference (const Image & image1, double constant)
SquaredDifference() [3/5]
Image itk::simple::SquaredDifference (double constant, const Image & image2)
SquaredDifference() [4/5]
Image itk::simple::SquaredDifference (Image && image1, const Image & image2)
Implements pixel-wise the computation of squared difference.
\
This function directly calls the execute method of SquaredDifferenceImageFilter in order to support a procedural API
See also
itk::simple::SquaredDifferenceImageFilter for the object oriented interface
SquaredDifference() [5/5]
Image itk::simple::SquaredDifference (Image && image1, double constant)
StandardDeviationProjection()
Image itk::simple::StandardDeviationProjection (const Image & image1, unsigned int projectionDimension = 0u)
Mean projection.
\
This function directly calls the execute method of StandardDeviationProjectionImageFilter in order to support a procedural API
See also
itk::simple::StandardDeviationProjectionImageFilter for the object oriented interface
STAPLE() [1/6]
Image itk::simple::STAPLE (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
STAPLE() [2/6]
Image itk::simple::STAPLE (const Image & image1, const Image & image2, const Image & image3, const Image & image4, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
STAPLE() [3/6]
Image itk::simple::STAPLE (const Image & image1, const Image & image2, const Image & image3, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
STAPLE() [4/6]
Image itk::simple::STAPLE (const Image & image1, const Image & image2, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
STAPLE() [5/6]
Image itk::simple::STAPLE (const Image & image1, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
STAPLE() [6/6]
Image itk::simple::STAPLE (const std::vector< Image > & images, double confidenceWeight = 1.0, double foregroundValue = 1.0, unsigned int maximumIterations = std::numeric_limits< unsigned int >::max())
The STAPLE filter implements the Simultaneous Truth and Performance Level Estimation algorithm for generating ground truth volumes from a set of binary expert segmentations.
This function directly calls the execute method of STAPLEImageFilter in order to support a procedural API
See also
itk::simple::STAPLEImageFilter for the object oriented interface
StochasticFractalDimension() [1/2]
Image itk::simple::StochasticFractalDimension (const Image & image, const Image & maskImage, std::vector< unsigned int > neighborhoodRadius = std::vector< unsigned int >(3, 2u))
This filter computes the stochastic fractal dimension of the input image.
\
This function directly calls the execute method of StochasticFractalDimensionImageFilter in order to support a procedural API
See also
itk::simple::StochasticFractalDimensionImageFilter for the object oriented interface
StochasticFractalDimension() [2/2]
Image itk::simple::StochasticFractalDimension (const Image & image, std::vector< unsigned int > neighborhoodRadius = std::vector< unsigned int >(3, 2u))
This filter computes the stochastic fractal dimension of the input image.
\
This function directly calls the execute method of StochasticFractalDimensionImageFilter in order to support a procedural API
See also
itk::simple::StochasticFractalDimensionImageFilter for the object oriented interface
Subtract() [1/5]
Image itk::simple::Subtract (const Image & image1, const Image & image2)
Pixel-wise subtraction of two images.
\
This function directly calls the execute method of SubtractImageFilter in order to support a procedural API
See also
itk::simple::SubtractImageFilter for the object oriented interface
Subtract() [2/5]
Image itk::simple::Subtract (const Image & image1, double constant)
Subtract() [3/5]
Image itk::simple::Subtract (double constant, const Image & image2)
Subtract() [4/5]
Image itk::simple::Subtract (Image && image1, const Image & image2)
Pixel-wise subtraction of two images.
\
This function directly calls the execute method of SubtractImageFilter in order to support a procedural API
See also
itk::simple::SubtractImageFilter for the object oriented interface
Examples
CppInPlace/CppInPlace.cxx.
Referenced by operator-(), and operator-=().
Subtract() [5/5]
Image itk::simple::Subtract (Image && image1, double constant)
SumProjection()
Image itk::simple::SumProjection (const Image & image1, unsigned int projectionDimension = 0u)
Sum projection.
\
This function directly calls the execute method of SumProjectionImageFilter in order to support a procedural API
See also
itk::simple::SumProjectionImageFilter for the object oriented interface
Tan() [1/2]
Image itk::simple::Tan (const Image & image1)
Computes the tangent of each input pixel.
\
This function directly calls the execute method of TanImageFilter in order to support a procedural API
See also
itk::simple::TanImageFilter for the object oriented interface
Tan() [2/2]
Image itk::simple::Tan (Image && image1)
Computes the tangent of each input pixel.
\
This function directly calls the execute method of TanImageFilter in order to support a procedural API
See also
itk::simple::TanImageFilter for the object oriented interface
TernaryAdd() [1/2]
Image itk::simple::TernaryAdd (const Image & image1, const Image & image2, const Image & image3)
Pixel-wise addition of three images.
\
This function directly calls the execute method of TernaryAddImageFilter in order to support a procedural API
See also
itk::simple::TernaryAddImageFilter for the object oriented interface
TernaryAdd() [2/2]
Image itk::simple::TernaryAdd (Image && image1, const Image & image2, const Image & image3)
Pixel-wise addition of three images.
\
This function directly calls the execute method of TernaryAddImageFilter in order to support a procedural API
See also
itk::simple::TernaryAddImageFilter for the object oriented interface
TernaryMagnitude() [1/2]
Image itk::simple::TernaryMagnitude (const Image & image1, const Image & image2, const Image & image3)
Compute the pixel-wise magnitude of three images.
\
This function directly calls the execute method of TernaryMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::TernaryMagnitudeImageFilter for the object oriented interface
TernaryMagnitude() [2/2]
Image itk::simple::TernaryMagnitude (Image && image1, const Image & image2, const Image & image3)
Compute the pixel-wise magnitude of three images.
\
This function directly calls the execute method of TernaryMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::TernaryMagnitudeImageFilter for the object oriented interface
TernaryMagnitudeSquared() [1/2]
Image itk::simple::TernaryMagnitudeSquared (const Image & image1, const Image & image2, const Image & image3)
Compute the pixel-wise squared magnitude of three images.
\
This function directly calls the execute method of TernaryMagnitudeSquaredImageFilter in order to support a procedural API
See also
itk::simple::TernaryMagnitudeSquaredImageFilter for the object oriented interface
TernaryMagnitudeSquared() [2/2]
Image itk::simple::TernaryMagnitudeSquared (Image && image1, const Image & image2, const Image & image3)
Compute the pixel-wise squared magnitude of three images.
\
This function directly calls the execute method of TernaryMagnitudeSquaredImageFilter in order to support a procedural API
See also
itk::simple::TernaryMagnitudeSquaredImageFilter for the object oriented interface
Threshold() [1/2]
Image itk::simple::Threshold (const Image & image1, double lower = 0.0, double upper = 1.0, double outsideValue = 0.0)
Set image values to a user-specified value if they are below, above, or between simple threshold values.
\
This function directly calls the execute method of ThresholdImageFilter in order to support a procedural API
See also
itk::simple::ThresholdImageFilter for the object oriented interface
Threshold() [2/2]
Image itk::simple::Threshold (Image && image1, double lower = 0.0, double upper = 1.0, double outsideValue = 0.0)
Set image values to a user-specified value if they are below, above, or between simple threshold values.
\
This function directly calls the execute method of ThresholdImageFilter in order to support a procedural API
See also
itk::simple::ThresholdImageFilter for the object oriented interface
Referenced by itk::simple::BinaryMinMaxCurvatureFlowImageFilter::SetThreshold(), itk::simple::CannySegmentationLevelSetImageFilter::SetThreshold(), itk::simple::IsolatedWatershedImageFilter::SetThreshold(), and itk::simple::UnsharpMaskImageFilter::SetThreshold().
ThresholdMaximumConnectedComponents()
Image itk::simple::ThresholdMaximumConnectedComponents (const Image & image1, uint32_t minimumObjectSizeInPixels = 0u, double upperBoundary = std::numeric_limits< double >::max(), uint8_t insideValue = 1u, uint8_t outsideValue = 0u)
Finds the threshold value of an image based on maximizing the number of objects in the image that are larger than a given minimal size.
\
This function directly calls the execute method of ThresholdMaximumConnectedComponentsImageFilter in order to support a procedural API
See also
itk::simple::ThresholdMaximumConnectedComponentsImageFilter for the object oriented interface
ThresholdSegmentationLevelSet() [1/2]
Image itk::simple::ThresholdSegmentationLevelSet (const Image & initialImage, const Image & featureImage, double lowerThreshold = 0.0, double upperThreshold = 255.0, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on intensity values.
\
This function directly calls the execute method of ThresholdSegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::ThresholdSegmentationLevelSetImageFilter for the object oriented interface
ThresholdSegmentationLevelSet() [2/2]
Image itk::simple::ThresholdSegmentationLevelSet (Image && initialImage, const Image & featureImage, double lowerThreshold = 0.0, double upperThreshold = 255.0, double maximumRMSError = 0.02, double propagationScaling = 1.0, double curvatureScaling = 1.0, uint32_t numberOfIterations = 1000u, bool reverseExpansionDirection = false)
Segments structures in images based on intensity values.
\
This function directly calls the execute method of ThresholdSegmentationLevelSetImageFilter in order to support a procedural API
See also
itk::simple::ThresholdSegmentationLevelSetImageFilter for the object oriented interface
TikhonovDeconvolution()
Image itk::simple::TikhonovDeconvolution (const Image & image1, const Image & image2, double regularizationConstant = 0.0, bool normalize = false, TikhonovDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::TikhonovDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, TikhonovDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::TikhonovDeconvolutionImageFilter::SAME)
An inverse deconvolution filter regularized in the Tikhonov sense.
\
This function directly calls the execute method of TikhonovDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::TikhonovDeconvolutionImageFilter for the object oriented interface
Tile() [1/6]
Image itk::simple::Tile (const Image & image1, const Image & image2, const Image & image3, const Image & image4, const Image & image5, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Tile() [2/6]
Image itk::simple::Tile (const Image & image1, const Image & image2, const Image & image3, const Image & image4, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Tile() [3/6]
Image itk::simple::Tile (const Image & image1, const Image & image2, const Image & image3, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Tile() [4/6]
Image itk::simple::Tile (const Image & image1, const Image & image2, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Tile() [5/6]
Image itk::simple::Tile (const Image & image1, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Tile() [6/6]
Image itk::simple::Tile (const std::vector< Image > & images, std::vector< uint32_t > layout = std::vector< uint32_t >(3, 100), double defaultPixelValue = 0.0)
Tile multiple input images into a single output image.
This function directly calls the execute method of TileImageFilter in order to support a procedural API
See also
itk::simple::TileImageFilter for the object oriented interface
Toboggan()
Image itk::simple::Toboggan (const Image & image1)
toboggan image segmentation The Toboggan segmentation takes a gradient magnitude image as input and produces an (over-)segmentation of the image based on connecting each pixel to a local minimum of gradient. It is roughly equivalent to a watershed segmentation of the lowest level.
\
This function directly calls the execute method of TobogganImageFilter in order to support a procedural API
See also
itk::simple::TobogganImageFilter for the object oriented interface
TransformGeometry() [1/2]
Image itk::simple::TransformGeometry (const Image & image, const Transform & transform)
itk::simple::TransformGeometryImageFilter Procedural Interface
\
This function directly calls the execute method of TransformGeometryImageFilter in order to support a procedural API
See also
itk::simple::TransformGeometryImageFilter for the object oriented interface
TransformGeometry() [2/2]
Image itk::simple::TransformGeometry (Image && image, const Transform & transform)
itk::simple::TransformGeometryImageFilter Procedural Interface
\
This function directly calls the execute method of TransformGeometryImageFilter in order to support a procedural API
See also
itk::simple::TransformGeometryImageFilter for the object oriented interface
TransformToDisplacementField()
Image itk::simple::TransformToDisplacementField (const Transform & transform, PixelIDValueEnum outputPixelType = itk::simple::sitkVectorFloat64, std::vector< unsigned int > size = std::vector< unsigned int >(3, 64), std::vector< double > outputOrigin = std::vector< double >(3, 0.0), std::vector< double > outputSpacing = std::vector< double >(3, 1.0), std::vector< double > outputDirection = std::vector< double >())
Generate a displacement field from a coordinate transform.
This function directly calls the execute method of TransformToDisplacementFieldFilter in order to support a procedural API
See also
itk::simple::TransformToDisplacementFieldFilter for the object oriented interface
TriangleThreshold() [1/2]
Image itk::simple::TriangleThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Triangle Threshold.
\
This function directly calls the execute method of TriangleThresholdImageFilter in order to support a procedural API
See also
itk::simple::TriangleThresholdImageFilter for the object oriented interface
TriangleThreshold() [2/2]
Image itk::simple::TriangleThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Triangle Threshold.
\
This function directly calls the execute method of TriangleThresholdImageFilter in order to support a procedural API
See also
itk::simple::TriangleThresholdImageFilter for the object oriented interface
UnaryMinus() [1/2]
Image itk::simple::UnaryMinus (const Image & image1)
Implements pixel-wise generic operation on one image.
\
This function directly calls the execute method of UnaryMinusImageFilter in order to support a procedural API
See also
itk::simple::UnaryMinusImageFilter for the object oriented interface
UnaryMinus() [2/2]
Image itk::simple::UnaryMinus (Image && image1)
Implements pixel-wise generic operation on one image.
\
This function directly calls the execute method of UnaryMinusImageFilter in order to support a procedural API
See also
itk::simple::UnaryMinusImageFilter for the object oriented interface
Referenced by operator-().
UnsharpMask()
Image itk::simple::UnsharpMask (const Image & image1, std::vector< double > sigmas = std::vector< double >(3, 1.0), double amount = 0.5, double threshold = 0.0)
Edge enhancement filter.
\
This function directly calls the execute method of UnsharpMaskImageFilter in order to support a procedural API
See also
itk::simple::UnsharpMaskImageFilter for the object oriented interface
Unused()
template<typename T > void SITKCommon_HIDDEN itk::simple::Unused (const T &)
A function which does nothing.
This function is to be used to mark parameters as unused to suppress compiler warning.
Definition at line 42 of file sitkTemplateFunctions.h.
ValuedRegionalMaxima()
Image itk::simple::ValuedRegionalMaxima (const Image & image1, bool fullyConnected = false)
Transforms the image so that any pixel that is not a regional maxima is set to the minimum value for the pixel type. Pixels that are regional maxima retain their value.
\
This function directly calls the execute method of ValuedRegionalMaximaImageFilter in order to support a procedural API
See also
itk::simple::ValuedRegionalMaximaImageFilter for the object oriented interface
ValuedRegionalMinima()
Image itk::simple::ValuedRegionalMinima (const Image & image1, bool fullyConnected = false)
Transforms the image so that any pixel that is not a regional minima is set to the maximum value for the pixel type. Pixels that are regional minima retain their value.
\
This function directly calls the execute method of ValuedRegionalMinimaImageFilter in order to support a procedural API
See also
itk::simple::ValuedRegionalMinimaImageFilter for the object oriented interface
VectorConfidenceConnected()
Image itk::simple::VectorConfidenceConnected (const Image & image1, std::vector< std::vector< unsigned int > > seedList = std::vector< std::vector< unsigned int > >(), unsigned int numberOfIterations = 4u, double multiplier = 4.5, unsigned int initialNeighborhoodRadius = 1u, uint8_t replaceValue = 1u)
Segment pixels with similar statistics using connectivity.
\
This function directly calls the execute method of VectorConfidenceConnectedImageFilter in order to support a procedural API
See also
itk::simple::VectorConfidenceConnectedImageFilter for the object oriented interface
VectorConnectedComponent()
Image itk::simple::VectorConnectedComponent (const Image & image1, double distanceThreshold = 1.0, bool fullyConnected = false)
A connected components filter that labels the objects in a vector image. Two vectors are pointing similar directions if one minus their dot product is less than a threshold. Vectors that are 180 degrees out of phase are similar. Assumes that vectors are normalized.
\
This function directly calls the execute method of VectorConnectedComponentImageFilter in order to support a procedural API
See also
itk::simple::VectorConnectedComponentImageFilter for the object oriented interface
VectorIndexSelectionCast() [1/2]
Image itk::simple::VectorIndexSelectionCast (const Image & image1, unsigned int index = 0u, PixelIDValueEnum outputPixelType = itk::simple::sitkUnknown)
Extracts the selected index of the vector that is the input pixel type.
\
This function directly calls the execute method of VectorIndexSelectionCastImageFilter in order to support a procedural API
See also
itk::simple::VectorIndexSelectionCastImageFilter for the object oriented interface
VectorIndexSelectionCast() [2/2]
Image itk::simple::VectorIndexSelectionCast (Image && image1, unsigned int index = 0u, PixelIDValueEnum outputPixelType = itk::simple::sitkUnknown)
Extracts the selected index of the vector that is the input pixel type.
\
This function directly calls the execute method of VectorIndexSelectionCastImageFilter in order to support a procedural API
See also
itk::simple::VectorIndexSelectionCastImageFilter for the object oriented interface
VectorMagnitude() [1/2]
Image itk::simple::VectorMagnitude (const Image & image1)
Take an image of vectors as input and produce an image with the magnitude of those vectors.
\
This function directly calls the execute method of VectorMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::VectorMagnitudeImageFilter for the object oriented interface
VectorMagnitude() [2/2]
Image itk::simple::VectorMagnitude (Image && image1)
Take an image of vectors as input and produce an image with the magnitude of those vectors.
\
This function directly calls the execute method of VectorMagnitudeImageFilter in order to support a procedural API
See also
itk::simple::VectorMagnitudeImageFilter for the object oriented interface
VotingBinary()
Image itk::simple::VotingBinary (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), unsigned int birthThreshold = 1u, unsigned int survivalThreshold = 1u, double foregroundValue = 1.0, double backgroundValue = 0.0)
Applies a voting operation in a neighborhood of each pixel.
\
This function directly calls the execute method of VotingBinaryImageFilter in order to support a procedural API
See also
itk::simple::VotingBinaryImageFilter for the object oriented interface
VotingBinaryHoleFilling()
Image itk::simple::VotingBinaryHoleFilling (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), unsigned int majorityThreshold = 1u, double foregroundValue = 1.0, double backgroundValue = 0.0)
Fills in holes and cavities by applying a voting operation on each pixel.
\
This function directly calls the execute method of VotingBinaryHoleFillingImageFilter in order to support a procedural API
See also
itk::simple::VotingBinaryHoleFillingImageFilter for the object oriented interface
VotingBinaryIterativeHoleFilling()
Image itk::simple::VotingBinaryIterativeHoleFilling (const Image & image1, std::vector< unsigned int > radius = std::vector< unsigned int >(3, 1), unsigned int maximumNumberOfIterations = 10u, unsigned int majorityThreshold = 1u, double foregroundValue = 1.0, double backgroundValue = 0.0)
Fills in holes and cavities by iteratively applying a voting operation.
\
This function directly calls the execute method of VotingBinaryIterativeHoleFillingImageFilter in order to support a procedural API
See also
itk::simple::VotingBinaryIterativeHoleFillingImageFilter for the object oriented interface
Warp()
Image itk::simple::Warp (const Image & image, const Image & displacementField, InterpolatorEnum interpolator = itk::simple::sitkLinear, std::vector< uint32_t > outputSize = std::vector< uint32_t >(3, 0), std::vector< double > outputOrigin = std::vector< double >(3, 0.0), std::vector< double > outputSpacing = std::vector< double >(3, 1.0), std::vector< double > outputDirection = std::vector< double >(), double edgePaddingValue = 0.0)
Warps an image using an input displacement field.
\
This function directly calls the execute method of WarpImageFilter in order to support a procedural API
See also
itk::simple::WarpImageFilter for the object oriented interface
WhiteTopHat()
Image itk::simple::WhiteTopHat (const Image & image1, std::vector< unsigned int > kernelRadius = std::vector< uint32_t >(3, 1), KernelEnum kernelType = itk::simple::sitkBall, bool safeBorder = true)
White top hat extracts local maxima that are larger than the structuring element.
\
This function directly calls the execute method of WhiteTopHatImageFilter in order to support a procedural API
See also
itk::simple::WhiteTopHatImageFilter for the object oriented interface
WienerDeconvolution()
Image itk::simple::WienerDeconvolution (const Image & image1, const Image & image2, double noiseVariance = 0.0, bool normalize = false, WienerDeconvolutionImageFilter::BoundaryConditionType boundaryCondition = itk::simple::WienerDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD, WienerDeconvolutionImageFilter::OutputRegionModeType outputRegionMode = itk::simple::WienerDeconvolutionImageFilter::SAME)
The Wiener deconvolution image filter is designed to restore an image convolved with a blurring kernel while keeping noise enhancement to a minimum.
\
This function directly calls the execute method of WienerDeconvolutionImageFilter in order to support a procedural API
See also
itk::simple::WienerDeconvolutionImageFilter for the object oriented interface
WrapPad()
Image itk::simple::WrapPad (const Image & image1, std::vector< unsigned int > padLowerBound = std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound = std::vector< unsigned int >(3, 0))
Increase the image size by padding with replicants of the input image value.
\
This function directly calls the execute method of WrapPadImageFilter in order to support a procedural API
See also
itk::simple::WrapPadImageFilter for the object oriented interface
WriteImage() [1/2]
SITKIO_EXPORT void itk::simple::WriteImage (const Image & image, const std::string & fileName, bool useCompression = false, int compressionLevel = -1)
WriteImage is a procedural interface to the ImageFileWriter. class which is convenient for many image writing tasks.
Parameters
image the input image to be written
fileName the filename of an Image e.g. "cthead.mha"
useCompression request to compress the written file
compressionLevel a hint for the amount of compression to be applied during writing
See also
itk::simple::ImageFileWriter for writing a single file.
Examples
CppCMake/Source/sitk_example.cxx, CppInPlace/CppInPlace.cxx, DicomSeriesReader/DicomSeriesReader.cxx, FastMarchingSegmentation/FastMarchingSegmentation.cxx, N4BiasFieldCorrection/N4BiasFieldCorrection.cxx, SimpleGaussianFunctional.cxx, SimpleIO/SimpleIO.cxx, and SliceBySliceDecorator/SliceBySliceDecorator.cxx.
WriteImage() [2/2]
SITKIO_EXPORT void itk::simple::WriteImage (const Image & image, const std::vector< std::string > & fileNames, bool useCompression = false, int compressionLevel = -1)
WriteImage is a procedural interface to the ImageSeriesWriter. class which is convenient for many image writing tasks.
Parameters
image the input image to be written
fileNames a vector of filenames of length equal to the number of slices in the image.
useCompression request to compress the written file
compressionLevel a hint for the amount of compression to be applied during writing.
See also
itk::simple::ImageFileWriter for writing a single file.
WriteTransform()
SITKCommon_EXPORT void itk::simple::WriteTransform (const Transform & transform, const std::string & filename)
Examples
DemonsRegistration1/DemonsRegistration1.cxx, DemonsRegistration2/DemonsRegistration2.cxx, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx, and SimpleIO/SimpleIO.cxx.
Xor() [1/5]
Image itk::simple::Xor (const Image & image1, const Image & image2)
Computes the XOR bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of XorImageFilter in order to support a procedural API
See also
itk::simple::XorImageFilter for the object oriented interface
Xor() [2/5]
Image itk::simple::Xor (const Image & image1, int constant)
Xor() [3/5]
Image itk::simple::Xor (Image && image1, const Image & image2)
Computes the XOR bitwise operator pixel-wise between two images.
\
This function directly calls the execute method of XorImageFilter in order to support a procedural API
See also
itk::simple::XorImageFilter for the object oriented interface
Referenced by operator^(), and operator^=().
Xor() [4/5]
Image itk::simple::Xor (Image && image1, int constant)
Xor() [5/5]
Image itk::simple::Xor (int constant, const Image & image2)
YenThreshold() [1/2]
Image itk::simple::YenThreshold (const Image & image, const Image & maskImage, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Yen Threshold.
\
This function directly calls the execute method of YenThresholdImageFilter in order to support a procedural API
See also
itk::simple::YenThresholdImageFilter for the object oriented interface
YenThreshold() [2/2]
Image itk::simple::YenThreshold (const Image & image, uint8_t insideValue = 1u, uint8_t outsideValue = 0u, uint32_t numberOfHistogramBins = 256u, bool maskOutput = true, uint8_t maskValue = 255u)
Threshold an image using the Yen Threshold.
\
This function directly calls the execute method of YenThresholdImageFilter in order to support a procedural API
See also
itk::simple::YenThresholdImageFilter for the object oriented interface
ZeroCrossing()
Image itk::simple::ZeroCrossing (const Image & image1, uint8_t foregroundValue = 1u, uint8_t backgroundValue = 0u)
This filter finds the closest pixel to the zero-crossings (sign changes) in a signed itk::Image .
\
This function directly calls the execute method of ZeroCrossingImageFilter in order to support a procedural API
See also
itk::simple::ZeroCrossingImageFilter for the object oriented interface
ZeroCrossingBasedEdgeDetection()
Image itk::simple::ZeroCrossingBasedEdgeDetection (const Image & image1, double variance = 1.0, uint8_t foregroundValue = 1u, uint8_t backgroundValue = 0u, double maximumError = 0.1)
This filter implements a zero-crossing based edge detecor.
\
This function directly calls the execute method of ZeroCrossingBasedEdgeDetectionImageFilter in order to support a procedural API
See also
itk::simple::ZeroCrossingBasedEdgeDetectionImageFilter for the object oriented interface
ZeroFluxNeumannPad()
Image itk::simple::ZeroFluxNeumannPad (const Image & image1, std::vector< unsigned int > padLowerBound = std::vector< unsigned int >(3, 0), std::vector< unsigned int > padUpperBound = std::vector< unsigned int >(3, 0))
Increase the image size by padding according to the zero-flux Neumann boundary condition.
\
This function directly calls the execute method of ZeroFluxNeumannPadImageFilter in order to support a procedural API
See also
itk::simple::ZeroFluxNeumannPadImageFilter for the object oriented interface